# Checks & Debugs regarding refactoring of code
Felix Zaussinger | XX.YY.ZZZZ

In [85]:
import os
import sys
import logging
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from src import utils
import mapping_career_causeways

# OPTIONAL: Load the "autoreload" extension so that code can change
%load_ext autoreload

# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2

# Settings
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

sns.set_context("poster")
sns.set(rc={"figure.figsize": (16, 9.0)})
sns.set_style("ticks")

pd.set_option("display.max_rows", 120)
pd.set_option("display.max_columns", 120)

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

# load paths
useful_paths = utils.UsefulPaths()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [227]:
from src.data.framework import Esco, Onet, Classifications, Crosswalks

esco = Esco()
onet = Onet()
clsf = Classifications()
crosswalks = Crosswalks()

ESCO Class

In [87]:
esco.occupations
esco.skills

,conceptType,conceptUri,skillType,reuseLevel,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,scopeNote,definition,inScheme,description
0,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0005c151-5b5a...,skill/competence,sector-specific,manage musical staff,manage staff of music\ncoordinate duties of mu...,NaN,released,2016-12-20T17:43:43Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Assign and manage staff tasks in areas such as...
1,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00064735-8fad...,skill/competence,occupation-specific,supervise correctional procedures,oversee prison procedures\nmanage correctional...,NaN,released,2016-12-20T20:17:49Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Supervise the operations of a correctional fac...
2,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/000709ed-2be5...,skill/competence,sector-specific,apply anti-oppressive practices,apply non-oppressive practices\napply an anti-...,NaN,released,2016-12-20T19:18:19Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Identify oppression in societies, economies, c..."
3,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0007bdc2-dd15...,skill/competence,sector-specific,control compliance of railway vehicles regulat...,monitoring of compliance with railway vehicles...,NaN,released,2016-12-20T20:02:19Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Inspect rolling stock, components and systems ..."
4,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00090cc1-1f27...,skill/competence,cross-sector,identify available services,establish available services\ndetermine rehabi...,NaN,released,2016-12-20T20:15:17Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Identify the different services available for ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13886,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/ffef5eb3-a15e...,skill/competence,sector-specific,remediate healthcare user's occupational perfo...,restore healthcare user's occupational perform...,NaN,released,2016-12-20T19:25:53Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,"Remediate or restore the cognitive, sensorimot..."
13887,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff0b074-5a76...,skill/competence,sector-specific,install transport equipment lighting,install transport equipment illumination\nfix ...,NaN,released,2016-12-20T20:03:21Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Install lighting elements in transport equipme...
13888,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff0e2cd-d0bd...,knowledge,sector-specific,natural language processing,NLP,NaN,released,2016-08-04T15:19:37Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,The technologies which enable ICT devices to u...
13889,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff5bc45-b506...,skill/competence,cross-sector,coordinate construction activities,reviewing construction progress\nconstruction ...,NaN,released,2016-12-20T18:22:35Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Coordinate the activities of several construct...
13890,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff74a70-4f82...,skill/competence,cross-sector,position guardrails and toeboards,positioning guardrails and toeboards\nattachme...,NaN,released,2016-12-20T18:24:23Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Attach guardrails and toeboards to the scaffol...

Onet Class

In [228]:
onet.green_occupations_gtp
onet.green_occupations_vona2018
onet.green_tasks_gtp
onet.brown_occupations_vona2018
onet.green_occupations_narrow_jrc
onet.green_occupations_gilli2020

    ISCO_code  share_green_gilli2020
0         111                  0.028
1         112                  0.034
2         121                  0.008
3         122                  0.202
4         131                  0.061
..        ...                    ...
122       941                  0.000
123       951                  0.000
124       952                  0.000
125       961                  0.692
126       962                  0.099

[127 rows x 2 columns]

Calculating occ-skills matrix with more flexibility

In [89]:
osm_weighted = esco.read_occ_skills_matrix(return_version="weighted")
np.unique(osm_weighted)

array([0. , 0.5, 1. ])

In [90]:
osm_unweighted = esco.read_occ_skills_matrix(
    return_version="unweighted", assign_labels=True
)
np.unique(osm_unweighted)

array([0, 1], dtype=int64)

In [91]:
osm_encoded = esco.read_occ_skills_matrix(return_version="raw", assign_labels=True)
np.unique(osm_encoded)

array([0, 1, 2], dtype=int64)

In [92]:
osm_weighted = esco.label_osm(osm_weighted)
osm_weighted

,manage musical staff,supervise correctional procedures,apply anti-oppressive practices,control compliance of railway vehicles regulations,identify available services,perform toxicological studies,ensure coquille uniformity,Haskell,show initiative,train staff to reduce food waste,apply diplomatic principles,lead police investigations,handle fish harvesting waste,develop energy saving concepts,perform street interventions in social work,work with soloists,sport and exercise medicine,conduct research on flora,install heat pump,design biomass installations,handle equipment while suspended,teach housekeeping skills,check train engines,influence public policies,enterprise risk management,manufacture ingredients,maintain aquaculture ponds,apply credit risk policy,handle customer requests related to cargo,draft scientific or academic papers and technical documentation,Incremental development,use of special equipment for daily activities,sawing techniques,produce guitar components,operate agricultural machinery,control pyrotechnics stock,guarantee customer satisfaction,manufacture wearing apparel products,cure tobacco leaves,develop a rehabilitation programme,maintain inventory of cleaning supplies,cold vulcanisation,supervise housekeeping operations,act as contact person during equipment incident,manage time in landscaping,advise on customs regulations,manage university department,develop terminology databases,assess nutritional characteristics of food,repair electric bicycles,maintain sorting equipment,explain features in accommodation venue,types of barley,KDevelop,purchase vehicle parts,inspect offshore constructions,transport patient to medical facility,adjust envelope cutting settings,prepare oils,purchase supplies,...,establish gaming policies,media and information literacy,evaluate clinical outcomes of dental hygiene interventions,gem cutting forms,cut pig's teeth,provide therapy of the visual system,administer materials to tea bag machines,advise on bank account,manage dental emergencies,assume highest level of responsibility in inland water transportation,manage time in food processing operations,student financial aid programmes,interpret pedigree charts,perform software recovery testing,astronomy,use instruments for food measurement,tend ball mill,understand spoken Norwegian,cut filament,procure time sheet approval,communicate with a non-scientific audience,prepare soda-ash,microchip scanners,rope lashing,create social alliances,assess your competencies in leading community arts,write Occitan,arrange customs inspection,perform nutrition analysis,analyse work-related written reports,surveillance methods,remove old caulking,keep company,clean patients' ear canals,anodising process,preserve samples,treat vehicle fabrics,collect domestic waste,perform energy simulations,match vessels to shipping routes,types of drill bits,cable-propelled transit,negotiate rights of use,Capture One,precious metal processing,control train movement,dependency on drugs,organise vehicle parts storage,set up reinforcing steel,model sensor,Scala,operate forestry equipment,test soil load bearing capacity,buy new library items,design clocks,remediate healthcare user's occupational performance,install transport equipment lighting,natural language processing,coordinate construction activities,position guardrails and toeboards
technical director,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
metal drawing machine operator,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.5,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
precision device inspector,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
air traffic safety technician,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
hospitality revenue manager,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
demographer,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,1.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
sorter labourer,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
armoured car guard,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.5,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
civil service administrative officer,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
motor vehicle assembler,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0

In [93]:
osm_weighted[osm_weighted == 1].sum(axis=1).describe()

count    3008.000000
mean       21.640957
std        12.145173
min         0.000000
25%        14.000000
50%        19.000000
75%        26.000000
max       133.000000
dtype: float64

In [94]:
osm_weighted[osm_weighted == 0.5].sum(axis=1).describe()

count    3008.000000
mean        9.766622
std        10.787132
min         0.000000
25%         4.500000
50%         8.500000
75%        11.500000
max       159.500000
dtype: float64

In [95]:
osm_unweighted[osm_unweighted == 1].sum(axis=1).describe()

count    3008.000000
mean       41.174202
std        24.990325
min         4.000000
25%        27.000000
50%        36.000000
75%        48.000000
max       340.000000
dtype: float64

Combining skills metadata

In [96]:
smd = esco.combine_skills_metadata(variable_selection=None)
smd

C:\Users\fzaussinger\Miniconda3\envs\re4gt\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
C:\Users\fzaussinger\Miniconda3\envs\re4gt\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,conceptType,conceptUri,skillType,reuseLevel,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,scopeNote,definition,inScheme,description,broaderConceptUri,broaderConceptPT,alternative_class_eth,skill_green_eth,skill_green_esco,impact_eth,scope_eth,machineScore_green,comment_eth,skill_brown_eth,alternative_class_eth_brown,scope_eth_brown,impact_eth_brown,comment_eth_brown,skill_brown_esco,machineScore_brown,skill_neutral_esco,skill_classification_esco,coreness
0,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0005c151-5b5a...,skill/competence,sector-specific,manage musical staff,manage staff of music\ncoordinate duties of mu...,NaN,released,2016-12-20T17:43:43Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Assign and manage staff tasks in areas such as...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,True,neutral,0.002187
1,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00064735-8fad...,skill/competence,occupation-specific,supervise correctional procedures,oversee prison procedures\nmanage correctional...,NaN,released,2016-12-20T20:17:49Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Supervise the operations of a correctional fac...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,True,neutral,0.000000
2,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/000709ed-2be5...,skill/competence,sector-specific,apply anti-oppressive practices,apply non-oppressive practices\napply an anti-...,NaN,released,2016-12-20T19:18:19Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Identify oppression in societies, economies, c...",NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,True,neutral,0.000748
3,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0007bdc2-dd15...,skill/competence,sector-specific,control compliance of railway vehicles regulat...,monitoring of compliance with railway vehicles...,NaN,released,2016-12-20T20:02:19Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Inspect rolling stock, components and systems ...",NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,True,neutral,0.049473
4,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00090cc1-1f27...,skill/competence,cross-sector,identify available services,establish available services\ndetermine rehabi...,NaN,released,2016-12-20T20:15:17Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Identify the different services available for ...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,True,neutral,0.001577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13886,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/ffef5eb3-a15e...,skill/competence,sector-specific,remediate healthcare user's occupational perfo...,restore healthcare user's occupational perform...,NaN,released,2016-12-20T19:25:53Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,"Remediate or restore the cognitive, sensorimot...",NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,True,neutral,0.000103
13887,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff0b074-5a76...,skill/competence,sector-specific,install transport equipment lighting,install transport equipment illumination\nfix ...,NaN,released,2016-12-20T20:03:21Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Install lighting elements in transport equipme...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,True,neutral,0.013943
13888,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff0e2cd-d0bd...,knowledge,sector-specific,natural language processing,NLP,NaN,released,2016-08-04T15:19:37Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,The technologies which enable ICT devices to u...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,True,neutral,0.025162
13889,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff5bc45-b506...,skill/competence,cross-sector,coordinate construction activities,reviewing construction progress\nconstruction ...,NaN,released,2016-12-20T18:22:35Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Coordinate the activities of several construct...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,True,neutral,0.065232
13890,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff74a70-4f82...,skill/competence,cross-sector,position guardrails and toeboards,positioning guardrails and toeboards\nattachme...,NaN,released,2016-12-20T18:24:23Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Attach guardrails and toeboards to the scaffol...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,True,neutral,0.006670

Calculating GBN shares at occupation level

In [97]:
esco.calc_gbn_shares_skill_based(skills_metadata=smd)

,conceptUri,n_total_specific_skills,n_green_specific_skills_esco,share_green_esco,n_brown_specific_skills_esco,share_brown_esco,n_neutral_specific_skills_esco,share_neutral_esco,gbn_classification_esco
0,http://data.europa.eu/esco/occupation/00030d09...,8,0,0.000000,0,0.000000,8,1.000000,neutral
1,http://data.europa.eu/esco/occupation/000e93a3...,39,0,0.000000,5,0.128205,34,0.871795,neutral
2,http://data.europa.eu/esco/occupation/0019b951...,43,0,0.000000,0,0.000000,43,1.000000,neutral
3,http://data.europa.eu/esco/occupation/0022f466...,39,2,0.051282,0,0.000000,37,0.948718,neutral
4,http://data.europa.eu/esco/occupation/002da35b...,26,0,0.000000,0,0.000000,26,1.000000,neutral
...,...,...,...,...,...,...,...,...,...
3003,http://data.europa.eu/esco/occupation/ff656b3a...,58,0,0.000000,0,0.000000,58,1.000000,neutral
3004,http://data.europa.eu/esco/occupation/ff8d4065...,26,14,0.538462,0,0.000000,12,0.461538,green
3005,http://data.europa.eu/esco/occupation/ffa4dd5d...,29,0,0.000000,1,0.034483,28,0.965517,neutral
3006,http://data.europa.eu/esco/occupation/ffade2f4...,31,0,0.000000,0,0.000000,31,1.000000,neutral
3007,http://data.europa.eu/esco/occupation/ffc292f1...,57,1,0.017544,1,0.017544,55,0.964912,neutral

Preprocessing of EU-LFS data

In [130]:
config = utils.load_config(os.path.join(useful_paths.config_dir, "eu_lfs_config.yml"))
config

{'paths': {'raw': 'C:\\eurostat_data\\raw',
  'raw_yf': 'C:\\eurostat_data\\raw\\Yearly_Data\\YearlyFiles_83_2019\\_YearlyFiles',
  'interim': 'C:\\eurostat_data\\interim',
  'processed': 'C:\\eurostat_data\\processed',
  'fmt_folder': '{country}_YEAR_1998_onwards',
  'fmt_file': '{country}{year}_y.csv'},
 'preprocessing': {'n_digits_isco08': 3,
  'n_digits_nace': 1,
  'n_digits_nuts': 2,
  'years': ['2019'],
  'countries': ['AT',
   'BE',
   'BG',
   'CH',
   'CY',
   'CZ',
   'DE',
   'DK',
   'EE',
   'ES',
   'FI',
   'FR',
   'GR',
   'HR',
   'HU',
   'IE',
   'IS',
   'IT',
   'LT',
   'LU',
   'LV',
   'MT',
   'NL',
   'NO',
   'PL',
   'PT',
   'RO',
   'SE',
   'SI',
   'SK',
   'UK'],
  'countries_isco08_2d': ['BG', 'PL'],
  'countries_isco08_1d': ['MT'],
  'countries_nuts_1d': ['UK'],
  'countries_nuts_0d': ['MT', 'NL'],
  'scaling_factor_coeff': 1000,
  'pension_age': ['77', '82', '87', '92', '97'],
  'variables': ['WSTATOR',
   'SEX',
   'NACE1D',
   'ISCO3D',
   'COUNTRYW',
   'REGIONW',
   'FTPT',
   'REFYEAR',
   'COUNTRY',
   'REGION',
   'DEGURBA',
   'HHTYPE',
   'AGE',
   'ILOSTAT',
   'EDUC4WN',
   'HATLEV1D',
   'MAINSTAT',
   'INCDECIL',
   'COEFF'],
  'na_values': {'WSTATOR': ['9'],
   'SEX': ['9'],
   'NACE1D': ['9'],
   'ISCO3D': ['999'],
   'COUNTRYW': ['99'],
   'REGIONW': ['00', '99'],
   'FTPT': ['9'],
   'REFYEAR': ['9999'],
   'COUNTRY': ['99'],
   'REGION': ['00'],
   'ILOSTAT': ['9'],
   'EDUC4WN': ['9'],
   'HATLEV1D': ['9'],
   'MAINSTAT': ['9'],
   'INCDECIL': ['99']},
  'dtypes_in': {'WSTATOR': 'str',
   'SEX': 'str',
   'NACE1D': 'str',
   'ISCO3D': 'str',
   'COUNTRYW': 'str',
   'REGIONW': 'str',
   'FTPT': 'str',
   'REFYEAR': 'str',
   'COUNTRY': 'str',
   'REGION': 'str',
   'DEGURBA': 'str',
   'HHTYPE': 'str',
   'AGE': 'str',
   'ILOSTAT': 'str',
   'EDUC4WN': 'str',
   'HATLEV1D': 'str',
   'MAINSTAT': 'str',
   'INCDECIL': 'str',
   'COEFF': 'float'},
  'dtypes_out': {'WSTATOR': 'category',
   'SEX': 'category',
   'NACE1D': 'category',
   'ISCO3D': 'category',
   'COUNTRYW': 'category',
   'REGIONW': 'category',
   'FTPT': 'category',
   'REFYEAR': 'category',
   'COUNTRY': 'category',
   'REGION': 'category',
   'DEGURBA': 'category',
   'HHTYPE': 'category',
   'AGE': 'category',
   'ILOSTAT': 'category',
   'EDUC4WN': 'category',
   'HATLEV1D': 'category',
   'MAINSTAT': 'category',
   'INCDECIL': 'category',
   'COEFF': 'float'}},
 'visualisation': {'epsg': 3035,
  'bbox_eu_epsg_3035': [2500000.0, 6000000.0, 1300000.0, 5500000.0],
  'missing_kwds': {'facecolor': 'white', 'hatch': '//', 'edgecolor': 'grey'},
  'edgecolor': 'grey',
  'linewidth': 0.5,
  'robust_cmap_percentiles': [2, 98],
  'cmap': 'Greys',
  'countries_for_maps': ['AT',
   'BE',
   'CH',
   'CY',
   'CZ',
   'DE',
   'DK',
   'EE',
   'ES',
   'FI',
   'FR',
   'GR',
   'HR',
   'HU',
   'IE',
   'IS',
   'IT',
   'LT',
   'LU',
   'LV',
   'NL',
   'NO',
   'PT',
   'RO',
   'SE',
   'SI',
   'SK',
   'UK']}}

In [131]:
from src.data.lfs import EuLfs

lfs = EuLfs(config=config)

In [204]:
lfs.read_raw_file("NL", "2019")

,QHHNUM,HHNUM,HHSEQNUM,SEX,NATIONAL,YEARESID,COUNTRYB,PROXY,WSTATOR,NOWKREAS,STAPRO,SIGNISAL,NACE1D,NA111D,ISCO3D,IS883D,COUNTRYW,REGIONW,YSTARTWK,MSTARTWK,FTPT,TEMP,TEMPDUR,HWUSUAL,HWACTUAL,HWOVERP,HWOVERPU,HOURREAS,WISHMORE,HWWISH,LOOKOJ,EXIST2J,STAPRO2J,NACE2J1D,NA112J1D,HWACTUA2,EXISTPR,YEARPR,MONTHPR,STAPROPR,NACEPR1D,NA11PR1D,ISCOPR3D,IS88PR3D,SEEKWORK,SEEKTYPE,SEEKDUR,METHODA,METHODB,METHODC,METHODD,METHODE,METHODF,METHODG,METHODH,METHODI,METHODJ,METHODK,METHODL,METHODM,...,SHIFTWK,EVENWK,NIGHTWK,SATWK,SUNWK,WAYMORE,HOMEWK,LOOKREAS,LEAVREAS,SEEKREAS,AVAIREAS,PRESEEK,NEEDCARE,REGISTER,MAINSTAT,EDUCFILD,COURPURP,COURFILD,COURWORH,HATFIELD,HATYEAR,WSTAT1Y,STAPRO1Y,NACE1Y1D,NA111Y1D,NA111YS,COUNTR1Y,REGION1Y,INCDECIL,ESEG1D,ESEG2D,HWUSTRAI,METHFW,PURP4W,LENTR4W,HHPERS,HHPARENT,HHPARTNR,HHCHILDR,HATLFATH,HATLMOTH,HHNBPERS,HHNB0014,HHNBOLD,HHNBCHLD,HHNBCH2,HHNBCH5,HHNBCH8,HHNBCH11,HHNBCH14,HHNBCH17,HHNBCH24,HHAGEYG,HHAGE14,HHCOMP,HHNBWORK,HHNBEMPL,HHNBUNEM,HHNBINAC,HHWKSTAT
0,Q1352728,352728,1,2,001-EU15,02,007-OTHER EUROPE,2,5,99,9,9,9,9.0,999.0,NaN,99,99,9999.0,99.0,9,9.0,9.0,99,99.0,99.0,99.0,99.0,9,99.0,9,9,9,9,9.0,99.0,1.0,2018.0,4.0,3.0,J,NaN,352.0,NaN,3,9.0,9.0,9,9,9,9,9,9,9,9,9,9,9,9,9,...,9.0,9.0,9.0,9.0,9.0,9,9.0,9,9.0,3.0,9.0,9.0,4,4,7.0,999,9.0,999,9.0,999,1999.0,1.0,3.0,J,NaN,NaN,NL,0,99.0,9,99,NaN,99.0,NaN,NaN,4,4,1,1,8,8,4,2,0,2,0,1,1,0,0,0,0,3.0,3.0,21,1,1,0,1,3
1,Q1352728,352728,2,1,000-OWN COUNTRY,00,000-OWN COUNTRY,1,1,99,3,9,K,NaN,251.0,NaN,NL,0,2018.0,4.0,1,1.0,9.0,40,50.0,0.0,0.0,1.0,0,40.0,0,1,9,9,9.0,99.0,9.0,9999.0,99.0,9.0,9,9.0,999.0,NaN,9,9.0,9.0,9,9,9,9,9,9,9,9,9,9,9,9,9,...,3.0,3.0,3.0,3.0,3.0,9,2.0,9,99.0,9.0,9.0,9.0,9,4,1.0,999,9.0,999,9.0,999,2001.0,1.0,3.0,NaN,NaN,NaN,NL,0,10.0,2,21,NaN,99.0,9.0,9.0,4,4,1,1,8,8,4,2,0,2,0,1,1,0,0,0,0,3.0,3.0,21,1,1,0,1,3
2,Q1352728,352728,3,2,000-OWN COUNTRY,02,001-EU15,9,9,99,9,9,9,9.0,999.0,NaN,99,99,9999.0,99.0,9,9.0,9.0,99,99.0,99.0,99.0,99.0,9,99.0,9,9,9,9,9.0,99.0,9.0,9999.0,99.0,9.0,9,9.0,999.0,NaN,9,9.0,9.0,9,9,9,9,9,9,9,9,9,9,9,9,9,...,9.0,9.0,9.0,9.0,9.0,9,9.0,9,99.0,9.0,9.0,9.0,9,9,9.0,999,9.0,999,9.0,999,9999.0,9.0,9.0,9,9.0,9.0,NL,0,99.0,9,99,NaN,99.0,9.0,9.0,1,3,2,2,M,H,4,2,0,2,0,1,1,0,0,0,0,3.0,3.0,21,1,1,0,1,3
3,Q1352728,352728,4,1,000-OWN COUNTRY,02,001-EU15,9,9,99,9,9,9,9.0,999.0,NaN,99,99,9999.0,99.0,9,9.0,9.0,99,99.0,99.0,99.0,99.0,9,99.0,9,9,9,9,9.0,99.0,9.0,9999.0,99.0,9.0,9,9.0,999.0,NaN,9,9.0,9.0,9,9,9,9,9,9,9,9,9,9,9,9,9,...,9.0,9.0,9.0,9.0,9.0,9,9.0,9,99.0,9.0,9.0,9.0,9,9,9.0,999,9.0,999,9.0,999,9999.0,9.0,9.0,9,9.0,9.0,NL,0,99.0,9,99,NaN,99.0,9.0,9.0,1,3,2,2,M,H,4,2,0,2,0,1,1,0,0,0,0,3.0,3.0,21,1,1,0,1,3
4,Q1352733,352733,1,2,000-OWN COUNTRY,00,000-OWN COUNTRY,1,5,99,9,9,9,9.0,999.0,NaN,99,99,9999.0,99.0,9,9.0,9.0,99,99.0,99.0,99.0,99.0,9,99.0,9,9,9,9,9.0,99.0,1.0,2014.0,99.0,NaN,NaN,NaN,NaN,NaN,3,9.0,9.0,9,9,9,9,9,9,9,9,9,9,9,9,9,...,9.0,9.0,9.0,9.0,9.0,9,9.0,9,9.0,6.0,9.0,9.0,9,4,4.0,999,9.0,999,9.0,0,2006.0,NaN,9.0,9,9.0,9.0,NL,0,99.0,8,80,NaN,99.0,9.0,9.0,4,4,2,2,8,8,1,0,1,0,0,0,0,0,0,0,0,NaN,NaN,10,0,0,0,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73614,Q4412476,412476,2,1,007-OTHER EUROPE,04,007-OTHER EUROPE,2,1,99,0,9,R,NaN,265.0,NaN,NL,0,2018.0,NaN,2,9.0,9.0,18,18.0,99.0,99.0,97.0,0,18.0,0,1,9,9,9.0,99.0,9.0,9999.0,99.0,9.0,9,9.0,999.0,NaN,9,9.0,9.0,9,9,9,9,9,9,9,9,9,9,9,9,9,...,9.0,1.0,1.0,1.0,1.0,9,3.0,9,99.0,9.0,9.0,9.0,9,4,1.0,999,9.0,999,9.0,999,1998.0,3.0,9.0,9,9.0,9.0,NL,0,99.0,2,24,NaN,99.0,9.0,9.0,4,4,1,2,8,8,2,0,0,0,0,0,0,0,0,0,0,NaN,NaN,20,2,2,0,0,2
73615,Q4412477,412477,1,1,000-OWN COUNTRY,00,000-OWN COUNTRY,1,2,4,3,9,O,NaN,252.0,NaN,NL,0,2002.0,99.0,1,1.0,9.0,38,0.0,0.0,0.0,99.0,0,1.0,0,1,9,9,9.0,99.0,9.0,9999.0,99.0,9.0,9,9.0,999.0,NaN,9,9.0,9.0,9,9,9,9,9,9,9,9,9,9,9,9,9,...,3.0,3.0,3.0,3.0,3.0,9,2.0,9,99.0,9.0,9.0,9.0,9,4,5.0,999,9.0,999,9.0,999,1976.0,1.0,3.0,O,NaN,NaN,NL,0,9.0,2,21,NaN,99.0,9.0,9.0,4,4,1,2,8,8,2,0,0,0,0,0,0,0,0,0,0,NaN,NaN,20,1,1,0,1,3
73616,Q4412477,412477,2,2,000-OWN COUNTRY,00,000-OWN COUNTRY,2,5,99,9,9,9,9.0,999.0,NaN,99,99,9999.0,99.0,9,9.0,9.0,99,99.0,99.0,99.0,99.0,9,99.0,9,9,9,9,9.0,99.0,1.0,2015.0,99.0,NaN,NaN,NaN,NaN,NaN,3,9.0,9.0,9,9,9,9,9,9,9,9,9,9,9,9,9,...,9.0,9.0,9.0,9.0,9.0,9,9.0,9,4.0,2.0,9.0,9.0,9,4,7.0,999,9.0,999,9.0,999,1981.0,5.0,9.0,9,9.0,9.0,NL,0,99.0,9,99,NaN,99.0,9.0,9.0,4,4,1,2,8,8,2,0,0,0,0,0,0,0,0,0,0,NaN,NaN,20,1,1,0,1,3
73617,Q4412480,412480,1,2,000-OWN COUNTRY,00,000-OWN COUNTRY,1,5,99,9,9,9,9.0,999.0,NaN,99,99,9999.0,99.0,9,9.0,9.0,99,99.0,99.0,99.0,99.0,9,99.0,9,9,9,9,9.0,99.0,1.0,2008.0,99.0,9.0,9,9.0,999.0,NaN,3,9.0,9.0,9,9,9,9,9,9,9,9,9,9,9,9,9,...,9.0,9.0,9.0,9.0,9.0,9,9.0,9,99.0,6.0,9.0,9.0,9,4,4.0,999,9.0,999,9.0,999,1963.0,NaN,9.0,9,9.0,9.0,NL,0,99.0,8,80,NaN,99.0,9.0,9.0,4,4,2,2,8,8,1,0,1,0,0,0,0,0,0,0,0,NaN,NaN,10,0,0,0,1,5
73618,Q4412481,412481,1,1,000-OWN COUNTRY,00,000-OWN COUNTRY,1,5,99,9,9,9,9.0,999.0,NaN,99,99,9999.0,99.0,9,9.0,9.0,99,99.0,99.0,99.0,99.0,9,99.0,9,9,9,9,9.0,99.0,1.0,2003.0,99.0,9.0,9,9.0,999.0,NaN,3,9.0,9.0,9,9,9,9,9,9,9,9,9,9,9,9,9,...,9.0,9.0,9.0,9.0,9.0,9,9.0,9,99.0,6.0,9.0,9.0,9,4,4.0,999,9.0,999,9.0,999,1972.0,NaN,9.0,9,9.0,9.0,NL,0,99.0,8,80,NaN,99.0,9.0,9.0,4,4,2,2,8,8,1,0,1,0,0,0,0,0,0,0,0,NaN,NaN,10,0,0,0,1,5

In [203]:
lfs.read_filtered_file("NL", "2019", return_filtering_stats=False).ISCO3D.sort_values()

47089    100
69010    100
64477    100
8434     100
36888    100
        ...
21632    962
37318    962
19601    962
41584    962
15504    962
Name: ISCO3D, Length: 43178, dtype: object

In [101]:
lfs.preprocess_files(years=["2017"], countries=["AT", "DE"], save_file=True)

2017
AT
DE

In [194]:
lfs.read_preprocessed_file(year=2019).ISCO.str.len()

0          3
1          3
2          3
3          3
4          3
          ..
1538248    3
1538249    3
1538250    3
1538251    3
1538252    3
Name: ISCO, Length: 1538253, dtype: int64

In [195]:
test = pd.read_pickle(
    r"T:\Documents\Projects\04_jrc_green-skills-regional\03_data-analysis\re4gt\data\interim\esco\occ_metadata_en_by_isco08.pkl"
)
test

,isco_level_1,isco_label_1,share_green_gtp_mean,n_occ_esco_sum,share_green_esco_mean,share_brown_esco_mean,share_neutral_esco_mean,isco_code,isco_level_2,isco_label_2,isco_level_3,isco_label_3,isco_level_4,isco_label_4
0,0,Armed forces occupations,0.000000,21.0,0.002783,0.001642,0.995575,0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Managers,0.238567,338.0,0.033836,0.005270,0.960894,1,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Professionals,0.321054,846.0,0.044372,0.009094,0.946534,2,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Technicians and associate professionals,0.321925,653.0,0.048199,0.010582,0.941218,3,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Clerical support workers,0.164054,89.0,0.024906,0.003998,0.971096,4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,NaN,NaN,0.000000,1.0,0.115385,0.000000,0.884615,9613,NaN,NaN,NaN,NaN,9613,Sweepers and related labourers
599,NaN,NaN,0.000000,2.0,0.000000,0.000000,1.000000,9621,NaN,NaN,NaN,NaN,9621,"Messengers, package deliverers and luggage por..."
600,NaN,NaN,0.000000,1.0,0.041667,0.000000,0.958333,9622,NaN,NaN,NaN,NaN,9622,Odd job persons
601,NaN,NaN,0.000000,2.0,0.104167,0.000000,0.895833,9623,NaN,NaN,NaN,NaN,9623,Meter readers and vending-machine collectors
602,NaN,NaN,0.000000,7.0,0.009874,0.010989,0.979137,9629,NaN,NaN,NaN,NaN,9629,Elementary workers not elsewhere classified

In [103]:
lfs.join_covariates(year=2017, isco_covariate_selection=["share_green_esco_mean"])

,AGE,COEFF,COEFF_share_green_esco_mean,COUNTRY,COUNTRYW,DEGURBA,EDUC4WN,FTPT,HATLEV1D,HHTYPE,ILOSTAT,INCDECIL,ISCO,ISCO3D,MAINSTAT,NACE1D,NACE1D_label,NUTS_ID,REFYEAR,REGION,REGIONW,SEX,WSTATOR,share_green_esco_mean
0,52,35.6900,1.303954,AT,AT,2,0,1,M,1,1,08,541,541,1,H,Transportation and Storage,AT22,2017,20,22,1,1,0.036536
1,42,63.8975,0.000000,AT,AT,2,0,1,M,1,1,05,334,334,1,G,Wholesale and Retail Trade; Repair of Motor Ve...,AT22,2017,20,22,1,1,0.000000
2,57,52.1800,0.236335,AT,AT,2,0,2,M,1,1,02,522,522,1,G,Wholesale and Retail Trade; Repair of Motor Ve...,AT22,2017,20,22,2,1,0.004529
3,37,57.9800,0.693583,AT,AT,2,0,1,M,1,1,07,812,812,1,C,Manufacturing,AT22,2017,20,22,1,1,0.011962
4,37,57.9800,0.000000,AT,AT,2,0,1,H,1,1,NaN,431,431,8,K,Financial and Insurance Activities,AT22,2017,20,22,2,2,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349968,27,145.9850,0.460371,DE,DE,3,0,2,H,1,1,07,341,341,1,P,Education,DEG0,2017,G0,G0,2,2,0.003154
349969,27,150.8525,1.742801,DE,DE,3,0,1,M,1,1,07,721,721,1,C,Manufacturing,DEG0,2017,G0,G0,1,1,0.011553
349970,27,150.8525,0.683244,DE,DE,3,0,1,M,1,1,05,522,522,1,G,Wholesale and Retail Trade; Repair of Motor Ve...,DEG0,2017,G0,G0,2,1,0.004529
349971,37,130.6400,4.930682,DE,DE,3,0,1,H,1,1,08,216,216,1,M,"Professional, Scientific and Technical Activities",DEG0,2017,G0,G0,1,1,0.037743
349972,37,130.6400,0.303870,DE,DE,3,0,1,H,1,1,08,263,263,1,O,Public Administration and Defence; Compulsory ...,DEG0,2017,G0,G0,2,1,0.002326

In [186]:
df = lfs.read_merged_file(year=2019, n_digits_isco=3)

In [190]:
np.unique(df.ISCO.str.len())

array([3], dtype=int64)

In [225]:
df = lfs.read_merged_file(year=2019, n_digits_isco=3)

KeyError: 'ISCO'

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1412535 entries, 0 to 1538252
Data columns (total 39 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   AGE                            1412535 non-null  category
 1   COEFF                          1409685 non-null  float64
 2   COEFF_share_brown_esco_mean    1402491 non-null  float64
 3   COEFF_share_green_esco_mean    1402491 non-null  float64
 4   COEFF_share_green_gtp_mean     1402491 non-null  float64
 5   COEFF_share_neutral_esco_mean  1402491 non-null  float64
 6   COUNTRY                        1412535 non-null  category
 7   COUNTRYW                       1412535 non-null  category
 8   DEGURBA                        1412535 non-null  category
 9   EDUC4WN                        1410234 non-null  category
 10  FTPT                           1412417 non-null  category
 11  HATLEV1D                       1408992 non-null  category
 12  HHTYPE                         1412535 non-null  category
 13  ILOSTAT                        1412535 non-null  category
 14  INCDECIL                       897211 non-null   category
 15  ISCO                           1412535 non-null  object
 16  ISCO3D                         1412535 non-null  category
 17  MAINSTAT                       1370889 non-null  category
 18  NACE1D                         1407041 non-null  category
 19  NACE1D_label                   1407041 non-null  object
 20  NUTS_ID                        1350491 non-null  object
 21  REFYEAR                        1412535 non-null  category
 22  REGION                         1320211 non-null  category
 23  REGIONW                        1307977 non-null  category
 24  SEX                            1412535 non-null  category
 25  WSTATOR                        1412535 non-null  category
 26  isco_label_1                   0 non-null        object
 27  isco_label_2                   0 non-null        object
 28  isco_label_3                   1405341 non-null  object
 29  isco_label_4                   0 non-null        object
 30  isco_level_1                   0 non-null        object
 31  isco_level_2                   0 non-null        object
 32  isco_level_3                   1405341 non-null  object
 33  isco_level_4                   0 non-null        object
 34  n_occ_esco_sum                 1405341 non-null  float64
 35  share_brown_esco_mean          1405341 non-null  float64
 36  share_green_esco_mean          1405341 non-null  float64
 37  share_green_gtp_mean           1405341 non-null  float64
 38  share_neutral_esco_mean        1405341 non-null  float64
dtypes: category(18), float64(10), object(11)
memory usage: 262.7+ MB

In [224]:
greenness_gilli_2020 = pd.read_excel(
    os.path.join(useful_paths.data_raw, "onet", "Gilli2020_AppC_Greenness_ISCO3D.xlsx"),
    dtype={"ISCO": "str"},
)
greenness_gilli_2020

    ISCO  share_green_gilli2020
0    111                  0.028
1    112                  0.034
2    121                  0.008
3    122                  0.202
4    131                  0.061
..   ...                    ...
122  941                  0.000
123  951                  0.000
124  952                  0.000
125  961                  0.692
126  962                  0.099

[127 rows x 2 columns]

In [217]:
df[df.share_green_esco_mean.isna()].ISCO.unique()

array(['633', '632', '631', '224', '634'], dtype=object)

In [170]:
df.ISCO3D.cat.categories.values

array(['000', '010', '011', '020', '021', '030', '031', '100', '110',
       '111', '112', '120', '121', '122', '130', '131', '132', '133',
       '134', '140', '141', '142', '143', '200', '210', '211', '212',
       '213', '214', '215', '216', '220', '221', '222', '223', '224',
       '225', '226', '230', '231', '232', '233', '234', '235', '240',
       '241', '242', '243', '250', '251', '252', '260', '261', '262',
       '263', '264', '265', '300', '310', '311', '312', '313', '314',
       '315', '320', '321', '322', '323', '324', '325', '330', '331',
       '332', '333', '334', '335', '340', '341', '342', '343', '350',
       '351', '352', '400', '410', '411', '412', '413', '420', '421',
       '422', '430', '431', '432', '440', '441', '500', '510', '511',
       '512', '513', '514', '515', '516', '520', '521', '522', '523',
       '524', '530', '531', '532', '540', '541', '600', '610', '611',
       '612', '613', '620', '621', '622', '630', '631', '632', '633',
       '634', '700', '710', '711', '712', '713', '720', '721', '722',
       '723', '730', '731', '732', '740', '741', '742', '750', '751',
       '752', '753', '754', '800', '810', '811', '812', '813', '814',
       '815', '816', '817', '818', '820', '821', '830', '831', '832',
       '833', '834', '835', '900', '910', '911', '912', '920', '921',
       '930', '931', '932', '933', '940', '941', '950', '951', '952',
       '960', '961', '962'], dtype=object)

In [159]:
np.unique(df.ISCO.str.len(), return_counts=True)

(array([1, 2, 3], dtype=int64),
 array([   9216,  111967, 1425386], dtype=int64))

In [160]:
df.loc[df.ISCO != df.ISCO3D, :].COUNTRY.unique()

['BG', 'MT', 'PL']
Categories (30, object): ['AT', 'BE', 'BG', 'CH', ..., 'RO', 'SE', 'SK', 'UK']

In [154]:
df.ISCO.sort_values()

1079249      0
1085924      0
1079677      0
1085967      0
1086792      0
          ...
890975     962
890985     962
1244683    962
889573     962
766682     962
Name: ISCO, Length: 1546569, dtype: object

In [150]:
(
    df.isco_label_1.notna().sum()
    + df.isco_label_2.notna().sum()
    + df.isco_label_3.notna().sum()
)

1533260

Aggregate

In [141]:
agg_dict = {"COEFF": np.sum, "COEFF_share_green_esco_mean": np.sum}

lfs.aggregate(year=2019, group_by=["NACE1D_label", "COUNTRYW"], agg_dict=agg_dict)

,NACE1D_label,COUNTRYW,COEFF,COEFF_share_green_esco_mean,COEFF_rel,COEFF_share_green_esco_mean_rel
0,Accommodation and Food Service Activities,AT,2.631255e+05,8920.107490,1.0,0.033901
1,Accommodation and Food Service Activities,BE,1.801191e+05,7248.596563,1.0,0.040243
2,Accommodation and Food Service Activities,BG,1.773203e+05,7299.937000,1.0,0.041168
3,Accommodation and Food Service Activities,CH,1.869531e+05,6649.787931,1.0,0.035569
4,Accommodation and Food Service Activities,CY,3.765403e+04,1216.622527,1.0,0.032311
...,...,...,...,...,...,...
625,Wholesale and Retail Trade; Repair of Motor Ve...,PT,6.971531e+05,15083.519315,1.0,0.021636
626,Wholesale and Retail Trade; Repair of Motor Ve...,RO,1.266177e+06,21630.960178,1.0,0.017084
627,Wholesale and Retail Trade; Repair of Motor Ve...,SE,5.691850e+05,14572.831752,1.0,0.025603
628,Wholesale and Retail Trade; Repair of Motor Ve...,SK,2.998393e+05,5396.260601,1.0,0.017997
629,Wholesale and Retail Trade; Repair of Motor Ve...,UK,4.046911e+06,86373.174158,1.0,0.021343

In [142]:
lfs.aggregate(year=2019, group_by="NACE1D_label", agg_dict=agg_dict)

,NACE1D_label,COEFF,COEFF_share_green_esco_mean,COEFF_rel,COEFF_share_green_esco_mean_rel
0,Accommodation and Food Service Activities,1.133915e+07,3.947692e+05,1.0,0.034815
1,Activities of Extraterritorial Organisations a...,1.958302e+05,4.102416e+03,1.0,0.020949
2,Activities of Households as Employers; Undiffe...,2.270725e+06,1.000355e+05,1.0,0.044054
3,Administrative and Support Service Activities,1.005101e+07,6.057680e+05,1.0,0.060269
4,"Agriculture, Forestry and Fishing",8.861904e+06,1.856829e+06,1.0,0.209529
5,"Arts, Entertainment and Recreation",4.228681e+06,1.176472e+05,1.0,0.027821
6,Construction,1.589664e+07,1.041165e+06,1.0,0.065496
7,Education,1.813708e+07,2.650332e+05,1.0,0.014613
8,"Electricity, Gas, Steam and Air Conditioning S...",1.602330e+06,8.446993e+04,1.0,0.052717
9,Financial and Insurance Activities,6.722941e+06,9.991007e+04,1.0,0.014861
10,Human Health and Social Work Activities,2.679404e+07,5.234028e+05,1.0,0.019534
11,Information and Communication,7.637331e+06,1.090513e+05,1.0,0.014279
12,Manufacturing,3.529264e+07,1.401436e+06,1.0,0.039709
13,Mining and Quarrying,7.601937e+05,3.496540e+04,1.0,0.045995
14,Other Service Activities,5.858696e+06,1.450607e+05,1.0,0.024760
15,"Professional, Scientific and Technical Activities",1.370367e+07,5.012698e+05,1.0,0.036579
16,Public Administration and Defence; Compulsory ...,1.587381e+07,4.899162e+05,1.0,0.030863
17,Real Estate Activities,1.964545e+06,5.886053e+04,1.0,0.029961
18,Transportation and Storage,1.229472e+07,4.400490e+05,1.0,0.035792
19,"Water Supply; Sewerage, Waste Management and R...",1.837414e+06,2.339442e+05,1.0,0.127323
20,Wholesale and Retail Trade; Repair of Motor Ve...,3.191768e+07,6.638221e+05,1.0,0.020798

LM Classifications

In [119]:
clsf.nace

,Order,Level,Code,Parent,Description,This item includes,This item also includes,Rulings,This item excludes,Reference to ISIC Rev. 4
0,398481,1,A,NaN,"AGRICULTURE, FORESTRY AND FISHING",This section includes the exploitation of vege...,NaN,NaN,NaN,A
1,398482,2,1,A,"Crop and animal production, hunting and relate...","This division includes two basic activities, n...",This division also includes service activities...,NaN,Agricultural activities exclude any subsequent...,1
2,398483,3,1.1,1,Growing of non-perennial crops,This group includes the growing of non-perenni...,NaN,NaN,NaN,11
3,398484,4,1.11,1.1,"Growing of cereals (except rice), leguminous c...",This class includes all forms of growing of ce...,NaN,NaN,"This class excludes:\n- growing of rice, see 0...",111
4,398485,4,1.12,1.1,Growing of rice,This class includes:\n- growing of rice (inclu...,NaN,NaN,NaN,112
...,...,...,...,...,...,...,...,...,...,...
991,399472,4,98.2,98.2,Undifferentiated service-producing activities ...,This class includes the undifferentiated subsi...,NaN,NaN,NaN,9820
992,399473,1,U,NaN,ACTIVITIES OF EXTRATERRITORIAL ORGANISATIONS A...,NaN,NaN,NaN,NaN,U
993,399474,2,99,U,Activities of extraterritorial organisations a...,NaN,NaN,NaN,NaN,99
994,399475,3,99,99,Activities of extraterritorial organisations a...,NaN,NaN,NaN,NaN,990
995,399476,4,99,99,Activities of extraterritorial organisations a...,This class includes:\n- activities of internat...,This class also includes:\n- activities of dip...,NaN,NaN,9900

In [230]:
clsf.nace_1d

   NACE1D                                       NACE1D_label
0       A                  Agriculture, Forestry and Fishing
1       B                               Mining and Quarrying
2       C                                      Manufacturing
3       D  Electricity, Gas, Steam and Air Conditioning S...
4       E  Water Supply; Sewerage, Waste Management and R...
5       F                                       Construction
6       G  Wholesale and Retail Trade; Repair of Motor Ve...
7       H                         Transportation and Storage
8       I          Accommodation and Food Service Activities
9       J                      Information and Communication
10      K                 Financial and Insurance Activities
11      L                             Real Estate Activities
12      M  Professional, Scientific and Technical Activities
13      N      Administrative and Support Service Activities
14      O  Public Administration and Defence; Compulsory ...
15      P                                          Education
16      Q            Human Health and Social Work Activities
17      R                 Arts, Entertainment and Recreation
18      S                           Other Service Activities
19      T  Activities of Households as Employers; Undiffe...
20      U  Activities of Extraterritorial Organisations a...

In [118]:
clsf.read_nace_at_level(2)

,Order,Level,Code,Parent,Description,This item includes,This item also includes,Rulings,This item excludes,Reference to ISIC Rev. 4
1,398482,2,1,A,"Crop and animal production, hunting and relate...","This division includes two basic activities, n...",This division also includes service activities...,NaN,Agricultural activities exclude any subsequent...,1
40,398521,2,2,A,Forestry and logging,This division includes the production of round...,NaN,NaN,Excluded is further processing of wood beginni...,2
49,398530,2,3,A,Fishing and aquaculture,This division includes capture fishery and aqu...,Also included are activities that are normally...,NaN,This division does not include building and re...,3
57,398538,2,5,B,Mining of coal and lignite,This division includes the extraction of solid...,NaN,NaN,This division does not include coking (see 19....,5
62,398543,2,6,B,Extraction of crude petroleum and natural gas,This division includes the production of crude...,NaN,NaN,This division excludes:\n- oil and gas field s...,6
67,398548,2,7,B,Mining of metal ores,This division includes mining for metallic min...,This division also includes:\n- ore dressing a...,NaN,This division excludes:\n- roasting of iron py...,7
73,398554,2,8,B,Other mining and quarrying,This division includes extraction from a mine ...,NaN,NaN,This division does not include processing (exc...,8
82,398563,2,9,B,Mining support service activities,This division includes specialised support ser...,NaN,NaN,NaN,9
88,398569,2,10,C,Manufacture of food products,This division includes the processing of the p...,NaN,NaN,This division does not include the preparation...,10
123,398604,2,11,C,Manufacture of beverages,This division includes the manufacture of beve...,NaN,NaN,This division excludes:\n- production of fruit...,11
132,398613,2,12,C,Manufacture of tobacco products,This division includes the processing of an ag...,NaN,NaN,NaN,12
135,398616,2,13,C,Manufacture of textiles,This division includes preparation and spinnin...,NaN,NaN,NaN,13
150,398631,2,14,C,Manufacture of wearing apparel,This division includes all tailoring (ready-to...,Division 14 also includes the fur industry (fu...,NaN,NaN,14
162,398643,2,15,C,Manufacture of leather and related products,This division includes dressing and dyeing of ...,It also includes the manufacture of similar pr...,NaN,NaN,15
168,398649,2,16,C,Manufacture of wood and of products of wood an...,This division includes the manufacture of wood...,NaN,NaN,This division does not include the manufacture...,16
177,398658,2,17,C,Manufacture of paper and paper products,This division includes the manufacture of pulp...,NaN,NaN,NaN,17
187,398668,2,18,C,Printing and reproduction of recorded media,"This division includes printing of products, s...",This division also includes the reproduction o...,NaN,This division excludes publishing activities (...,18
195,398676,2,19,C,Manufacture of coke and refined petroleum prod...,This division includes the transformation of c...,This division also includes the manufacture fo...,NaN,Not included is the manufacture of such gases ...,19
200,398681,2,20,C,Manufacture of chemicals and chemical products,This division includes the transformation of o...,NaN,NaN,NaN,20
223,398704,2,21,C,Manufacture of basic pharmaceutical products a...,This division includes the manufacture of basi...,This also includes the manufacture of medicina...,NaN,NaN,21
228,398709,2,22,C,Manufacture of rubber and plastic products,This division includes the manufacture of rubb...,NaN,NaN,NaN,22
237,398718,2,23,C,Manufacture of other non-metallic mineral prod...,This division includes manufacturing activitie...,The manufacture of shaped and finished stone a...,NaN,NaN,23
270,398751,2,24,C,Manufacture of basic metals,This division includes the activities of smelt...,This division also includes the manufacture of...,NaN,NaN,24
292,398773,2,25,C,"Manufacture of fabricated metal products, exce...","This division includes the manufacture of ""pur...",The manufacture of weapons and ammunition is a...,NaN,This division excludes:\n- specialised repair ...,25
318,398799,2,26,C,"Manufacture of computer, electronic and optica...",This division includes the manufacture of comp...,The division also contains the manufacture of ...,NaN,NaN,26
337,398818,2,27,C,Manufacture of electrical equipment,This division includes the manufacture of prod...,Also included is the manufacture of electrical...,NaN,This division excludes the manufacture of elec...,27
354,398835,2,28,C,Manufacture of machinery and equipment n.e.c.,This division includes the manufacture of mach...,This division also includes the manufacture of...,NaN,This division excludes the manufacture of meta...,28
381,398862,2,29,C,"Manufacture of motor vehicles, trailers and se...",This division includes the manufacture of moto...,NaN,NaN,NaN,29
389,398870,2,30,C,Manufacture of other transport equipment,This division includes the manufacture of tran...,NaN,NaN,NaN,30
403,398884,2,31,C,Manufacture of furniture,This division includes the manufacture of furn...,NaN,NaN,NaN,31
409,398890,2,32,C,Other manufacturing,This division includes the manufacture of a va...,NaN,NaN,NaN,32
425,398906,2,33,C,Repair and installation of machinery and equip...,This division includes the specialised repair ...,Also included in this division is the speciali...,NaN,This division excludes:\n- cleaning of industr...,33
438,398919,2,35,D,"Electricity, gas, steam and air conditioning s...",NaN,NaN,NaN,NaN,35
451,398932,2,36,E,"Water collection, treatment and supply","This division includes the collection, treatme...",NaN,NaN,NaN,36
454,398935,2,37,E,Sewerage,This division includes the operation of sewer ...,NaN,NaN,NaN,37
457,398938,2,38,E,"Waste collection, treatment and disposal activ...","This division includes the collection, treatme...",This also includes local hauling of waste mate...,NaN,NaN,38
467,398948,2,39,E,Remediation activities and other waste managem...,This division includes the provision of remedi...,NaN,NaN,NaN,39
471,398952,2,41,F,Construction of buildings,This division includes general construction of...,NaN,NaN,NaN,41
476,398957,2,42,F,Civil engineering,This division includes general construction fo...,NaN,NaN,NaN,42
487,398968,2,43,F,Specialised construction activities,This division includes specialised constructio...,Also included are building finishing and build...,NaN,NaN,43
506,398987,2,45,G,Wholesale and retail trade and repair of motor...,This division includes all activities (except ...,This division also includes activities such as...,NaN,This division does not include the retail sale...,45
517,398998,2,46,G,"Wholesale trade, except of motor vehicles and ...",This division includes wholesale trade on own ...,NaN,NaN,This division excludes:\n- wholesale of motor ...,46
574,399055,2,47,G,"Retail trade, except of motor vehicles and mot...",This division includes the resale (sale withou...,This division also includes units engaged prim...,NaN,This division excludes:\n- sale of farmers' pr...,47
622,399103,2,49,H,Land transport and transport via pipelines,This division includes the transport of passen...,NaN,NaN,NaN,49
636,399117,2,50,H,Water transport,This division includes the transport of passen...,NaN,NaN,This division excludes restaurant and bar acti...,50
645,399126,2,51,H,Air transport,This division includes the transport of passen...,NaN,NaN,"This division excludes:\n- crop spraying, see ...",51
651,399132,2,52,H,Warehousing and support activities for transpo...,This division includes warehousing and support...,NaN,NaN,NaN,52
660,399141,2,53,H,Postal and courier activities,This division includes postal and courier acti...,Local delivery and messenger services are also...,NaN,NaN,53
666,399147,2,55,I,Accommodation,This division includes the provision of short-...,Also included is the provision of longer term ...,NaN,This division excludes activities related to t...,55
675,399156,2,56,I,Food and beverage service activities,This division includes food and beverage servi...,NaN,NaN,Excluded is the production of meals not fit fo...,56
684,399165,2,58,J,Publishing activities,This division includes the publishing of books...,NaN,NaN,This division excludes the publishing of motio...,58
694,399175,2,59,J,"Motion picture, video and television programme...",This division includes production of theatrica...,This division also includes the sound recordin...,NaN,NaN,59
702,399183,2,60,J,Programming and broadcasting activities,This division includes the activities of creat...,This division also includes the production of ...,NaN,This division excludes the distribution of cab...,60
707,399188,2,61,J,Telecommunications,This division includes the activities of provi...,NaN,NaN,NaN,61
716,399197,2,62,J,"Computer programming, consultancy and related ...",This division includes the following activitie...,NaN,NaN,NaN,62
722,399203,2,63,J,Information service activities,This division includes the activities of web s...,NaN,NaN,NaN,63
730,399211,2,64,K,"Financial service activities, except insurance...",This division includes the activities of obtai...,NaN,NaN,NaN,64
742,399223,2,65,K,"Insurance, reinsurance and pension funding, ex...",This division includes the underwriting annuit...,NaN,NaN,NaN,65
750,399231,2,66,K,Activities auxiliary to financial services and...,This division includes the provision of servic...,NaN,NaN,NaN,66
762,399243,2,68,L,Real estate activities,NaN,NaN,NaN,NaN,68
771,399252,2,69,M,Legal and accounting activities,This division includes legal representation of...,It also includes preparation of legal document...,NaN,NaN,69
776,399257,2,70,M,Activities of head offices; management consult...,This division includes the provision of advice...,It also includes the overseeing and managing o...,NaN,NaN,70
782,399263,2,71,M,Architectural and engineering activities; tech...,This division includes the provision of archit...,"It also includes the performance of physical, ...",NaN,NaN,71
788,399269,2,72,M,Scientific research and development,This division includes the activities of three...,NaN,NaN,"This division excludes:\n- market research, se...",72
794,399275,2,73,M,Advertising and market research,This division includes the creation of adverti...,NaN,NaN,NaN,73
800,399281,2,74,M,"Other professional, scientific and technical a...",This division includes the provision of profes...,NaN,NaN,NaN,74
809,399290,2,75,M,Veterinary activities,This division includes the provision of animal...,It also includes animal ambulance activities.,NaN,NaN,75
813,399294,2,77,N,Rental and leasing activities,This division includes the rental and leasing ...,NaN,NaN,"This division excludes:\n- financial leasing, ...",77
830,399311,2,78,N,Employment activities,This division includes activities of listing e...,NaN,NaN,This division excludes:\n- activities of agent...,78
837,399318,2,79,N,"Travel agency, tour operator and other reserva...",This division includes the activity of agencie...,The activities of tourist guides and tourism p...,NaN,NaN,79
843,399324,2,80,N,Security and investigation activities,This division includes security-related servic...,NaN,NaN,NaN,80
850,399331,2,81,N,Services to buildings and landscape activities,This division includes the provision of a numb...,NaN,NaN,NaN,81
859,399340,2,82,N,"Office administrative, office support and othe...",This division includes the provision of a rang...,This division also includes all support servic...,NaN,Units classified in this division do not provi...,82
872,399353,2,84,O,Public administration and defence; compulsory ...,NaN,NaN,NaN,NaN,84
886,399367,2,85,P,Education,NaN,NaN,NaN,NaN,85
905,399386,2,86,Q,Human health activities,This division includes activities of short- or...,It also includes medical consultation and trea...,NaN,NaN,86
914,399395,2,87,Q,Residential care activities,This division includes the provision of reside...,NaN,NaN,NaN,87
923,399404,2,88,Q,Social work activities without accommodation,This division includes the provision of a vari...,NaN,NaN,NaN,88
930,399411,2,90,R,"Creative, arts and entertainment activities",This division includes the operation of facili...,NaN,NaN,This division excludes:\n- the operation of mu...,90
936,399417,2,91,R,"Libraries, archives, museums and other cultura...",This division includes the activities of libra...,It also includes the preservation and exhibiti...,NaN,This division excludes:\n- sports and amusemen...,91
942,399423,2,92,R,Gambling and betting activities,This division includes the operation of gambli...,NaN,NaN,NaN,92
945,399426,2,93,R,Sports activities and amusement and recreation...,This division includes the provision of recrea...,NaN,NaN,"Excluded from this division are dramatic arts,...",93
955,399436,2,94,S,Activities of membership organisations,This division includes activities of organisat...,NaN,NaN,NaN,94
965,399446,2,95,S,Repair of computers and personal and household...,This division includes the repair and maintena...,It also includes the repair of communications ...,NaN,Excluded from this division is the repair of m...,95
976,399457,2,96,S,Other personal service activities,This division includes all service activities ...,NaN,NaN,NaN,96
984,399465,2,97,T,Activities of households as employers of domes...,NaN,NaN,NaN,NaN,97
987,399468,2,98,T,Undifferentiated goods- and services-producing...,This division includes the undifferentiated su...,NaN,NaN,NaN,98
993,399474,2,99,U,Activities of extraterritorial organisations a...,NaN,NaN,NaN,NaN,99

In [126]:
clsf.nuts_4326

,NUTS_ID,LEVL_CODE,CNTR_CODE,NAME_LATN,NUTS_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,FID,geometry
0,BG,0,BG,Bulgaria,България,0.0,NaN,0,BG,"POLYGON ((22.99717 43.80787, 23.05372 43.79691..."
1,CH,0,CH,Schweiz/Suisse/Svizzera,Schweiz/Suisse/Svizzera,0.0,NaN,0,CH,"POLYGON ((8.61383 47.80108, 8.62791 47.76184, ..."
2,AL,0,AL,Shqipëria,Shqipëria,0.0,NaN,0,AL,"MULTIPOLYGON (((19.83100 42.46645, 19.84072 42..."
3,CZ,0,CZ,Česko,Česko,0.0,NaN,0,CZ,"POLYGON ((14.49122 51.04353, 14.50443 51.04093..."
4,BE,0,BE,Belgique/België,Belgique/België,0.0,NaN,0,BE,"MULTIPOLYGON (((5.10218 51.42900, 5.07104 51.3..."
...,...,...,...,...,...,...,...,...,...,...
2005,PL721,3,PL,Kielecki,Kielecki,4.0,2.0,3,PL721,"POLYGON ((20.43282 51.33940, 20.50927 51.32735..."
2006,PL722,3,PL,Sandomiersko-jędrzejowski,Sandomiersko-jędrzejowski,4.0,3.0,3,PL722,"POLYGON ((21.80300 51.07208, 21.82085 51.05049..."
2007,PL811,3,PL,Bialski,Bialski,4.0,3.0,3,PL811,"POLYGON ((23.12841 52.28784, 23.17834 52.28314..."
2008,UKN09,3,UK,Ards and North Down,Ards and North Down,4.0,1.0,1,UKN09,"MULTIPOLYGON (((-5.82347 54.49541, -5.83085 54..."
2009,UKN0A,3,UK,Derry City and Strabane,Derry City and Strabane,4.0,2.0,1,UKN0A,"POLYGON ((-7.14907 55.04338, -7.15718 55.03004..."

In [128]:
clsf.isco

,conceptType,conceptUri,code,preferredLabel,status,altLabels,inScheme,description
0,ISCOGroup,http://data.europa.eu/esco/isco/C0,0,Armed forces occupations,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Armed forces occupations include all jobs held...
1,ISCOGroup,http://data.europa.eu/esco/isco/C01,01,Commissioned armed forces officers,released,NaN,http://data.europa.eu/esco/concept-scheme/isco...,Commissioned armed forces officers provide lea...
2,ISCOGroup,http://data.europa.eu/esco/isco/C011,011,Commissioned armed forces officers,released,NaN,http://data.europa.eu/esco/concept-scheme/isco...,Commissioned armed forces officers provide lea...
3,ISCOGroup,http://data.europa.eu/esco/isco/C0110,0110,Commissioned armed forces officers,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Commissioned armed forces officers provide lea...
4,ISCOGroup,http://data.europa.eu/esco/isco/C02,02,Non-commissioned armed forces officers,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Non-commissioned armed forces officers enforce...
...,...,...,...,...,...,...,...,...
614,ISCOGroup,http://data.europa.eu/esco/isco/C9621,9621,"Messengers, package deliverers and luggage por...",released,NaN,http://data.europa.eu/esco/concept-scheme/isco...,"Messengers, package deliverers and luggage por..."
615,ISCOGroup,http://data.europa.eu/esco/isco/C9622,9622,Odd job persons,released,NaN,http://data.europa.eu/esco/concept-scheme/isco...,"Odd-job persons clean, paint and maintain buil..."
616,ISCOGroup,http://data.europa.eu/esco/isco/C9623,9623,Meter readers and vending-machine collectors,released,NaN,http://data.europa.eu/esco/concept-scheme/isco...,Meter readers and vending-machine collectors s...
617,ISCOGroup,http://data.europa.eu/esco/isco/C9624,9624,Water and firewood collectors,released,NaN,http://data.europa.eu/esco/concept-scheme/isco...,Water and firewood collectors collect water an...
618,ISCOGroup,http://data.europa.eu/esco/isco/C9629,9629,Elementary workers not elsewhere classified,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,This unit group covers elementary workers not ...

Visualise aggregated EU-LFS data

In [229]:
from src.visualization.visualize import eulfs_maps

eulfs_maps(year=2019)

     NUTS_ID                                       NACE1D_label        COEFF  \
0       AT11          Accommodation and Food Service Activities    5687.3950
1       AT11  Activities of Households as Employers; Undiffe...     301.3750
2       AT11      Administrative and Support Service Activities    2040.1375
3       AT11                  Agriculture, Forestry and Fishing    5270.3500
4       AT11                 Arts, Entertainment and Recreation    2015.3400
...      ...                                                ...          ...
4494     UKN  Public Administration and Defence; Compulsory ...   70340.0600
4495     UKN                             Real Estate Activities    6116.0800
4496     UKN                         Transportation and Storage   35783.6600
4497     UKN  Water Supply; Sewerage, Waste Management and R...    2942.3000
4498     UKN  Wholesale and Retail Trade; Repair of Motor Ve...  114194.6300

      COEFF_share_green_esco_mean  COEFF_share_brown_esco_mean  \
0                      236.518961                    36.693470
1                        7.248070                     1.606323
2                      211.252075                     8.716575
3                     1430.797258                    22.129799
4                       51.591237                     6.284672
...                           ...                          ...
4494                  2445.284222                   334.807109
4495                    93.039125                    25.191250
4496                  1014.105198                   455.491808
4497                   439.107404                    46.796238
4498                  2460.184357                   835.198854

      COEFF_share_neutral_esco_mean  COEFF_share_green_gtp_mean  \
0                       5414.182569                  232.550694
1                        292.520607                    0.000000
2                       1820.168850                  234.428523
3                       3817.422943                 1079.843488
4                       1957.464091                   47.519498
...                             ...                         ...
4494                   67559.968669                 8417.743105
4495                    5997.849626                  475.003409
4496                   34314.062994                 3695.642751
4497                    2456.396359                 1032.286340
4498                  110899.246790                12704.492467

      COEFF_share_green_gilli2020  COEFF_rel  COEFF_share_green_esco_mean_rel  \
0                       37.292273        1.0                         0.041587
1                        0.000000        1.0                         0.024050
2                       12.069230        1.0                         0.103548
3                       36.259220        1.0                         0.271481
4                       21.516300        1.0                         0.025599
...                           ...        ...                              ...
4494                  1790.371020        1.0                         0.034764
4495                   183.848710        1.0                         0.015212
4496                  1098.383800        1.0                         0.028340
4497                   624.814490        1.0                         0.149240
4498                  3114.694380        1.0                         0.021544

      COEFF_share_brown_esco_mean_rel  COEFF_share_neutral_esco_mean_rel  \
0                            0.006452                           0.951962
1                            0.005330                           0.970620
2                            0.004273                           0.892179
3                            0.004199                           0.724321
4                            0.003118                           0.971282
...                               ...                                ...
4494                         0.004760                           0.960476
4495                         0.004119                           0.980669
4496                         0.012729                           0.958931
4497                         0.015905                           0.834856
4498                         0.007314                           0.971142

      COEFF_share_green_gtp_mean_rel  COEFF_share_green_gilli2020_rel
0                           0.040889                         0.006557
1                           0.000000                         0.000000
2                           0.114908                         0.005916
3                           0.204890                         0.006880
4                           0.023579                         0.010676
...                              ...                              ...
4494                        0.119672                         0.025453
4495                        0.077665                         0.030060
4496                        0.103277                         0.030695
4497                        0.350843                         0.212356
4498                        0.111253                         0.027275

[4499 rows x 14 columns]