# Checks & Debugs regarding refactoring of code
Felix Zaussinger | XX.YY.ZZZZ

In [1]:
import os
import sys
import logging
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from src import utils
import mapping_career_causeways

# OPTIONAL: Load the "autoreload" extension so that code can change
%load_ext autoreload

# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2

# Settings
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

sns.set_context("poster")
sns.set(rc={'figure.figsize': (16, 9.)})
sns.set_style("ticks")

pd.set_option("display.max_rows", 120)
pd.set_option("display.max_columns", 120)

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

# load paths
useful_paths = utils.UsefulPaths(fn_config_path="paths_config.yml")

In [14]:
from src.data.framework import Esco, Onet
esco = Esco()
onet = Onet()

ESCO Class

In [18]:
esco.occupations
esco.skills

,conceptType,conceptUri,skillType,reuseLevel,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,scopeNote,definition,inScheme,description
0,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0005c151-5b5a...,skill/competence,sector-specific,manage musical staff,manage staff of music\ncoordinate duties of mu...,NaN,released,2016-12-20T17:43:43Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Assign and manage staff tasks in areas such as...
1,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00064735-8fad...,skill/competence,occupation-specific,supervise correctional procedures,oversee prison procedures\nmanage correctional...,NaN,released,2016-12-20T20:17:49Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Supervise the operations of a correctional fac...
2,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/000709ed-2be5...,skill/competence,sector-specific,apply anti-oppressive practices,apply non-oppressive practices\napply an anti-...,NaN,released,2016-12-20T19:18:19Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Identify oppression in societies, economies, c..."
3,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0007bdc2-dd15...,skill/competence,sector-specific,control compliance of railway vehicles regulat...,monitoring of compliance with railway vehicles...,NaN,released,2016-12-20T20:02:19Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Inspect rolling stock, components and systems ..."
4,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00090cc1-1f27...,skill/competence,cross-sector,identify available services,establish available services\ndetermine rehabi...,NaN,released,2016-12-20T20:15:17Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Identify the different services available for ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13886,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/ffef5eb3-a15e...,skill/competence,sector-specific,remediate healthcare user's occupational perfo...,restore healthcare user's occupational perform...,NaN,released,2016-12-20T19:25:53Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,"Remediate or restore the cognitive, sensorimot..."
13887,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff0b074-5a76...,skill/competence,sector-specific,install transport equipment lighting,install transport equipment illumination\nfix ...,NaN,released,2016-12-20T20:03:21Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Install lighting elements in transport equipme...
13888,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff0e2cd-d0bd...,knowledge,sector-specific,natural language processing,NLP,NaN,released,2016-08-04T15:19:37Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,The technologies which enable ICT devices to u...
13889,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff5bc45-b506...,skill/competence,cross-sector,coordinate construction activities,reviewing construction progress\nconstruction ...,NaN,released,2016-12-20T18:22:35Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Coordinate the activities of several construct...
13890,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff74a70-4f82...,skill/competence,cross-sector,position guardrails and toeboards,positioning guardrails and toeboards\nattachme...,NaN,released,2016-12-20T18:24:23Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Attach guardrails and toeboards to the scaffol...

Onet Class

In [3]:
onet.green_occupations_gtp
onet.green_occupations_vona2018
onet.green_tasks_gtp
onet.brown_occupations_vona2018
onet.green_occupations_narrow_jrc

,isco08_jrc,occ_eng_jrc,n_green_tasks_jrc,n_tasks_jrc,greenness_jrc
0,1.1.2.4.3,General managers and equivalent in health care,1,11.0,0.090909
1,1.1.2.6.3,Managers and equivalent in health care,1,13.0,0.076923
2,1.2.2.3.0,Directors and general managers of construction...,1,13.0,0.076923
3,1.2.3.2.0,"Directors and managers of the organisation, hu...",1,15.0,0.066667
4,1.2.3.7.0,Directors and managers of the research and dev...,1,12.0,0.083333
5,1.2.3.9.0,Other departmental directors and managers,1,10.0,0.100000
6,1.3.1.2.0,Entrepreneurs and managers of small companies ...,1,14.0,0.071429
7,1.3.1.3.0,Entrepreneurs and managers of small constructi...,1,14.0,0.071429
8,1.3.1.8.0,Entrepreneurs and managers of small companies ...,1,13.0,0.076923
9,2.1.1.2.1,Chemists and related professions,1,14.0,0.071429
10,2.1.1.6.1,Geologists,2,12.0,0.166667
11,2.1.1.6.4,Meteorologists,1,10.0,0.100000
12,2.2.1.1.4,Energy and nuclear engineers,3,14.0,0.214286
13,2.2.1.2.2,Mining engineers,1,13.0,0.076923
14,2.2.1.5.1,Chemical and petroleum engineers,1,11.0,0.090909
15,2.2.1.6.1,Building and environmental engineers,1,9.0,0.111111
16,2.2.1.6.2,Hydraulic engineers,1,12.0,0.083333
17,2.2.1.7.0,Industrial and management engineers,1,13.0,0.076923
18,2.2.2.1.2,"Planners, landscape architects and land recove...",3,10.0,0.300000
19,2.3.1.1.5,Botanicals,1,12.0,0.083333
20,2.3.1.1.7,Ecologists,2,11.0,0.181818
21,2.3.1.3.0,Agronomists and foresters,1,11.0,0.090909
22,2.4.1.7.2,Specialists in social and occupational medicine,1,13.0,0.076923
23,2.5.3.2.3,Geographers,2,10.0,0.200000
24,3.1.1.1.1,Geological technicians,1,9.0,0.111111
25,3.1.1.1.2,Physical and nuclear engineers,1,8.0,0.125000
26,3.1.3.2.1,Ceramic product technicians,1,7.0,0.142857
27,3.1.3.4.0,Electronic technicians,1,13.0,0.076923
28,3.1.3.6.0,Energy saving and renewable energy technicians,2,7.0,0.285714
29,3.1.4.1.1,Operating and control technicians for metal pr...,1,7.0,0.142857
30,3.1.4.1.2,Chemical plant management and control technicians,1,9.0,0.111111
31,3.1.4.1.3,Operating and control technicians for paper pr...,1,9.0,0.111111
32,3.1.4.1.4,Water treatment plant operation and control te...,1,13.0,0.076923
33,3.1.4.1.5,Operating and control technicians for automati...,1,8.0,0.125000
34,3.1.4.2.1,Thermal and electrical energy production techn...,2,15.0,0.133333
35,3.1.4.2.2,Water and other fluids operation technicians,1,10.0,0.100000
36,3.1.4.2.3,Electricity distribution network operation tec...,2,15.0,0.133333
37,3.1.5.1.0,Production technicians in mines and quarries,1,11.0,0.090909
38,3.1.5.2.0,Construction site management technicians,1,9.0,0.111111
39,3.1.5.3.0,Manufacturing production technicians,2,15.0,0.133333
40,3.1.5.4.1,Food preparation technicians,1,14.0,0.071429
41,3.1.5.4.2,Food production technicians,2,12.0,0.166667
42,3.1.6.1.1,Naval commanders,2,15.0,0.133333
43,3.1.6.1.2,Officers and stewards,1,13.0,0.076923
44,3.1.6.3.1,Flight controllers,2,10.0,0.200000
45,3.1.6.3.2,Airport traffic technicians,2,10.0,0.200000
46,3.1.8.3.1,Environmental control technicians,4,10.0,0.400000
47,3.1.8.3.2,"Waste collection, treatment and environmental ...",3,10.0,0.290000
48,3.2.1.5.1,Environmental and workplace prevention technic...,2,12.0,0.166667
49,3.2.2.1.2,Forestry technicians,5,10.0,0.500000
50,3.2.2.3.3,Veterinary laboratory technicians,1,15.0,0.066667
51,3.4.1.5.1,Nature and sports guides,1,12.0,0.083333
52,3.4.6.3.2,Fire brigade security service technicians,2,10.0,0.200000
53,3.4.6.3.3,Technicians of the security services of the Fo...,2,10.0,0.200000
54,5.1.1.3.0,Operators of fuel distributors and assimilates,1,12.0,0.083333
55,5.4.8.1.0,Territorial guarding staff,1,10.0,0.120000
56,5.4.8.3.3,Forestry officers,3,9.0,0.333333
57,6.1.1.3.0,Saline farmers,5,11.0,0.421488
58,6.1.3.5.0,Glassmakers,1,12.0,0.083333
59,6.1.3.6.2,Installers of thermal systems in civil constru...,2,11.0,0.181818
60,6.1.5.1.0,Cleaning and hygiene workers,2,11.0,0.181818
61,6.1.5.2.0,Sewerage maintenance workers,1,12.0,0.083333
62,6.2.1.6.0,Divers and underwater workers,1,14.0,0.071429
63,6.2.2.3.1,Machine tool operators,1,15.0,0.066667
64,6.2.2.3.2,Mechanical Adjusters,1,13.0,0.076923
65,6.2.4.1.3,Electromechanical,1,15.0,0.066667
66,6.2.4.1.4,Installers and repairers of electricity genera...,1,14.0,0.071429
67,6.2.4.4.0,Installers and repairers of telecommunications...,1,12.0,0.083333
68,6.2.4.5.0,"Installers, maintainers and repairers of power...",1,13.0,0.076923
69,6.3.1.1.0,Precision mechanics,1,15.0,0.066667
70,6.3.1.5.1,Production of lenses and spectacles,1,12.0,0.083333
71,6.3.1.5.2,Optical equipment production workers,1,13.0,0.076923
72,6.3.1.6.2,Workers in the processing of precious and hard...,1,14.0,0.071429
73,6.3.1.6.3,Jewellery workers,1,12.0,0.083333
74,6.3.2.1.1,Potters and terracotta makers,1,14.0,0.071429
75,6.3.2.1.2,Ceramists,1,14.0,0.071429
76,6.3.2.2.1,Glass blowers and moulders,1,13.0,0.076923
77,6.3.3.2.2,Artisans of handcrafted leather and hide products,1,13.0,0.076923
78,6.3.4.1.0,Operators of pre-press polygraphic activities,1,15.0,0.066667
79,6.3.4.4.2,"Lithographers, screen printers and typographic...",1,12.0,0.083333
80,6.4.2.6.0,Breeders and specialised workers on insect farms,1,13.0,0.076923
81,6.4.4.1.1,Tree fellers and reforesters,2,15.0,0.133333
82,6.4.5.1.0,Aquaculturists,1,13.0,0.076923
83,6.4.5.2.0,Coastal and inland fisheries fishermen,1,14.0,0.071429
84,6.4.5.3.0,Deep-sea fishermen,1,15.0,0.066667
85,6.5.1.1.2,Norcini,1,14.0,0.071429
86,6.5.1.1.3,Fishmongers,1,12.0,0.083333
87,6.5.1.2.2,Pastai,1,13.0,0.076923
88,6.5.1.3.2,Ice cream parlours,1,11.0,0.090909
89,6.5.1.3.3,Canning,1,13.0,0.076923
90,6.5.1.4.0,Food and drink tasters and classifiers,1,6.0,0.166667
91,6.5.1.6.0,Specialised workers in the preparation and pro...,1,10.0,0.100000
92,6.5.3.6.3,Cutters of upholstery and covers for armchairs...,1,9.0,0.111111
93,6.5.4.3.2,Leather cutters,1,14.0,0.071429
94,7.1.1.2.0,Plant operators for primary processing of ores...,1,8.0,0.125000
95,7.1.1.3.2,Conductors of exploration probes and drills,1,13.0,0.076923
96,7.1.2.1.1,Blast furnace operators,1,10.0,0.100000
97,7.1.2.4.2,Metal extrusion and forming machine operators,1,15.0,0.066667
98,7.1.3.1.0,"Plant operators for dosing, mixing and kneadin...",1,12.0,0.083333
99,7.1.5.2.0,Machinery and plant operators for basic and fi...,1,15.0,0.066667
100,7.1.5.3.2,Operators of machinery for the production of c...,1,13.0,0.076923
101,7.1.6.2.1,Operators of waste recovery and recycling faci...,3,10.0,0.300000
102,7.2.2.1.0,Metal finishers and plant operators for finish...,1,14.0,0.071429
103,7.2.3.3.0,Drivers of machinery for the manufacture of pl...,1,12.0,0.083333
104,7.2.6.4.0,"Machinery operators for dry cleaning, bleachin...",1,11.0,0.090909
105,7.2.6.5.0,Fabric printing machinery operators,1,13.0,0.076923
106,7.2.8.1.0,Workers on packaging machines and packaging of...,1,10.0,0.100000
107,7.3.2.8.3,Operators of industrial machinery for the prod...,1,15.0,0.066667
108,7.3.2.8.4,Industrial machinery operators for the product...,1,10.0,0.100000
109,7.4.1.2.0,"Train verification, circulation and training o...",1,12.0,0.083333
110,8.1.4.1.0,Unskilled cleaning staff in accommodation serv...,1,14.0,0.071429
111,8.1.4.2.0,Unskilled staff in catering services,1,12.0,0.083333
112,8.1.4.3.0,Unskilled office and commercial cleaning staff,1,11.0,0.090909
113,8.1.4.5.0,Ecological workers and other waste collectors ...,9,15.0,0.600000
114,8.1.6.1.1,Unskilled building security staff,1,13.0,0.076923
115,8.1.6.1.3,Unskilled staff working in the custody of equi...,1,12.0,0.083333
116,8.3.2.1.0,Unskilled forestry personnel,1,13.0,0.076923

Calculating occ-skills matrix with more flexibility

In [39]:
osm_weighted = esco.read_occ_skills_matrix(return_version="weighted")
np.unique(osm_weighted)

array([0. , 0.5, 1. ])

In [40]:
osm_unweighted = esco.read_occ_skills_matrix(return_version="unweighted", assign_labels=True)
np.unique(osm_unweighted)

array([0, 1], dtype=int64)

In [42]:
osm_encoded = esco.read_occ_skills_matrix(return_version="raw", assign_labels=True)
np.unique(osm_encoded)

array([0, 1, 2], dtype=int64)

In [22]:
osm_weighted = esco.label_osm(osm_weighted)
osm_weighted

,manage musical staff,supervise correctional procedures,apply anti-oppressive practices,control compliance of railway vehicles regulations,identify available services,perform toxicological studies,ensure coquille uniformity,Haskell,show initiative,train staff to reduce food waste,apply diplomatic principles,lead police investigations,handle fish harvesting waste,develop energy saving concepts,perform street interventions in social work,work with soloists,sport and exercise medicine,conduct research on flora,install heat pump,design biomass installations,handle equipment while suspended,teach housekeeping skills,check train engines,influence public policies,enterprise risk management,manufacture ingredients,maintain aquaculture ponds,apply credit risk policy,handle customer requests related to cargo,draft scientific or academic papers and technical documentation,Incremental development,use of special equipment for daily activities,sawing techniques,produce guitar components,operate agricultural machinery,control pyrotechnics stock,guarantee customer satisfaction,manufacture wearing apparel products,cure tobacco leaves,develop a rehabilitation programme,maintain inventory of cleaning supplies,cold vulcanisation,supervise housekeeping operations,act as contact person during equipment incident,manage time in landscaping,advise on customs regulations,manage university department,develop terminology databases,assess nutritional characteristics of food,repair electric bicycles,maintain sorting equipment,explain features in accommodation venue,types of barley,KDevelop,purchase vehicle parts,inspect offshore constructions,transport patient to medical facility,adjust envelope cutting settings,prepare oils,purchase supplies,...,establish gaming policies,media and information literacy,evaluate clinical outcomes of dental hygiene interventions,gem cutting forms,cut pig's teeth,provide therapy of the visual system,administer materials to tea bag machines,advise on bank account,manage dental emergencies,assume highest level of responsibility in inland water transportation,manage time in food processing operations,student financial aid programmes,interpret pedigree charts,perform software recovery testing,astronomy,use instruments for food measurement,tend ball mill,understand spoken Norwegian,cut filament,procure time sheet approval,communicate with a non-scientific audience,prepare soda-ash,microchip scanners,rope lashing,create social alliances,assess your competencies in leading community arts,write Occitan,arrange customs inspection,perform nutrition analysis,analyse work-related written reports,surveillance methods,remove old caulking,keep company,clean patients' ear canals,anodising process,preserve samples,treat vehicle fabrics,collect domestic waste,perform energy simulations,match vessels to shipping routes,types of drill bits,cable-propelled transit,negotiate rights of use,Capture One,precious metal processing,control train movement,dependency on drugs,organise vehicle parts storage,set up reinforcing steel,model sensor,Scala,operate forestry equipment,test soil load bearing capacity,buy new library items,design clocks,remediate healthcare user's occupational performance,install transport equipment lighting,natural language processing,coordinate construction activities,position guardrails and toeboards
technical director,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
metal drawing machine operator,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.5,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
precision device inspector,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
air traffic safety technician,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
hospitality revenue manager,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
demographer,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,1.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
sorter labourer,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
armoured car guard,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.5,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
civil service administrative officer,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0
motor vehicle assembler,0.0,0,0,0.0,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,...,0.0,0.0,0,0,0.0,0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0

In [27]:
osm_weighted[osm_weighted == 1].sum(axis=1).describe()

count    3008.000000
mean       21.640957
std        12.145173
min         0.000000
25%        14.000000
50%        19.000000
75%        26.000000
max       133.000000
dtype: float64

In [28]:
osm_weighted[osm_weighted == 0.5].sum(axis=1).describe()

count    3008.000000
mean        9.766622
std        10.787132
min         0.000000
25%         4.500000
50%         8.500000
75%        11.500000
max       159.500000
dtype: float64

In [30]:
osm_unweighted[osm_unweighted == 1].sum(axis=1).describe()

count    3008.000000
mean       41.174202
std        24.990325
min         4.000000
25%        27.000000
50%        36.000000
75%        48.000000
max       340.000000
dtype: float64

Combining skills metadata

In [47]:
smd = esco.combine_skills_metadata(variable_selection=None)
smd

,conceptType,conceptUri,skillType,reuseLevel,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,scopeNote,definition,inScheme,description,broaderConceptPT,machineScore_green,skill_green_esco,scope_eth,impact_eth,skill_green_eth,comment_eth,broaderConceptUri,alternative_class_eth,scope_eth_brown,skill_brown_esco,impact_eth_brown,comment_eth_brown,machineScore_brown,skill_brown_eth,alternative_class_eth_brown,skill_neutral_esco,skill_classification_esco,coreness
0,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0005c151-5b5a...,skill/competence,sector-specific,manage musical staff,manage staff of music\ncoordinate duties of mu...,NaN,released,2016-12-20T17:43:43Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Assign and manage staff tasks in areas such as...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,neutral,0.002187
1,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00064735-8fad...,skill/competence,occupation-specific,supervise correctional procedures,oversee prison procedures\nmanage correctional...,NaN,released,2016-12-20T20:17:49Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Supervise the operations of a correctional fac...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,neutral,0.000000
2,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/000709ed-2be5...,skill/competence,sector-specific,apply anti-oppressive practices,apply non-oppressive practices\napply an anti-...,NaN,released,2016-12-20T19:18:19Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Identify oppression in societies, economies, c...",NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,neutral,0.000748
3,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0007bdc2-dd15...,skill/competence,sector-specific,control compliance of railway vehicles regulat...,monitoring of compliance with railway vehicles...,NaN,released,2016-12-20T20:02:19Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,"Inspect rolling stock, components and systems ...",NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,neutral,0.049473
4,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00090cc1-1f27...,skill/competence,cross-sector,identify available services,establish available services\ndetermine rehabi...,NaN,released,2016-12-20T20:15:17Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Identify the different services available for ...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,neutral,0.001577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13886,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/ffef5eb3-a15e...,skill/competence,sector-specific,remediate healthcare user's occupational perfo...,restore healthcare user's occupational perform...,NaN,released,2016-12-20T19:25:53Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,"Remediate or restore the cognitive, sensorimot...",NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,neutral,0.000103
13887,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff0b074-5a76...,skill/competence,sector-specific,install transport equipment lighting,install transport equipment illumination\nfix ...,NaN,released,2016-12-20T20:03:21Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Install lighting elements in transport equipme...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,neutral,0.013943
13888,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff0e2cd-d0bd...,knowledge,sector-specific,natural language processing,NLP,NaN,released,2016-08-04T15:19:37Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,The technologies which enable ICT devices to u...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,neutral,0.025162
13889,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff5bc45-b506...,skill/competence,cross-sector,coordinate construction activities,reviewing construction progress\nconstruction ...,NaN,released,2016-12-20T18:22:35Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Coordinate the activities of several construct...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,neutral,0.065232
13890,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/fff74a70-4f82...,skill/competence,cross-sector,position guardrails and toeboards,positioning guardrails and toeboards\nattachme...,NaN,released,2016-12-20T18:24:23Z,NaN,NaN,http://data.europa.eu/esco/concept-scheme/skil...,Attach guardrails and toeboards to the scaffol...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,neutral,0.006670

Calculating GBN shares at occupation level

In [48]:
esco.calc_gbn_shares_skill_based(skills_metadata=smd)

,conceptUri,n_total_specific_skills,n_green_specific_skills_esco,share_green_esco,n_brown_specific_skills_esco,share_brown_esco,n_neutral_specific_skills_esco,share_neutral_esco,gbn_classification_esco
0,http://data.europa.eu/esco/occupation/00030d09...,8,0,0.000000,0,0.000000,8,1.000000,neutral
1,http://data.europa.eu/esco/occupation/000e93a3...,39,0,0.000000,5,0.128205,34,0.871795,neutral
2,http://data.europa.eu/esco/occupation/0019b951...,43,0,0.000000,0,0.000000,43,1.000000,neutral
3,http://data.europa.eu/esco/occupation/0022f466...,39,2,0.051282,0,0.000000,37,0.948718,neutral
4,http://data.europa.eu/esco/occupation/002da35b...,26,0,0.000000,0,0.000000,26,1.000000,neutral
...,...,...,...,...,...,...,...,...,...
3003,http://data.europa.eu/esco/occupation/ff656b3a...,58,0,0.000000,0,0.000000,58,1.000000,neutral
3004,http://data.europa.eu/esco/occupation/ff8d4065...,26,14,0.538462,0,0.000000,12,0.461538,green
3005,http://data.europa.eu/esco/occupation/ffa4dd5d...,29,0,0.000000,1,0.034483,28,0.965517,neutral
3006,http://data.europa.eu/esco/occupation/ffade2f4...,31,0,0.000000,0,0.000000,31,1.000000,neutral
3007,http://data.europa.eu/esco/occupation/ffc292f1...,57,1,0.017544,1,0.017544,55,0.964912,neutral