# Calculation of occupational-level green/brown shares based on ESCO and ONET data
Felix Zaussinger | 17.05.2022

## Core Analysis Goal(s)
1. Calculate g/b shares based on ESCO skills data
2. Collect g/b shares based on various ONET data at different granularity levels
3. Combine into a central data set
4. Derive a final data set by using both ESCO and ONET data to triangulate green and brown occupations

**Overview of data sets**

1 ONET: Vona 2018 (Greenness), SOC 8-digit matched via ONET-ESCO crosswalk [CHECK]
2 ONET: GTP 2011 (Greenness), SOC 8-digit matched via ONET-ESCO crosswalk [CHECK]
3 ONET: Vona 2019 (Greenness), SOC 6-digit matched via IBS SOC-ISCO crosswalk
4 ONET: JRC/Consoli (Greenness), CP-2011 5-digit matched via CP2011-ESCO crosswalk
5 ESCO: ESCO 2022 (Greenness) [CHECK]

## Key Insight(s)
1.
2.
 3.

In [1]:
import os
import sys
import logging
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from src import utils
import mapping_career_causeways

# OPTIONAL: Load the "autoreload" extension so that code can change
%load_ext autoreload

# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2

# Settings
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

sns.set_context("poster")
sns.set(rc={'figure.figsize': (16, 9.)})
sns.set_style("ticks")

pd.set_option("display.max_rows", 120)
pd.set_option("display.max_columns", 120)

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

# load paths
useful_paths = utils.UsefulPaths()

**Initialise main objects**

In [95]:
from src.data.framework import Esco, Onet, Classifications, Crosswalks

esco = Esco()
onet = Onet()
classifications = Classifications()
crosswalks = Crosswalks()

**1) Combine ESCO skills metadata**

In [31]:
var_sel_skills = [
    'conceptType', 'conceptUri', 'skillType', 'reuseLevel', 'preferredLabel',
    'skill_green_esco', 'skill_brown_esco', 'skill_neutral_esco', 'skill_classification_esco',
    'skill_green_eth', 'skill_brown_eth', 'machineScore_green', 'machineScore_brown',
]

smd = esco.combine_skills_metadata(override=True, variable_selection=var_sel_skills)
smd.head()

C:\Users\fzaussinger\Miniconda3\envs\re4gt\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
C:\Users\fzaussinger\Miniconda3\envs\re4gt\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,conceptType,conceptUri,skillType,reuseLevel,preferredLabel,skill_green_esco,skill_brown_esco,skill_neutral_esco,skill_classification_esco,skill_green_eth,skill_brown_eth,machineScore_green,machineScore_brown
0,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0005c151-5b5a...,skill/competence,sector-specific,manage musical staff,False,False,True,neutral,NaN,NaN,NaN,NaN
1,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00064735-8fad...,skill/competence,occupation-specific,supervise correctional procedures,False,False,True,neutral,NaN,NaN,NaN,NaN
2,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/000709ed-2be5...,skill/competence,sector-specific,apply anti-oppressive practices,False,False,True,neutral,NaN,NaN,NaN,NaN
3,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/0007bdc2-dd15...,skill/competence,sector-specific,control compliance of railway vehicles regulat...,False,False,True,neutral,NaN,NaN,NaN,NaN
4,KnowledgeSkillCompetence,http://data.europa.eu/esco/skill/00090cc1-1f27...,skill/competence,cross-sector,identify available services,False,False,True,neutral,NaN,NaN,NaN,NaN

**2) Calculate GBN occupation shares based on ESCO skill classifications**

In [40]:
# based on essential and optional skills, unweighted
esco_gbn_shares_all = esco.calc_gbn_shares_skill_based(skills_metadata=smd, drop_counts=True, essential_only=False)

# based on essential skills only (similar to core greenness in Vona et al. 2019)
esco_gbn_shares_ess = esco.calc_gbn_shares_skill_based(skills_metadata=smd, drop_counts=True, essential_only=True)

T:\Documents\Projects\04_jrc_green-skills-regional\03_data-analysis\re4gt\src\data\framework.py:1361: RuntimeWarning: invalid value encountered in true_divide
  occ_share = n_gbn_specific_skills / n_total_specific_skills

In [43]:
esco_gbn_shares_ess.columns

Index(['conceptUri', 'share_green_esco', 'share_brown_esco',
       'share_neutral_esco', 'gbn_classification_esco'],
      dtype='object')

**3) Combine ESCO-level occupation metadata**

In [116]:
var_sel_occs = [
    "conceptUri", "preferredLabel", "description", "isco_level_4", "isco_level_3", "isco_level_2", "isco_level_1", "isco_label_4", "isco_label_3", "isco_label_2", "isco_label_1",
    'share_green_esco', 'share_brown_esco', 'share_neutral_esco', 'gbn_classification_esco',
    'share_green_esco_ess', 'share_brown_esco_ess', 'share_neutral_esco_ess', 'gbn_classification_esco_ess',
]

omd = esco.combine_occupation_metadata(skills_metadata=smd, variable_selection=var_sel_occs)

T:\Documents\Projects\04_jrc_green-skills-regional\03_data-analysis\re4gt\src\data\framework.py:1347: RuntimeWarning: invalid value encountered in true_divide
  # TODO: remove [:1] once ETH skill classification is finished

**4) Join 8-digit ONET-level occupation metadata to Nesta crosswalk**

In [49]:
# read Nesta crosswalk
cw_onet_esco = crosswalks.onet_esco_mcc_full
cw_onet_esco

,onet_code,title,share_green_vona2018,total_spec_tasks_vona2018,green_spec_tasks_vona2018
0,11-1011.03,Chief Sustainability Officers,1.000000,18,18
1,11-1021.00,General and Operations Managers,0.055556,18,1
2,11-2021.00,Marketing Managers,0.200000,20,4
3,11-3051.02,Geothermal Production Managers,1.000000,17,17
4,11-3051.04,Biomass Power Plant Managers,1.000000,18,18
5,11-3071.01,Transportation Managers,0.178571,28,5
6,11-3071.02,Storage and Distribution Managers,0.233333,30,7
7,11-3071.03,Logistics Managers,0.300000,30,9
8,11-9021.00,Construction Managers,0.280000,25,7
9,11-9041.00,Architectural and Engineering Managers,0.190476,21,4
10,11-9121.02,Water Resource Specialists,1.000000,21,21
11,11-9199.01,Regulatory Affairs Managers,0.148148,27,4
12,11-9199.02,Compliance Managers,0.200000,30,6
13,11-9199.04,Supply Chain Managers,0.300000,30,9
14,11-9199.11,Brownfield Redevelopment Specialists and Site ...,1.000000,22,22
15,13-1022.00,"Wholesale and Retail Buyers, Except Farm Products",0.238095,21,5
16,13-1041.07,Regulatory Affairs Specialists,0.187500,32,6
17,13-1081.01,Logistics Engineers,0.366667,30,11
18,13-1081.02,Logistics Analysts,0.193548,31,6
19,13-1151.00,Training and Development Specialists,0.095238,21,2
20,13-1199.01,Energy Auditors,1.000000,21,21
21,13-1199.05,Sustainability Specialists,1.000000,14,14
22,13-2051.00,Financial Analysts,0.333333,18,6
23,13-2052.00,Personal Financial Advisors,0.142857,21,3
24,13-2099.02,Risk Management Specialists,0.166667,24,4
25,15-1199.04,Geospatial Information Scientists and Technolo...,0.083333,24,2
26,15-1199.05,Geographic Information Systems Technicians,0.263158,19,5
27,17-1011.00,"Architects, Except Landscape and Naval",0.368421,19,7
28,17-1012.00,Landscape Architects,0.263158,19,5
29,17-2011.00,Aerospace Engineers,0.333333,18,6
30,17-2051.00,Civil Engineers,0.470588,17,8
31,17-2051.01,Transportation Engineers,0.230769,26,6
32,17-2071.00,Electrical Engineers,0.136364,22,3
33,17-2072.00,"Electronics Engineers, Except Computer",0.217391,23,5
34,17-2081.00,Environmental Engineers,1.000000,28,28
35,17-2081.01,Water/Wastewater Engineers,1.000000,27,27
36,17-2141.00,Mechanical Engineers,0.259259,27,7
37,17-2161.00,Nuclear Engineers,0.350000,20,7
38,17-2199.01,Biochemical Engineers,0.342857,35,12
39,17-2199.02,Validation Engineers,0.090909,22,2
40,17-2199.03,Energy Engineers,0.952381,21,20
41,17-2199.04,Manufacturing Engineers,0.166667,24,4
42,17-2199.05,Mechatronics Engineers,0.130435,23,3
43,17-2199.07,Photonics Engineers,0.192308,26,5
44,17-2199.08,Robotics Engineers,0.083333,24,2
45,17-2199.10,Wind Energy Engineers,1.000000,16,16
46,17-3023.03,Electrical Engineering Technicians,0.208333,24,5
47,17-3024.00,Electro-Mechanical Technicians,0.083333,12,1
48,17-3024.01,Robotics Technicians,0.086957,23,2
49,17-3025.00,Environmental Engineering Technicians,1.000000,26,26
50,17-3026.00,Industrial Engineering Technicians,0.222222,18,4
51,17-3029.02,Electrical Engineering Technologists,0.400000,20,8
52,17-3029.03,Electromechanical Engineering Technologists,0.294118,17,5
53,17-3029.04,Electronics Engineering Technologists,0.173913,23,4
54,17-3029.05,Industrial Engineering Technologists,0.173913,23,4
55,17-3029.06,Manufacturing Engineering Technologists,0.275862,29,8
56,17-3029.07,Mechanical Engineering Technologists,0.142857,21,3
57,17-3029.08,Photonics Technicians,0.200000,30,6
58,17-3029.09,Manufacturing Production Technicians,0.200000,30,6
59,19-1013.00,Soil and Plant Scientists,0.629630,27,17
60,19-1031.01,Soil and Water Conservationists,1.000000,33,33
61,19-2021.00,Atmospheric and Space Scientists,0.500000,24,12
62,19-2041.01,Climate Change Analysts,1.000000,14,14
63,19-2041.02,Environmental Restoration Planners,1.000000,22,22
64,19-2042.00,"Geoscientists, Except Hydrologists and Geograp...",0.483871,31,15
65,19-2099.01,Remote Sensing Scientists and Technologists,0.083333,24,2
66,19-3011.01,Environmental Economists,1.000000,19,19
67,19-3051.00,Urban and Regional Planners,0.368421,19,7
68,19-3099.01,Transportation Planners,0.136364,22,3
69,19-4011.01,Agricultural Technicians,0.120000,25,3
70,19-4041.01,Geophysical Data Technicians,0.238095,21,5
71,19-4041.02,Geological Sample Test Technicians,0.187500,16,3
72,19-4051.01,Nuclear Equipment Operation Technicians,0.411765,17,7
73,19-4091.00,Environmental Science and Protection Technicia...,1.000000,25,25
74,19-4099.02,Precision Agriculture Technicians,0.304348,23,7
75,19-4099.03,Remote Sensing Technicians,0.136364,22,3
76,23-1022.00,"Arbitrators, Mediators, and Conciliators",0.050000,20,1
77,27-3022.00,Reporters and Correspondents,0.045455,22,1
78,27-3031.00,Public Relations Specialists,0.235294,17,4
79,29-9012.00,Occupational Health and Safety Technicians,0.346154,26,9
80,41-4011.00,"Sales Representatives, Wholesale and Manufactu...",0.105263,38,4
81,41-4011.07,Solar Sales Representatives and Assessors,1.000000,13,13
82,43-5071.00,"Shipping, Receiving, and Traffic Clerks",0.090909,11,1
83,47-2061.00,Construction Laborers,0.181818,33,6
84,47-2152.01,Pipe Fitters and Steamfitters,0.150000,20,3
85,47-2152.02,Plumbers,0.391304,23,9
86,47-2181.00,Roofers,0.300000,30,9
87,47-2211.00,Sheet Metal Workers,0.240000,25,6
88,47-2231.00,Solar Photovoltaic Installers,1.000000,26,26
89,47-4011.00,Construction and Building Inspectors,0.263158,19,5
90,47-4041.00,Hazardous Materials Removal Workers,0.913043,23,21
91,47-4099.03,Weatherization Installers and Technicians,1.000000,18,18
92,47-5013.00,"Service Unit Operators, Oil, Gas, and Mining",0.052632,19,1
93,47-5041.00,Continuous Mining Machine Operators,0.166667,12,2
94,49-3023.02,Automotive Specialty Technicians,0.400000,25,10
95,49-3031.00,Bus and Truck Mechanics and Diesel Engine Spec...,0.160000,25,4
96,49-9021.01,Heating and Air Conditioning Mechanics and Ins...,0.233333,30,7
97,49-9071.00,"Maintenance and Repair Workers, General",0.129032,31,4
98,49-9081.00,Wind Turbine Service Technicians,1.000000,13,13
99,49-9099.01,Geothermal Technicians,1.000000,24,24
100,51-2011.00,"Aircraft Structure, Surfaces, Rigging, and Sys...",0.133333,30,4
101,51-4041.00,Machinists,0.068966,29,2
102,51-8011.00,Nuclear Power Reactor Operators,0.333333,18,6
103,51-8013.00,Power Plant Operators,0.208333,24,5
104,51-8099.03,Biomass Plant Technicians,1.000000,16,16
105,51-9012.00,"Separating, Filtering, Clarifying, Precipitati...",0.050000,20,1
106,51-9061.00,"Inspectors, Testers, Sorters, Samplers, and We...",0.062500,32,2
107,51-9199.01,Recycling and Reclamation Workers,1.000000,18,18
108,53-3032.00,Heavy and Tractor-Trailer Truck Drivers,0.090909,33,3
109,53-6051.07,"Transportation Vehicle, Equipment and Systems ...",0.409091,22,9
110,53-7081.00,Refuse and Recyclable Material Collectors,1.000000,16,16

Join Vona 2018 data to crosswalk at ONET 8-digit level

In [71]:
cw_onet_esco_merged = pd.merge(
    cw_onet_esco,
    onet.green_occupations_vona2018[["onet_code", "share_green_vona2018"]],
    on="onet_code",
    how="left"
)

# clean
cw_onet_esco_merged

,id,concept_uri,preferred_label,isco_level_4,onet_code,onet_occupation,onet_code_6d,share_green_vona2018
0,0,http://data.europa.eu/esco/occupation/00030d09...,technical director,2166,27-1011.00,art directors,27-1011,NaN
1,1,http://data.europa.eu/esco/occupation/000e93a3...,metal drawing machine operator,8121,51-4021.00,"extruding and drawing machine setters, operato...",51-4021,NaN
2,2,http://data.europa.eu/esco/occupation/0019b951...,precision device inspector,7543,51-9061.00,"inspectors, testers, sorters, samplers, and we...",51-9061,0.0625
3,3,http://data.europa.eu/esco/occupation/0022f466...,air traffic safety technician,3155,17-3023.01,electronics engineering technicians,17-3023,NaN
4,4,http://data.europa.eu/esco/occupation/002da35b...,hospitality revenue manager,2431,13-1161.00,market research analysts and marketing special...,13-1161,NaN
...,...,...,...,...,...,...,...,...
2937,2937,http://data.europa.eu/esco/occupation/ff656b3a...,demographer,2120,15-2041.00,statisticians,15-2041,NaN
2938,2938,http://data.europa.eu/esco/occupation/ff8d4065...,sorter labourer,9612,51-9199.01,recycling and reclamation workers,51-9199,1.0000
2939,2939,http://data.europa.eu/esco/occupation/ffa4dd5d...,armoured car guard,5414,33-9032.00,security guards,33-9032,NaN
2940,2940,http://data.europa.eu/esco/occupation/ffade2f4...,civil service administrative officer,2422,11-3011.00,administrative services managers,11-3011,NaN
2941,2941,http://data.europa.eu/esco/occupation/ffc292f1...,motor vehicle assembler,8211,51-2031.00,engine and other machine assemblers,51-2031,NaN

Join GTP 2011 data to crosswalk at ONET 8-digit level

In [72]:
cw_onet_esco_merged = pd.merge(
    cw_onet_esco_merged,
    onet.green_occupations_gtp[["onet_code", "share_green_gtp"]],
    on="onet_code",
    how="left"
)

cw_onet_esco_merged

,id,concept_uri,preferred_label,isco_level_4,onet_code,onet_occupation,onet_code_6d,share_green_vona2018,share_green_gtp
0,0,http://data.europa.eu/esco/occupation/00030d09...,technical director,2166,27-1011.00,art directors,27-1011,NaN,NaN
1,1,http://data.europa.eu/esco/occupation/000e93a3...,metal drawing machine operator,8121,51-4021.00,"extruding and drawing machine setters, operato...",51-4021,NaN,NaN
2,2,http://data.europa.eu/esco/occupation/0019b951...,precision device inspector,7543,51-9061.00,"inspectors, testers, sorters, samplers, and we...",51-9061,0.0625,0.0625
3,3,http://data.europa.eu/esco/occupation/0022f466...,air traffic safety technician,3155,17-3023.01,electronics engineering technicians,17-3023,NaN,NaN
4,4,http://data.europa.eu/esco/occupation/002da35b...,hospitality revenue manager,2431,13-1161.00,market research analysts and marketing special...,13-1161,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2937,2937,http://data.europa.eu/esco/occupation/ff656b3a...,demographer,2120,15-2041.00,statisticians,15-2041,NaN,NaN
2938,2938,http://data.europa.eu/esco/occupation/ff8d4065...,sorter labourer,9612,51-9199.01,recycling and reclamation workers,51-9199,1.0000,1.0000
2939,2939,http://data.europa.eu/esco/occupation/ffa4dd5d...,armoured car guard,5414,33-9032.00,security guards,33-9032,NaN,NaN
2940,2940,http://data.europa.eu/esco/occupation/ffade2f4...,civil service administrative officer,2422,11-3011.00,administrative services managers,11-3011,NaN,NaN
2941,2941,http://data.europa.eu/esco/occupation/ffc292f1...,motor vehicle assembler,8211,51-2031.00,engine and other machine assemblers,51-2031,NaN,NaN

**5) Join 6-digit ONET-level occupation metadata to IBS SOC 6D - ISCO 4D crosswalk**

In [111]:
cw_soc_isco = crosswalks.soc10_isco08_ibs
cw_soc_isco

       soc10  isco08
0     111011    1112
1     111011    1113
2     111011    1120
3     111021    1112
4     111021    1114
...      ...     ...
1126  553015     310
1127  553016     310
1128  553017     310
1129  553018     310
1130  553019     310

[1131 rows x 2 columns]

Join 6-digit level brown classification from Vona et al. 2018

In [96]:
brown_occupations_vona2018 = onet.brown_occupations_vona2018
brown_occupations_vona2018["soc_code"] = brown_occupations_vona2018["soc_code"].str.replace("-", "").astype(int)
brown_occupations_vona2018["is_brown_vona2018"] = np.ones(
    brown_occupations_vona2018.shape[0], dtype=int
)

In [102]:
cw_soc_isco_merged = pd.merge(
    cw_soc_isco,
    brown_occupations_vona2018.drop(columns=["occupation"]),
    left_on="soc10",
    right_on="soc_code",
    how="left"
).drop(columns=["soc_code"])

cw_soc_isco_merged["is_brown_vona2018"] = cw_soc_isco_merged["is_brown_vona2018"].fillna(0)

Join 6-digit level greeness scores from Vona et al. 2019

In [115]:
# TODO

Aggregate data by ISCO 4D level

In [136]:
onet_to_isco_4d = cw_soc_isco_merged.groupby("isco08")["is_brown_vona2018"].mean()
onet_to_isco_4d = onet_to_isco_4d.reset_index()
onet_to_isco_4d = onet_to_isco_4d.rename(columns={"is_brown_vona2018": "share_brown_vona2018"})
onet_to_isco_4d["isco08"] = onet_to_isco_4d["isco08"].astype(str)
onet_to_isco_4d

    isco08  share_brown_vona2018
0      110                   0.0
1      210                   0.0
2      310                   0.0
3     1111                   0.0
4     1112                   0.0
..     ...                   ...
431   9621                   0.0
432   9622                   0.0
433   9623                   0.5
434   9624                   0.0
435   9629                   0.0

[436 rows x 2 columns]

**7) Combine all information into a single ESCO-level data set, attaching ONET data either via ESCO directly (ONET 8-digits), or via ISCO (SOC 6-digits)**

In [137]:
occ_master_ds = omd.copy()

Join 8-digit ONET data (via Nesta crosswalk)

In [138]:
occ_master_ds = pd.merge(
    occ_master_ds,
    cw_onet_esco_merged[["concept_uri", "share_green_gtp", "share_green_vona2018"]],
    left_on="conceptUri",
    right_on="concept_uri",
    how="left"
).drop(columns="concept_uri")

occ_master_ds["share_green_gtp"] = occ_master_ds["share_green_gtp"].fillna(0)
occ_master_ds["share_green_vona2018"] = occ_master_ds["share_green_vona2018"].fillna(0)
occ_master_ds

,conceptUri,preferredLabel,description,isco_level_4,isco_level_3,isco_level_2,isco_level_1,isco_label_4,isco_label_3,isco_label_2,isco_label_1,share_green_esco,share_brown_esco,share_neutral_esco,gbn_classification_esco,share_green_esco_ess,share_brown_esco_ess,share_neutral_esco_ess,gbn_classification_esco_ess,share_green_gtp,share_green_vona2018
0,http://data.europa.eu/esco/occupation/00030d09...,technical director,Technical directors realise the artistic visio...,2654,265,26,2,"Film, stage and related directors and producers",Creative and performing artists,"Legal, social and cultural professionals",Professionals,0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral,0.0,0.0
1,http://data.europa.eu/esco/occupation/1a7fb683...,video and motion picture director,Video and motion picture directors are respons...,2654,265,26,2,"Film, stage and related directors and producers",Creative and performing artists,"Legal, social and cultural professionals",Professionals,0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral,0.0,0.0
2,http://data.europa.eu/esco/occupation/2f372afe...,performance lighting director,Performance lighting directors determine what ...,2654,265,26,2,"Film, stage and related directors and producers",Creative and performing artists,"Legal, social and cultural professionals",Professionals,0.052632,0.0,0.947368,neutral,0.055556,0.0,0.944444,neutral,0.0,0.0
3,http://data.europa.eu/esco/occupation/30b25ee4...,animation director,Animation directors supervise and recruit mult...,2654,265,26,2,"Film, stage and related directors and producers",Creative and performing artists,"Legal, social and cultural professionals",Professionals,0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral,0.0,0.0
4,http://data.europa.eu/esco/occupation/3b6bea7d...,video and motion picture producer,Video and motion picture producers supervise t...,2654,265,26,2,"Film, stage and related directors and producers",Creative and performing artists,"Legal, social and cultural professionals",Professionals,0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3003,http://data.europa.eu/esco/occupation/b059d331...,hawker,Hawkers sell goods and services on established...,9520,952,95,9,Street vendors (excluding food),Street vendors (excluding food),Street and related sales and service workers,Elementary occupations,0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral,0.0,0.0
3004,http://data.europa.eu/esco/occupation/96a0d8d3...,quick service restaurant crew member,"Quick service restaurant crew members prepare,...",9411,941,94,9,Fast food preparers,Food preparation assistants,Food preparation assistants,Elementary occupations,0.040000,0.0,0.960000,neutral,0.058824,0.0,0.941176,neutral,0.0,0.0
3005,http://data.europa.eu/esco/occupation/a02a1117...,pizzaiolo,Pizzaiolos are responsible for preparing and c...,9411,941,94,9,Fast food preparers,Food preparation assistants,Food preparation assistants,Elementary occupations,0.047619,0.0,0.952381,neutral,0.066667,0.0,0.933333,neutral,0.0,0.0
3006,http://data.europa.eu/esco/occupation/e1cf6897...,kitchen assistant,Kitchen assistants assist in the preparation o...,9412,941,94,9,Kitchen helpers,Food preparation assistants,Food preparation assistants,Elementary occupations,0.064516,0.0,0.935484,neutral,0.100000,0.0,0.900000,neutral,0.0,0.0
3007,http://data.europa.eu/esco/occupation/f756fdab...,kitchen porter,"Kitchen porters wash and clean kitchen areas, ...",9412,941,94,9,Kitchen helpers,Food preparation assistants,Food preparation assistants,Elementary occupations,0.125000,0.0,0.875000,neutral,0.142857,0.0,0.857143,neutral,0.0,0.0

Join 6-digit ONET data (via ISCO 4D codes)

In [139]:
occ_master_ds = pd.merge(
    occ_master_ds,
    onet_to_isco_4d,
    left_on="isco_level_4",
    right_on="isco08",
    how="left"
).drop(columns=["isco08"])

In [140]:
occ_master_ds

,conceptUri,preferredLabel,description,isco_level_4,isco_level_3,isco_level_2,isco_level_1,isco_label_4,isco_label_3,isco_label_2,isco_label_1,share_green_esco,share_brown_esco,share_neutral_esco,gbn_classification_esco,share_green_esco_ess,share_brown_esco_ess,share_neutral_esco_ess,gbn_classification_esco_ess,share_green_gtp,share_green_vona2018,share_brown_vona2018
0,http://data.europa.eu/esco/occupation/00030d09...,technical director,Technical directors realise the artistic visio...,2654,265,26,2,"Film, stage and related directors and producers",Creative and performing artists,"Legal, social and cultural professionals",Professionals,0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral,0.0,0.0,0.0
1,http://data.europa.eu/esco/occupation/1a7fb683...,video and motion picture director,Video and motion picture directors are respons...,2654,265,26,2,"Film, stage and related directors and producers",Creative and performing artists,"Legal, social and cultural professionals",Professionals,0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral,0.0,0.0,0.0
2,http://data.europa.eu/esco/occupation/2f372afe...,performance lighting director,Performance lighting directors determine what ...,2654,265,26,2,"Film, stage and related directors and producers",Creative and performing artists,"Legal, social and cultural professionals",Professionals,0.052632,0.0,0.947368,neutral,0.055556,0.0,0.944444,neutral,0.0,0.0,0.0
3,http://data.europa.eu/esco/occupation/30b25ee4...,animation director,Animation directors supervise and recruit mult...,2654,265,26,2,"Film, stage and related directors and producers",Creative and performing artists,"Legal, social and cultural professionals",Professionals,0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral,0.0,0.0,0.0
4,http://data.europa.eu/esco/occupation/3b6bea7d...,video and motion picture producer,Video and motion picture producers supervise t...,2654,265,26,2,"Film, stage and related directors and producers",Creative and performing artists,"Legal, social and cultural professionals",Professionals,0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3003,http://data.europa.eu/esco/occupation/b059d331...,hawker,Hawkers sell goods and services on established...,9520,952,95,9,Street vendors (excluding food),Street vendors (excluding food),Street and related sales and service workers,Elementary occupations,0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral,0.0,0.0,0.0
3004,http://data.europa.eu/esco/occupation/96a0d8d3...,quick service restaurant crew member,"Quick service restaurant crew members prepare,...",9411,941,94,9,Fast food preparers,Food preparation assistants,Food preparation assistants,Elementary occupations,0.040000,0.0,0.960000,neutral,0.058824,0.0,0.941176,neutral,0.0,0.0,0.0
3005,http://data.europa.eu/esco/occupation/a02a1117...,pizzaiolo,Pizzaiolos are responsible for preparing and c...,9411,941,94,9,Fast food preparers,Food preparation assistants,Food preparation assistants,Elementary occupations,0.047619,0.0,0.952381,neutral,0.066667,0.0,0.933333,neutral,0.0,0.0,0.0
3006,http://data.europa.eu/esco/occupation/e1cf6897...,kitchen assistant,Kitchen assistants assist in the preparation o...,9412,941,94,9,Kitchen helpers,Food preparation assistants,Food preparation assistants,Elementary occupations,0.064516,0.0,0.935484,neutral,0.100000,0.0,0.900000,neutral,0.0,0.0,0.0
3007,http://data.europa.eu/esco/occupation/f756fdab...,kitchen porter,"Kitchen porters wash and clean kitchen areas, ...",9412,941,94,9,Kitchen helpers,Food preparation assistants,Food preparation assistants,Elementary occupations,0.125000,0.0,0.875000,neutral,0.142857,0.0,0.857143,neutral,0.0,0.0,0.0