# Fix bugs in data merging of ESCO and O*NET
Felix Zaussinger | 13.04.2022

## Core Analysis Goal(s)
1. Fix bugs in occupation and skills metadata merging.
2. Gain confidence that the final datasets are valid.
3.

## Key Insight(s)
1.
2.
3.

In [1]:
import os
import sys
import logging
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from src import utils
# import mapping_career_causeways

# OPTIONAL: Load the "autoreload" extension so that code can change
%load_ext autoreload

# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2

# Settings
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

sns.set_context("poster")
sns.set(rc={'figure.figsize': (16, 9.)})
sns.set_style("ticks")

pd.set_option("display.max_rows", 120)
pd.set_option("display.max_columns", 120)

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

# load paths
useful_paths = utils.UsefulPaths()

In [2]:
from src import utils, stats_utils, plotting_utils
from src.data.framework import Esco, Onet, Crosswalks

Code ...

In [3]:
esco = Esco()
crosswalks = Crosswalks()
onet = Onet()

### Checking problems with ONET-ESCO crosswalk
- some ONET greening occupations missing in Nesta crosswalk

In [4]:
gt_esco = esco.read_greenness_task_based()

In [5]:
gt_esco.title_gtp.unique()

array(['Chief Sustainability Officers', 'Green Marketers',
       'Geothermal Production Managers', 'Biofuels Production Managers',
       'Biomass Production Managers',
       'Methane/Landfill Gas Collection System Operators',
       'Hydroelectric Production Managers',
       'Biofuels/Biodiesel Technology and Product Development Managers',
       'Water Resource Specialists', 'Wind Energy Operations Managers',
       'Wind Energy Project Managers',
       'Brownfield Redevelopment Specialists and Site Managers',
       'Energy Auditors', 'Sustainability Specialists',
       'Environmental Engineers', 'Water/Wastewater Engineers',
       'Fuel Cell Engineers', 'Energy Engineers', 'Wind Energy Engineers',
       'Solar Energy Systems Engineers',
       'Environmental Engineering Technicians', 'Fuel Cell Technicians',
       'Soil and Water Conservationists', 'Climate Change Analysts',
       'Environmental Restoration Planners', 'Industrial Ecologists',
       'Environmental Economists',
       'Environmental Science and Protection Technicians, Including Health',
       'Energy Brokers', 'Solar Sales Representatives and Assessors',
       'Solar Energy Installation Managers',
       'Hazardous Materials Removal Workers',
       'Solar Photovoltaic Installers',
       'Solar Thermal Installers and Technicians',
       'Weatherization Installers and Technicians',
       'Geothermal Technicians', 'Wind Turbine Service Technicians',
       'Biofuels Processing Technicians',
       'Methane/Landfill Gas Generation System Technicians',
       'Biomass Plant Technicians', 'Hydroelectric Plant Technicians',
       'Recycling and Reclamation Workers', 'Recycling Coordinators',
       'Refuse and Recyclable Material Collectors', 'Aerospace Engineers',
       'Atmospheric and Space Scientists',
       'Geoscientists, Except Hydrologists and Geographers',
       'Civil Engineers', 'Automotive Specialty Technicians',
       'Transportation Vehicle, Equipment and Systems Inspectors, Except Aviation',
       'Electrical Engineering Technologists',
       'Nuclear Equipment Operation Technicians', 'Plumbers',
       'Nuclear Engineers', 'Urban and Regional Planners',
       'Logistics Engineers', 'Nanosystems Engineers',
       'Nanotechnology Engineering Technologists',
       'Occupational Health and Safety Technicians',
       'Biochemical Engineers', 'Financial Analysts',
       'Electromechanical Engineering Technologists', 'Roofers',
       'Automotive Engineers', 'Precision Agriculture Technicians',
       'Construction and Building Inspectors', 'Supply Chain Managers',
       'Manufacturing Engineering Technologists', 'Construction Managers',
       'Architects, Except Landscape and Naval', 'Logistics Managers',
       'Wholesale and Retail Buyers, Except Farm Products',
       'Nuclear Power Reactor Operators', 'Mechanical Engineers',
       'Automotive Engineering Technicians',
       'Heating and Air Conditioning Mechanics and Installers',
       'Geographic Information Systems Technicians',
       'Landscape Architects', 'Storage and Distribution Managers',
       'Transportation Engineers', 'Industrial Engineering Technicians',
       'Sheet Metal Workers', 'Financial Quantitative Analysts',
       'Electronics Engineers, Except Computer',
       'Public Relations Specialists  ', 'Freight Forwarders',
       'Geophysical Data Technicians', 'Transportation Managers',
       'Electrical Engineering Technicians', 'Power Plant Operators',
       'Compliance Managers', 'Marketing Managers',
       'Microsystems Engineers', 'Photonics Technicians',
       'Manufacturing Production Technicians', 'Logistics Analysts',
       'Photonics Engineers', 'Engineering Managers',
       'Regulatory Affairs Specialists', 'Electrical Engineers',
       'Construction Laborers', 'Geological Sample Test Technicians',
       'Risk Management Specialists',
       'Electronics Engineering Technologists',
       'Industrial Engineering Technologists', 'Manufacturing Engineers',
       'Nanotechnology Engineering Technicians',
       'Mechanical Engineering Technologists',
       'Pipe Fitters and Steamfitters', 'Regulatory Affairs Managers',
       'Farm and Ranch Managers', 'Personal Financial Advisors',
       'Maintenance and Repair Workers, General',
       'Transportation Planners', 'Remote Sensing Technicians',
       'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products',
       'Continuous Mining Machine Operators',
       'Aircraft Structure, Surfaces, Rigging, and Systems Assemblers',
       'Mechatronics Engineers', 'General and Operations Managers',
       'Investment Underwriters', 'Agricultural Technicians',
       'Robotics Technicians', 'Training and Development Specialists',
       'Truck Drivers, Heavy and Tractor-Trailer', 'Validation Engineers',
       'Robotics Engineers', 'Securities and Commodities Traders',
       'Shipping, Receiving, and Traffic Clerks',
       'Geospatial Information Scientists and Technologists',
       'Electro-Mechanical Technicians',
       'Remote Sensing Scientists and Technologists', 'Machinists',
       'Inspectors, Testers, Sorters, Samplers, and Weighers',
       'Service Unit Operators, Oil, Gas, and Mining',
       'Arbitrators, Mediators, and Conciliators',
       'Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders',
       'Reporters and Correspondents'], dtype=object)

63 ONET greening occupations dont have a match to ESCO based on current crosswalk

In [6]:
bsel = gt_esco.loc[:, ["preferred_label"]].isna().values
df_no_match = gt_esco.loc[bsel]
df_no_match

,onet_code,title_gtp,occupation_type,n_new_green_tasks_gtp,n_existing_green_tasks_gtp,n_non_green_tasks_gtp,share_green_gtp,title_vona2018,share_green_vona2018,total_spec_tasks_vona2018,green_spec_tasks_vona2018,id,concept_uri,preferred_label,isco_level_4,onet_occupation
1,11-2011.01,Green Marketers,New Green N&E,16,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11-3051.02,Geothermal Production Managers,New Green N&E,17,0,0,1.000000,Geothermal Production Managers,1.000000,17.0,17.0,NaN,NaN,NaN,NaN,NaN
3,11-3051.03,Biofuels Production Managers,New Green N&E,14,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11-3051.04,Biomass Production Managers,New Green N&E,18,0,0,1.000000,Biomass Power Plant Managers,1.000000,18.0,18.0,NaN,NaN,NaN,NaN,NaN
5,11-3051.05,Methane/Landfill Gas Collection System Operators,New Green N&E,21,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,11-3051.06,Hydroelectric Production Managers,New Green N&E,19,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,11-9041.01,Biofuels/Biodiesel Technology and Product Deve...,New Green N&E,19,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,11-9121.02,Water Resource Specialists,New Green N&E,21,0,0,1.000000,Water Resource Specialists,1.000000,21.0,21.0,NaN,NaN,NaN,NaN,NaN
9,11-9199.09,Wind Energy Operations Managers,New Green N&E,16,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11-9199.10,Wind Energy Project Managers,New Green N&E,15,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11-9199.11,Brownfield Redevelopment Specialists and Site ...,New Green N&E,22,0,0,1.000000,Brownfield Redevelopment Specialists and Site ...,1.000000,22.0,22.0,NaN,NaN,NaN,NaN,NaN
22,17-2081.01,Water/Wastewater Engineers,New Green N&E,27,0,0,1.000000,Water/Wastewater Engineers,1.000000,27.0,27.0,NaN,NaN,NaN,NaN,NaN
23,17-2141.01,Fuel Cell Engineers,Existing Green N&E,3,23,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,17-2199.10,Wind Energy Engineers,New Green N&E,16,0,0,1.000000,Wind Energy Engineers,1.000000,16.0,16.0,NaN,NaN,NaN,NaN,NaN
33,17-2199.11,Solar Energy Systems Engineers,New Green N&E,13,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,17-3029.10,Fuel Cell Technicians,Existing Green N&E,4,12,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,19-1031.01,Soil and Water Conservationists,Green Enhanced Skills,8,25,0,1.000000,Soil and Water Conservationists,1.000000,33.0,33.0,NaN,NaN,NaN,NaN,NaN
40,19-2041.01,Climate Change Analysts,New Green N&E,14,0,0,1.000000,Climate Change Analysts,1.000000,14.0,14.0,NaN,NaN,NaN,NaN,NaN
41,19-2041.02,Environmental Restoration Planners,New Green N&E,22,0,0,1.000000,Environmental Restoration Planners,1.000000,22.0,22.0,NaN,NaN,NaN,NaN,NaN
43,19-3011.01,Environmental Economists,New Green N&E,20,0,0,1.000000,Environmental Economists,1.000000,19.0,19.0,NaN,NaN,NaN,NaN,NaN
48,41-3099.01,Energy Brokers,Existing Green N&E,4,12,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,47-1011.03,Solar Energy Installation Managers,New Green N&E,15,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,47-4099.01,Solar Photovoltaic Installers,New Green N&E,26,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,47-4099.02,Solar Thermal Installers and Technicians,New Green N&E,21,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,49-9099.01,Geothermal Technicians,New Green N&E,26,0,0,1.000000,Geothermal Technicians,1.000000,24.0,24.0,NaN,NaN,NaN,NaN,NaN
57,49-9099.02,Wind Turbine Service Technicians,New Green N&E,13,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,51-8099.01,Biofuels Processing Technicians,New Green N&E,19,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,51-8099.03,Biomass Plant Technicians,New Green N&E,16,0,0,1.000000,Biomass Plant Technicians,1.000000,16.0,16.0,NaN,NaN,NaN,NaN,NaN
65,53-1021.01,Recycling Coordinators,New Green N&E,23,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,17-2011.00,Aerospace Engineers,Green Enhanced Skills,5,4,9,0.500000,Aerospace Engineers,0.333333,18.0,6.0,NaN,NaN,NaN,NaN,NaN
100,53-6051.07,"Transportation Vehicle, Equipment and Systems ...",Green Enhanced Skills,8,1,12,0.428571,"Transportation Vehicle, Equipment and Systems ...",0.409091,22.0,9.0,NaN,NaN,NaN,NaN,NaN
101,17-3029.02,Electrical Engineering Technologists,Existing Green N&E,7,1,11,0.421053,Electrical Engineering Technologists,0.400000,20.0,8.0,NaN,NaN,NaN,NaN,NaN
102,19-4051.01,Nuclear Equipment Operation Technicians,Green Enhanced Skills,7,1,12,0.400000,Nuclear Equipment Operation Technicians,0.411765,17.0,7.0,NaN,NaN,NaN,NaN,NaN
105,17-2161.00,Nuclear Engineers,Green Enhanced Skills,3,4,12,0.368421,Nuclear Engineers,0.350000,20.0,7.0,NaN,NaN,NaN,NaN,NaN
108,13-1081.01,Logistics Engineers,Existing Green N&E,10,1,19,0.366667,Logistics Engineers,0.366667,30.0,11.0,NaN,NaN,NaN,NaN,NaN
109,17-2199.09,Nanosystems Engineers,Existing Green N&E,9,0,16,0.360000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,17-3029.11,Nanotechnology Engineering Technologists,Existing Green N&E,6,0,11,0.352941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,17-3029.03,Electromechanical Engineering Technologists,Existing Green N&E,3,2,10,0.333333,Electromechanical Engineering Technologists,0.294118,17.0,5.0,NaN,NaN,NaN,NaN,NaN
124,17-2141.02,Automotive Engineers,Existing Green N&E,6,2,17,0.320000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,19-4099.02,Precision Agriculture Technicians,Existing Green N&E,4,3,15,0.318182,Precision Agriculture Technicians,0.304348,23.0,7.0,NaN,NaN,NaN,NaN,NaN
142,11-9199.06,Logistics Managers,Existing Green N&E,8,1,21,0.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,51-8011.00,Nuclear Power Reactor Operators,Green Enhanced Skills,6,0,14,0.300000,Nuclear Power Reactor Operators,0.333333,18.0,6.0,NaN,NaN,NaN,NaN,NaN
221,17-3027.01,Automotive Engineering Technicians,Existing Green N&E,4,1,13,0.277778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,15-1099.07,Geographic Information Systems Technicians,Existing Green N&E,5,0,14,0.263158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,17-2051.01,Transportation Engineers,Existing Green N&E,3,3,18,0.250000,Transportation Engineers,0.230769,26.0,6.0,NaN,NaN,NaN,NaN,NaN
238,13-2099.01,Financial Quantitative Analysts,Existing Green N&E,5,0,16,0.238095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,17-2199.06,Microsystems Engineers,Existing Green N&E,5,1,24,0.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,17-3029.09,Manufacturing Production Technicians,Existing Green N&E,4,2,24,0.200000,Manufacturing Production Technicians,0.200000,30.0,6.0,NaN,NaN,NaN,NaN,NaN
304,11-9041.00,Engineering Managers,Green Enhanced Skills,4,0,17,0.190476,Architectural and Engineering Managers,0.190476,21.0,4.0,NaN,NaN,NaN,NaN,NaN
315,19-4041.02,Geological Sample Test Technicians,Green Enhanced Skills,2,1,14,0.176471,Geological Sample Test Technicians,0.187500,16.0,3.0,NaN,NaN,NaN,NaN,NaN
317,17-3029.04,Electronics Engineering Technologists,Existing Green N&E,4,0,19,0.173913,Electronics Engineering Technologists,0.173913,23.0,4.0,NaN,NaN,NaN,NaN,NaN
318,17-3029.05,Industrial Engineering Technologists,Existing Green N&E,4,0,19,0.173913,Industrial Engineering Technologists,0.173913,23.0,4.0,NaN,NaN,NaN,NaN,NaN
322,17-3029.12,Nanotechnology Engineering Technicians,Existing Green N&E,3,0,16,0.157895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,11-9013.02,Farm and Ranch Managers,Green Enhanced Skills,3,1,24,0.142857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,49-9042.00,"Maintenance and Repair Workers, General",Green Enhanced Skills,4,0,25,0.137931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363,47-5041.00,Continuous Mining Machine Operators,Green Enhanced Skills,2,0,13,0.133333,Continuous Mining Machine Operators,0.166667,12.0,2.0,NaN,NaN,NaN,NaN,NaN
367,17-2199.05,Mechatronics Engineers,Existing Green N&E,3,0,20,0.130435,Mechatronics Engineers,0.130435,23.0,3.0,NaN,NaN,NaN,NaN,NaN
375,13-2099.03,Investment Underwriters,Existing Green N&E,2,0,15,0.117647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380,17-3024.01,Robotics Technicians,Existing Green N&E,2,0,17,0.105263,Robotics Technicians,0.086957,23.0,2.0,NaN,NaN,NaN,NaN,NaN
381,13-1073.00,Training and Development Specialists,Green Enhanced Skills,2,0,18,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,15-1099.06,Geospatial Information Scientists and Technolo...,Existing Green N&E,2,0,22,0.083333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,17-3024.00,Electro-Mechanical Technicians,Green Enhanced Skills,1,0,11,0.083333,Electro-Mechanical Technicians,0.083333,12.0,1.0,NaN,NaN,NaN,NaN,NaN
411,19-2099.01,Remote Sensing Scientists and Technologists,Existing Green N&E,2,0,22,0.083333,Remote Sensing Scientists and Technologists,0.083333,24.0,2.0,NaN,NaN,NaN,NaN,NaN

In [7]:
gt_esco.columns

Index(['onet_code', 'title_gtp', 'occupation_type', 'n_new_green_tasks_gtp',
       'n_existing_green_tasks_gtp', 'n_non_green_tasks_gtp',
       'share_green_gtp', 'title_vona2018', 'share_green_vona2018',
       'total_spec_tasks_vona2018', 'green_spec_tasks_vona2018', 'id',
       'concept_uri', 'preferred_label', 'isco_level_4', 'onet_occupation'],
      dtype='object')

Summary: number of ESCO occupations matched to a single greening ONET occupation

In [8]:
grouping_cols = ["onet_code", "title_gtp", "occupation_type", "share_green_gtp"]

match_summary = gt_esco.groupby(grouping_cols)["preferred_label"].count().sort_values(ascending=False)
match_summary.rename("n_matches_esco", inplace=True)

match_summary.to_csv(
    os.path.join(useful_paths.results_dir, "validation", "onet_esco_crosswalk", "onet_to_esco_match_summary.csv"),
    sep=";"
)

match_summary

onet_code   title_gtp                                                                                            occupation_type        share_green_gtp
13-1022.00  Wholesale and Retail Buyers, Except Farm Products                                                    Green Enhanced Skills  0.300000           41
17-2141.00  Mechanical Engineers                                                                                 Green Enhanced Skills  0.285714           36
51-9012.00  Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders  Green Enhanced Skills  0.047619           29
51-9061.00  Inspectors, Testers, Sorters, Samplers, and Weighers                                                 Green Enhanced Skills  0.062500           28
27-3022.00  Reporters and Correspondents                                                                         Green Enhanced Skills  0.035714           18
                                                                                                                                                           ..
17-2011.00  Aerospace Engineers                                                                                  Green Enhanced Skills  0.500000            0
15-1099.07  Geographic Information Systems Technicians                                                           Existing Green N&E     0.263158            0
15-1099.06  Geospatial Information Scientists and Technologists                                                  Existing Green N&E     0.083333            0
41-3099.01  Energy Brokers                                                                                       Existing Green N&E     1.000000            0
17-3029.04  Electronics Engineering Technologists                                                                Existing Green N&E     0.173913            0
Name: n_matches_esco, Length: 138, dtype: int64

In [9]:
missing_matches = match_summary[match_summary == 0].reset_index()
missing_matches

,onet_code,title_gtp,occupation_type,share_green_gtp,n_matches_esco
0,11-9199.11,Brownfield Redevelopment Specialists and Site ...,New Green N&E,1.000000,0
1,11-9199.10,Wind Energy Project Managers,New Green N&E,1.000000,0
2,11-9199.09,Wind Energy Operations Managers,New Green N&E,1.000000,0
3,49-9042.00,"Maintenance and Repair Workers, General",Green Enhanced Skills,0.137931,0
4,47-4099.01,Solar Photovoltaic Installers,New Green N&E,1.000000,0
5,47-4099.02,Solar Thermal Installers and Technicians,New Green N&E,1.000000,0
6,13-1073.00,Training and Development Specialists,Green Enhanced Skills,0.100000,0
7,13-1081.01,Logistics Engineers,Existing Green N&E,0.366667,0
8,47-5041.00,Continuous Mining Machine Operators,Green Enhanced Skills,0.133333,0
9,11-9121.02,Water Resource Specialists,New Green N&E,1.000000,0
10,11-9041.01,Biofuels/Biodiesel Technology and Product Deve...,New Green N&E,1.000000,0
11,11-9199.06,Logistics Managers,Existing Green N&E,0.300000,0
12,17-3029.03,Electromechanical Engineering Technologists,Existing Green N&E,0.333333,0
13,49-9099.01,Geothermal Technicians,New Green N&E,1.000000,0
14,49-9099.02,Wind Turbine Service Technicians,New Green N&E,1.000000,0
15,11-9041.00,Engineering Managers,Green Enhanced Skills,0.190476,0
16,11-9013.02,Farm and Ranch Managers,Green Enhanced Skills,0.142857,0
17,51-8011.00,Nuclear Power Reactor Operators,Green Enhanced Skills,0.300000,0
18,51-8099.01,Biofuels Processing Technicians,New Green N&E,1.000000,0
19,11-3051.06,Hydroelectric Production Managers,New Green N&E,1.000000,0
20,51-8099.03,Biomass Plant Technicians,New Green N&E,1.000000,0
21,11-3051.05,Methane/Landfill Gas Collection System Operators,New Green N&E,1.000000,0
22,11-3051.04,Biomass Production Managers,New Green N&E,1.000000,0
23,11-3051.03,Biofuels Production Managers,New Green N&E,1.000000,0
24,11-3051.02,Geothermal Production Managers,New Green N&E,1.000000,0
25,53-1021.01,Recycling Coordinators,New Green N&E,1.000000,0
26,11-2011.01,Green Marketers,New Green N&E,1.000000,0
27,53-6051.07,"Transportation Vehicle, Equipment and Systems ...",Green Enhanced Skills,0.428571,0
28,47-1011.03,Solar Energy Installation Managers,New Green N&E,1.000000,0
29,13-2099.01,Financial Quantitative Analysts,Existing Green N&E,0.238095,0
30,17-3029.02,Electrical Engineering Technologists,Existing Green N&E,0.421053,0
31,19-2099.01,Remote Sensing Scientists and Technologists,Existing Green N&E,0.083333,0
32,17-3029.05,Industrial Engineering Technologists,Existing Green N&E,0.173913,0
33,17-3027.01,Automotive Engineering Technicians,Existing Green N&E,0.277778,0
34,17-3024.01,Robotics Technicians,Existing Green N&E,0.105263,0
35,17-3024.00,Electro-Mechanical Technicians,Green Enhanced Skills,0.083333,0
36,17-3029.09,Manufacturing Production Technicians,Existing Green N&E,0.200000,0
37,17-3029.10,Fuel Cell Technicians,Existing Green N&E,1.000000,0
38,17-3029.11,Nanotechnology Engineering Technologists,Existing Green N&E,0.352941,0
39,17-3029.12,Nanotechnology Engineering Technicians,Existing Green N&E,0.157895,0
40,19-1031.01,Soil and Water Conservationists,Green Enhanced Skills,1.000000,0
41,17-2199.11,Solar Energy Systems Engineers,New Green N&E,1.000000,0
42,19-2041.01,Climate Change Analysts,New Green N&E,1.000000,0
43,19-2041.02,Environmental Restoration Planners,New Green N&E,1.000000,0
44,17-2199.10,Wind Energy Engineers,New Green N&E,1.000000,0
45,17-2199.09,Nanosystems Engineers,Existing Green N&E,0.360000,0
46,19-3011.01,Environmental Economists,New Green N&E,1.000000,0
47,13-2099.03,Investment Underwriters,Existing Green N&E,0.117647,0
48,17-2199.06,Microsystems Engineers,Existing Green N&E,0.200000,0
49,17-2199.05,Mechatronics Engineers,Existing Green N&E,0.130435,0
50,17-2161.00,Nuclear Engineers,Green Enhanced Skills,0.368421,0
51,19-4041.02,Geological Sample Test Technicians,Green Enhanced Skills,0.176471,0
52,19-4051.01,Nuclear Equipment Operation Technicians,Green Enhanced Skills,0.400000,0
53,17-2141.02,Automotive Engineers,Existing Green N&E,0.320000,0
54,19-4099.02,Precision Agriculture Technicians,Existing Green N&E,0.318182,0
55,17-2141.01,Fuel Cell Engineers,Existing Green N&E,1.000000,0
56,17-2081.01,Water/Wastewater Engineers,New Green N&E,1.000000,0
57,17-2051.01,Transportation Engineers,Existing Green N&E,0.250000,0
58,17-2011.00,Aerospace Engineers,Green Enhanced Skills,0.500000,0
59,15-1099.07,Geographic Information Systems Technicians,Existing Green N&E,0.263158,0
60,15-1099.06,Geospatial Information Scientists and Technolo...,Existing Green N&E,0.083333,0
61,41-3099.01,Energy Brokers,Existing Green N&E,1.000000,0
62,17-3029.04,Electronics Engineering Technologists,Existing Green N&E,0.173913,0

63 occupations are completely missing any match to ESCO occupations. What is going on there?

In [10]:
missing_matches.shape

(63, 5)

Inspecting the crosswalk I used for the thesis

In [11]:
cw = crosswalks.onet_esco_mcc_full
cw

,id,concept_uri,preferred_label,isco_level_4,onet_code,onet_occupation,onet_code_6d
0,0,http://data.europa.eu/esco/occupation/00030d09...,technical director,2166,27-1011.00,art directors,27-1011
1,1,http://data.europa.eu/esco/occupation/000e93a3...,metal drawing machine operator,8121,51-4021.00,"extruding and drawing machine setters, operato...",51-4021
2,2,http://data.europa.eu/esco/occupation/0019b951...,precision device inspector,7543,51-9061.00,"inspectors, testers, sorters, samplers, and we...",51-9061
3,3,http://data.europa.eu/esco/occupation/0022f466...,air traffic safety technician,3155,17-3023.01,electronics engineering technicians,17-3023
4,4,http://data.europa.eu/esco/occupation/002da35b...,hospitality revenue manager,2431,13-1161.00,market research analysts and marketing special...,13-1161
...,...,...,...,...,...,...,...
2937,2937,http://data.europa.eu/esco/occupation/ff656b3a...,demographer,2120,15-2041.00,statisticians,15-2041
2938,2938,http://data.europa.eu/esco/occupation/ff8d4065...,sorter labourer,9612,51-9199.01,recycling and reclamation workers,51-9199
2939,2939,http://data.europa.eu/esco/occupation/ffa4dd5d...,armoured car guard,5414,33-9032.00,security guards,33-9032
2940,2940,http://data.europa.eu/esco/occupation/ffade2f4...,civil service administrative officer,2422,11-3011.00,administrative services managers,11-3011
2941,2941,http://data.europa.eu/esco/occupation/ffc292f1...,motor vehicle assembler,8211,51-2031.00,engine and other machine assemblers,51-2031

2942 ESCO occupations are matched to 669 ONET occupations

In [12]:
cw.onet_code.unique().shape

(669,)

None of these 63 onet occupations is part of this crosswalk

In [13]:
for code, label in zip(missing_matches.onet_code, missing_matches.title_gtp):
    match_original_code = code in cw.onet_code.values
    print("{} ¦ {} ¦ {}".format(code, label, match_original_code))

11-9199.11 ¦ Brownfield Redevelopment Specialists and Site Managers ¦ False
11-9199.10 ¦ Wind Energy Project Managers ¦ False
11-9199.09 ¦ Wind Energy Operations Managers ¦ False
49-9042.00 ¦ Maintenance and Repair Workers, General ¦ False
47-4099.01 ¦ Solar Photovoltaic Installers ¦ False
47-4099.02 ¦ Solar Thermal Installers and Technicians ¦ False
13-1073.00 ¦ Training and Development Specialists ¦ False
13-1081.01 ¦ Logistics Engineers ¦ False
47-5041.00 ¦ Continuous Mining Machine Operators ¦ False
11-9121.02 ¦ Water Resource Specialists ¦ False
11-9041.01 ¦ Biofuels/Biodiesel Technology and Product Development Managers ¦ False
11-9199.06 ¦ Logistics Managers ¦ False
17-3029.03 ¦ Electromechanical Engineering Technologists ¦ False
49-9099.01 ¦ Geothermal Technicians ¦ False
49-9099.02 ¦ Wind Turbine Service Technicians ¦ False
11-9041.00 ¦ Engineering Managers ¦ False
11-9013.02 ¦ Farm and Ranch Managers ¦ False
51-8011.00 ¦ Nuclear Power Reactor Operators ¦ False
51-8099.01 ¦ Biofuels Processing Technicians ¦ False
11-3051.06 ¦ Hydroelectric Production Managers ¦ False
51-8099.03 ¦ Biomass Plant Technicians ¦ False
11-3051.05 ¦ Methane/Landfill Gas Collection System Operators ¦ False
11-3051.04 ¦ Biomass Production Managers ¦ False
11-3051.03 ¦ Biofuels Production Managers ¦ False
11-3051.02 ¦ Geothermal Production Managers ¦ False
53-1021.01 ¦ Recycling Coordinators ¦ False
11-2011.01 ¦ Green Marketers ¦ False
53-6051.07 ¦ Transportation Vehicle, Equipment and Systems Inspectors, Except Aviation ¦ False
47-1011.03 ¦ Solar Energy Installation Managers ¦ False
13-2099.01 ¦ Financial Quantitative Analysts ¦ False
17-3029.02 ¦ Electrical Engineering Technologists ¦ False
19-2099.01 ¦ Remote Sensing Scientists and Technologists ¦ False
17-3029.05 ¦ Industrial Engineering Technologists ¦ False
17-3027.01 ¦ Automotive Engineering Technicians ¦ False
17-3024.01 ¦ Robotics Technicians ¦ False
17-3024.00 ¦ Electro-Mechanical Technicians ¦ False
17-3029.09 ¦ Manufacturing Production Technicians ¦ False
17-3029.10 ¦ Fuel Cell Technicians ¦ False
17-3029.11 ¦ Nanotechnology Engineering Technologists ¦ False
17-3029.12 ¦ Nanotechnology Engineering Technicians ¦ False
19-1031.01 ¦ Soil and Water Conservationists ¦ False
17-2199.11 ¦ Solar Energy Systems Engineers ¦ False
19-2041.01 ¦ Climate Change Analysts ¦ False
19-2041.02 ¦ Environmental Restoration Planners ¦ False
17-2199.10 ¦ Wind Energy Engineers ¦ False
17-2199.09 ¦ Nanosystems Engineers ¦ False
19-3011.01 ¦ Environmental Economists ¦ False
13-2099.03 ¦ Investment Underwriters ¦ False
17-2199.06 ¦ Microsystems Engineers ¦ False
17-2199.05 ¦ Mechatronics Engineers ¦ False
17-2161.00 ¦ Nuclear Engineers ¦ False
19-4041.02 ¦ Geological Sample Test Technicians ¦ False
19-4051.01 ¦ Nuclear Equipment Operation Technicians ¦ False
17-2141.02 ¦ Automotive Engineers ¦ False
19-4099.02 ¦ Precision Agriculture Technicians ¦ False
17-2141.01 ¦ Fuel Cell Engineers ¦ False
17-2081.01 ¦ Water/Wastewater Engineers ¦ False
17-2051.01 ¦ Transportation Engineers ¦ False
17-2011.00 ¦ Aerospace Engineers ¦ False
15-1099.07 ¦ Geographic Information Systems Technicians ¦ False
15-1099.06 ¦ Geospatial Information Scientists and Technologists ¦ False
41-3099.01 ¦ Energy Brokers ¦ False
17-3029.04 ¦ Electronics Engineering Technologists ¦ False

#### Option 1: assign value to coarser SOC level and check if there is a match

In [14]:
cw.query("onet_code == '51-4021.00'")
cw_unique_onet = cw.drop_duplicates(subset="onet_code")

sel = cw_unique_onet.onet_code == "11-9199.00"
cw_unique_onet.loc[sel, 'onet_occupation'].values.tolist()[0]

'managers, all other'

In [15]:
summary_dict = {
    "onet_code_orig": [],
    "onet_label_orig": [],
    "onet_match_orig": [],
    "onet_code_1_below": [],
    "onet_label_1_below": [],
    "onet_match_1_below": [],
    "onet_code_2_below": [],
    "onet_label_2_below": [],
    "onet_match_2_below": []
}

for code_orig, label_orig in zip(missing_matches.onet_code, missing_matches.title_gtp):
    # coarser onet soc codes
    onet_code_1_below = code_orig[:-1] + "0"
    onet_code_2_below = code_orig[:-2] + "00"

    # original match with cw?
    match_orig = code_orig in cw_unique_onet.onet_code.values

    # if not, check one level below if not
    if match_orig is False:

        onet_match_1_below = onet_code_1_below in cw_unique_onet.onet_code.values
        if onet_match_1_below:
            sel = cw_unique_onet.onet_code == onet_code_1_below
            onet_label_1_below = cw_unique_onet.loc[sel, 'onet_occupation'].values.tolist()[0]

            onet_code_2_below = False
            onet_label_2_below = False
            onet_match_2_below = False
        else:
            onet_label_1_below = None

            # check if there is a match two levels below
            onet_match_2_below = onet_code_2_below in cw_unique_onet.onet_code.values
            if onet_match_2_below:
                sel_2 = cw_unique_onet.onet_code == onet_code_2_below
                onet_label_2_below = cw_unique_onet.loc[sel_2, 'onet_occupation'].values.tolist()[0]
                pass

    else:
        onet_match_1_below = None
        onet_label_1_below = None

    # update dict
    summary_dict["onet_code_orig"].append(code_orig)
    summary_dict["onet_label_orig"].append(label_orig)
    summary_dict["onet_match_orig"].append(match_orig)

    summary_dict["onet_code_1_below"].append(onet_code_1_below)
    summary_dict["onet_label_1_below"].append(onet_label_1_below)
    summary_dict["onet_match_1_below"].append(onet_match_1_below)

    summary_dict["onet_code_2_below"].append(onet_code_2_below)
    summary_dict["onet_label_2_below"].append(onet_label_2_below)
    summary_dict["onet_match_2_below"].append(onet_match_2_below)


df_cw_coarsening_summary = pd.DataFrame.from_dict(summary_dict)

df_cw_coarsening_summary

,onet_code_orig,onet_label_orig,onet_match_orig,onet_code_1_below,onet_label_1_below,onet_match_1_below,onet_code_2_below,onet_label_2_below,onet_match_2_below
0,11-9199.11,Brownfield Redevelopment Specialists and Site ...,False,11-9199.10,None,False,11-9199.00,"managers, all other",True
1,11-9199.10,Wind Energy Project Managers,False,11-9199.10,None,False,11-9199.00,"managers, all other",True
2,11-9199.09,Wind Energy Operations Managers,False,11-9199.00,"managers, all other",True,False,False,False
3,49-9042.00,"Maintenance and Repair Workers, General",False,49-9042.00,None,False,49-9042.00,False,False
4,47-4099.01,Solar Photovoltaic Installers,False,47-4099.00,None,False,47-4099.00,False,False
5,47-4099.02,Solar Thermal Installers and Technicians,False,47-4099.00,None,False,47-4099.00,False,False
6,13-1073.00,Training and Development Specialists,False,13-1073.00,None,False,13-1073.00,False,False
7,13-1081.01,Logistics Engineers,False,13-1081.00,None,False,13-1081.00,False,False
8,47-5041.00,Continuous Mining Machine Operators,False,47-5041.00,None,False,47-5041.00,False,False
9,11-9121.02,Water Resource Specialists,False,11-9121.00,natural sciences managers,True,False,False,False
10,11-9041.01,Biofuels/Biodiesel Technology and Product Deve...,False,11-9041.00,None,False,11-9041.00,False,False
11,11-9199.06,Logistics Managers,False,11-9199.00,"managers, all other",True,False,False,False
12,17-3029.03,Electromechanical Engineering Technologists,False,17-3029.00,None,False,17-3029.00,False,False
13,49-9099.01,Geothermal Technicians,False,49-9099.00,None,False,49-9099.00,False,False
14,49-9099.02,Wind Turbine Service Technicians,False,49-9099.00,None,False,49-9099.00,False,False
15,11-9041.00,Engineering Managers,False,11-9041.00,None,False,11-9041.00,False,False
16,11-9013.02,Farm and Ranch Managers,False,11-9013.00,None,False,11-9013.00,False,False
17,51-8011.00,Nuclear Power Reactor Operators,False,51-8011.00,None,False,51-8011.00,False,False
18,51-8099.01,Biofuels Processing Technicians,False,51-8099.00,None,False,51-8099.00,False,False
19,11-3051.06,Hydroelectric Production Managers,False,11-3051.00,industrial production managers,True,False,False,False
20,51-8099.03,Biomass Plant Technicians,False,51-8099.00,None,False,51-8099.00,False,False
21,11-3051.05,Methane/Landfill Gas Collection System Operators,False,11-3051.00,industrial production managers,True,False,False,False
22,11-3051.04,Biomass Production Managers,False,11-3051.00,industrial production managers,True,False,False,False
23,11-3051.03,Biofuels Production Managers,False,11-3051.00,industrial production managers,True,False,False,False
24,11-3051.02,Geothermal Production Managers,False,11-3051.00,industrial production managers,True,False,False,False
25,53-1021.01,Recycling Coordinators,False,53-1021.00,"first-line supervisors of helpers, laborers, a...",True,False,False,False
26,11-2011.01,Green Marketers,False,11-2011.00,None,False,11-2011.00,False,False
27,53-6051.07,"Transportation Vehicle, Equipment and Systems ...",False,53-6051.00,transportation inspectors,True,False,False,False
28,47-1011.03,Solar Energy Installation Managers,False,47-1011.00,first-line supervisors of construction trades ...,True,False,False,False
29,13-2099.01,Financial Quantitative Analysts,False,13-2099.00,None,False,13-2099.00,False,False
30,17-3029.02,Electrical Engineering Technologists,False,17-3029.00,None,False,17-3029.00,False,False
31,19-2099.01,Remote Sensing Scientists and Technologists,False,19-2099.00,None,False,19-2099.00,False,False
32,17-3029.05,Industrial Engineering Technologists,False,17-3029.00,None,False,17-3029.00,False,False
33,17-3027.01,Automotive Engineering Technicians,False,17-3027.00,mechanical engineering technicians,True,False,False,False
34,17-3024.01,Robotics Technicians,False,17-3024.00,None,False,17-3024.00,False,False
35,17-3024.00,Electro-Mechanical Technicians,False,17-3024.00,None,False,17-3024.00,False,False
36,17-3029.09,Manufacturing Production Technicians,False,17-3029.00,None,False,17-3029.00,False,False
37,17-3029.10,Fuel Cell Technicians,False,17-3029.10,None,False,17-3029.00,False,False
38,17-3029.11,Nanotechnology Engineering Technologists,False,17-3029.10,None,False,17-3029.00,False,False
39,17-3029.12,Nanotechnology Engineering Technicians,False,17-3029.10,None,False,17-3029.00,False,False
40,19-1031.01,Soil and Water Conservationists,False,19-1031.00,conservation scientists,True,False,False,False
41,17-2199.11,Solar Energy Systems Engineers,False,17-2199.10,None,False,17-2199.00,False,False
42,19-2041.01,Climate Change Analysts,False,19-2041.00,"environmental scientists and specialists, incl...",True,False,False,False
43,19-2041.02,Environmental Restoration Planners,False,19-2041.00,"environmental scientists and specialists, incl...",True,False,False,False
44,17-2199.10,Wind Energy Engineers,False,17-2199.10,None,False,17-2199.00,False,False
45,17-2199.09,Nanosystems Engineers,False,17-2199.00,None,False,17-2199.00,False,False
46,19-3011.01,Environmental Economists,False,19-3011.00,economists,True,False,False,False
47,13-2099.03,Investment Underwriters,False,13-2099.00,None,False,13-2099.00,False,False
48,17-2199.06,Microsystems Engineers,False,17-2199.00,None,False,17-2199.00,False,False
49,17-2199.05,Mechatronics Engineers,False,17-2199.00,None,False,17-2199.00,False,False
50,17-2161.00,Nuclear Engineers,False,17-2161.00,None,False,17-2161.00,False,False
51,19-4041.02,Geological Sample Test Technicians,False,19-4041.00,None,False,19-4041.00,False,False
52,19-4051.01,Nuclear Equipment Operation Technicians,False,19-4051.00,nuclear technicians,True,False,False,False
53,17-2141.02,Automotive Engineers,False,17-2141.00,mechanical engineers,True,False,False,False
54,19-4099.02,Precision Agriculture Technicians,False,19-4099.00,"life, physical, and social science technicians...",True,False,False,False
55,17-2141.01,Fuel Cell Engineers,False,17-2141.00,mechanical engineers,True,False,False,False
56,17-2081.01,Water/Wastewater Engineers,False,17-2081.00,environmental engineers,True,False,False,False
57,17-2051.01,Transportation Engineers,False,17-2051.00,civil engineers,True,False,False,False
58,17-2011.00,Aerospace Engineers,False,17-2011.00,None,False,17-2011.00,False,False
59,15-1099.07,Geographic Information Systems Technicians,False,15-1099.00,None,False,15-1099.00,False,False
60,15-1099.06,Geospatial Information Scientists and Technolo...,False,15-1099.00,None,False,15-1099.00,False,False
61,41-3099.01,Energy Brokers,False,41-3099.00,None,False,41-3099.00,False,False
62,17-3029.04,Electronics Engineering Technologists,False,17-3029.00,None,False,17-3029.00,False,False

Results of downwalking
- 24 additional matches through downwalking to SOC 6D level
- 22 additional matches one level below (SOC 7D), 2 matches two levels below (SOC 8D)

In [16]:
df_cw_coarsening_summary.onet_match_1_below.sum()

22

In [17]:
df_cw_coarsening_summary.onet_match_2_below.sum()

2

#### Option 2: use reduced crosswalk at ESCO LVL 5
Idea
- use reduced crosswalk file used in MCC report that matches at the ESCO lvl 5.
- Assign same membership to all lower-level children.

Conclusion
- no additional matches are found, the crosswalk would need to be reconstructed.

In [18]:
esco5_onet_cw = crosswalks.onet_esco_mcc_reduced
esco5_onet_cw.concept_uri.unique()

array(['http://data.europa.eu/esco/occupation/0ee67d5e-8de9-48f0-97c5-ba23d486b1e9',
       'http://data.europa.eu/esco/occupation/404a50e9-61ce-448d-a695-bbfc697a0727',
       'http://data.europa.eu/esco/occupation/5bca96fd-4203-400b-be58-9e9b50bc98da',
       ...,
       'http://data.europa.eu/esco/occupation/c28cb56b-003e-499a-8dbf-b654864e7867',
       'http://data.europa.eu/esco/occupation/e16e4cb0-6f7d-4bf9-8f90-d1d866ad229b',
       'http://data.europa.eu/esco/occupation/e31c83ac-cb74-4936-88f1-90ed0997b29b'],
      dtype=object)

In [19]:
matches =  []
for code_orig, label_orig in zip(missing_matches.onet_code, missing_matches.title_gtp):
    match = esco5_onet_cw.loc[esco5_onet_cw.loc[:, "onet_code"] == code_orig]
    matches.append(not match.empty)
    print(code_orig, "¦", label_orig, "¦", not match.empty)

11-9199.11 ¦ Brownfield Redevelopment Specialists and Site Managers ¦ False
11-9199.10 ¦ Wind Energy Project Managers ¦ False
11-9199.09 ¦ Wind Energy Operations Managers ¦ False
49-9042.00 ¦ Maintenance and Repair Workers, General ¦ False
47-4099.01 ¦ Solar Photovoltaic Installers ¦ False
47-4099.02 ¦ Solar Thermal Installers and Technicians ¦ False
13-1073.00 ¦ Training and Development Specialists ¦ False
13-1081.01 ¦ Logistics Engineers ¦ False
47-5041.00 ¦ Continuous Mining Machine Operators ¦ False
11-9121.02 ¦ Water Resource Specialists ¦ False
11-9041.01 ¦ Biofuels/Biodiesel Technology and Product Development Managers ¦ False
11-9199.06 ¦ Logistics Managers ¦ False
17-3029.03 ¦ Electromechanical Engineering Technologists ¦ False
49-9099.01 ¦ Geothermal Technicians ¦ False
49-9099.02 ¦ Wind Turbine Service Technicians ¦ False
11-9041.00 ¦ Engineering Managers ¦ False
11-9013.02 ¦ Farm and Ranch Managers ¦ False
51-8011.00 ¦ Nuclear Power Reactor Operators ¦ False
51-8099.01 ¦ Biofuels Processing Technicians ¦ False
11-3051.06 ¦ Hydroelectric Production Managers ¦ False
51-8099.03 ¦ Biomass Plant Technicians ¦ False
11-3051.05 ¦ Methane/Landfill Gas Collection System Operators ¦ False
11-3051.04 ¦ Biomass Production Managers ¦ False
11-3051.03 ¦ Biofuels Production Managers ¦ False
11-3051.02 ¦ Geothermal Production Managers ¦ False
53-1021.01 ¦ Recycling Coordinators ¦ False
11-2011.01 ¦ Green Marketers ¦ False
53-6051.07 ¦ Transportation Vehicle, Equipment and Systems Inspectors, Except Aviation ¦ False
47-1011.03 ¦ Solar Energy Installation Managers ¦ False
13-2099.01 ¦ Financial Quantitative Analysts ¦ False
17-3029.02 ¦ Electrical Engineering Technologists ¦ False
19-2099.01 ¦ Remote Sensing Scientists and Technologists ¦ False
17-3029.05 ¦ Industrial Engineering Technologists ¦ False
17-3027.01 ¦ Automotive Engineering Technicians ¦ False
17-3024.01 ¦ Robotics Technicians ¦ False
17-3024.00 ¦ Electro-Mechanical Technicians ¦ False
17-3029.09 ¦ Manufacturing Production Technicians ¦ False
17-3029.10 ¦ Fuel Cell Technicians ¦ False
17-3029.11 ¦ Nanotechnology Engineering Technologists ¦ False
17-3029.12 ¦ Nanotechnology Engineering Technicians ¦ False
19-1031.01 ¦ Soil and Water Conservationists ¦ False
17-2199.11 ¦ Solar Energy Systems Engineers ¦ False
19-2041.01 ¦ Climate Change Analysts ¦ False
19-2041.02 ¦ Environmental Restoration Planners ¦ False
17-2199.10 ¦ Wind Energy Engineers ¦ False
17-2199.09 ¦ Nanosystems Engineers ¦ False
19-3011.01 ¦ Environmental Economists ¦ False
13-2099.03 ¦ Investment Underwriters ¦ False
17-2199.06 ¦ Microsystems Engineers ¦ False
17-2199.05 ¦ Mechatronics Engineers ¦ False
17-2161.00 ¦ Nuclear Engineers ¦ False
19-4041.02 ¦ Geological Sample Test Technicians ¦ False
19-4051.01 ¦ Nuclear Equipment Operation Technicians ¦ False
17-2141.02 ¦ Automotive Engineers ¦ False
19-4099.02 ¦ Precision Agriculture Technicians ¦ False
17-2141.01 ¦ Fuel Cell Engineers ¦ False
17-2081.01 ¦ Water/Wastewater Engineers ¦ False
17-2051.01 ¦ Transportation Engineers ¦ False
17-2011.00 ¦ Aerospace Engineers ¦ False
15-1099.07 ¦ Geographic Information Systems Technicians ¦ False
15-1099.06 ¦ Geospatial Information Scientists and Technologists ¦ False
41-3099.01 ¦ Energy Brokers ¦ False
17-3029.04 ¦ Electronics Engineering Technologists ¦ False

In [20]:
np.array(matches).sum()

0

#### Option 3: use ONET-SOC and SOC-ISCO crosswalks from MCC project (for LFS data only)

Idea:
- don't go via ESCO but directly match the GTP data to ISCO occupations

Conclusions:
- 56/63 occupations can be matched in this way.
- Not attaching to ESCO, however, will make us loose a lot of information when working with the national (DE/IT) data.

In [21]:
crosswalks.soc10_isco08_ibs

       soc10  isco08
0     111011    1112
1     111011    1113
2     111011    1120
3     111021    1112
4     111021    1114
...      ...     ...
1126  553015     310
1127  553016     310
1128  553017     310
1129  553018     310
1130  553019     310

[1131 rows x 2 columns]

In [22]:
onet_us2010soc = crosswalks.onet_soc10
onet_us2010soc

,O*NET-SOC 2010 Code,O*NET-SOC 2010 Title,2010 SOC Code,2010 SOC Title
0,11-1011.00,Chief Executives,11-1011,Chief Executives
1,11-1011.03,Chief Sustainability Officers,11-1011,Chief Executives
2,11-1021.00,General and Operations Managers,11-1021,General and Operations Managers
3,11-1031.00,Legislators,11-1031,Legislators
4,11-2011.00,Advertising and Promotions Managers,11-2011,Advertising and Promotions Managers
...,...,...,...,...
1105,55-3015.00,Command and Control Center Specialists,55-3015,Command and Control Center Specialists
1106,55-3016.00,Infantry,55-3016,Infantry
1107,55-3017.00,Radar and Sonar Technicians,55-3017,Radar and Sonar Technicians
1108,55-3018.00,Special Forces,55-3018,Special Forces
1109,55-3019.00,Military Enlisted Tactical Operations and Air/...,55-3019,Military Enlisted Tactical Operations and Air/...

In [23]:
onet_us2010soc.iloc[:, 2].unique()

array(['11-1011', '11-1021', '11-1031', '11-2011', '11-2021', '11-2022',
       '11-2031', '11-3011', '11-3021', '11-3031', '11-3051', '11-3061',
       '11-3071', '11-3111', '11-3121', '11-3131', '11-9013', '11-9021',
       '11-9031', '11-9032', '11-9033', '11-9039', '11-9041', '11-9051',
       '11-9061', '11-9071', '11-9081', '11-9111', '11-9121', '11-9131',
       '11-9141', '11-9151', '11-9161', '11-9199', '13-1011', '13-1021',
       '13-1022', '13-1023', '13-1031', '13-1032', '13-1041', '13-1051',
       '13-1071', '13-1074', '13-1075', '13-1081', '13-1111', '13-1121',
       '13-1131', '13-1141', '13-1151', '13-1161', '13-1199', '13-2011',
       '13-2021', '13-2031', '13-2041', '13-2051', '13-2052', '13-2053',
       '13-2061', '13-2071', '13-2072', '13-2081', '13-2082', '13-2099',
       '15-1111', '15-1121', '15-1122', '15-1131', '15-1132', '15-1133',
       '15-1134', '15-1141', '15-1142', '15-1143', '15-1151', '15-1152',
       '15-1199', '15-2011', '15-2021', '15-2031', '15-2041', '15-2091',
       '15-2099', '17-1011', '17-1012', '17-1021', '17-1022', '17-2011',
       '17-2021', '17-2031', '17-2041', '17-2051', '17-2061', '17-2071',
       '17-2072', '17-2081', '17-2111', '17-2112', '17-2121', '17-2131',
       '17-2141', '17-2151', '17-2161', '17-2171', '17-2199', '17-3011',
       '17-3012', '17-3013', '17-3019', '17-3021', '17-3022', '17-3023',
       '17-3024', '17-3025', '17-3026', '17-3027', '17-3029', '17-3031',
       '19-1011', '19-1012', '19-1013', '19-1020', '19-1021', '19-1022',
       '19-1023', '19-1029', '19-1031', '19-1032', '19-1041', '19-1042',
       '19-1099', '19-2011', '19-2012', '19-2021', '19-2031', '19-2032',
       '19-2041', '19-2042', '19-2043', '19-2099', '19-3011', '19-3022',
       '19-3031', '19-3032', '19-3039', '19-3041', '19-3051', '19-3091',
       '19-3092', '19-3093', '19-3094', '19-3099', '19-4011', '19-4021',
       '19-4031', '19-4041', '19-4051', '19-4061', '19-4091', '19-4092',
       '19-4093', '19-4099', '21-1011', '21-1012', '21-1013', '21-1014',
       '21-1015', '21-1019', '21-1021', '21-1022', '21-1023', '21-1029',
       '21-1091', '21-1092', '21-1093', '21-1094', '21-1099', '21-2011',
       '21-2021', '21-2099', '23-1011', '23-1012', '23-1021', '23-1022',
       '23-1023', '23-2011', '23-2091', '23-2093', '23-2099', '25-1011',
       '25-1021', '25-1022', '25-1031', '25-1032', '25-1041', '25-1042',
       '25-1043', '25-1051', '25-1052', '25-1053', '25-1054', '25-1061',
       '25-1062', '25-1063', '25-1064', '25-1065', '25-1066', '25-1067',
       '25-1069', '25-1071', '25-1072', '25-1081', '25-1082', '25-1111',
       '25-1112', '25-1113', '25-1121', '25-1122', '25-1123', '25-1124',
       '25-1125', '25-1126', '25-1191', '25-1192', '25-1193', '25-1194',
       '25-1199', '25-2011', '25-2012', '25-2021', '25-2022', '25-2023',
       '25-2031', '25-2032', '25-2051', '25-2052', '25-2053', '25-2054',
       '25-2059', '25-3011', '25-3021', '25-3099', '25-4011', '25-4012',
       '25-4013', '25-4021', '25-4031', '25-9011', '25-9021', '25-9031',
       '25-9041', '25-9099', '27-1011', '27-1012', '27-1013', '27-1014',
       '27-1019', '27-1021', '27-1022', '27-1023', '27-1024', '27-1025',
       '27-1026', '27-1027', '27-1029', '27-2011', '27-2012', '27-2021',
       '27-2022', '27-2023', '27-2031', '27-2032', '27-2041', '27-2042',
       '27-2099', '27-3011', '27-3012', '27-3021', '27-3022', '27-3031',
       '27-3041', '27-3042', '27-3043', '27-3091', '27-3099', '27-4011',
       '27-4012', '27-4013', '27-4014', '27-4021', '27-4031', '27-4032',
       '27-4099', '29-1011', '29-1021', '29-1022', '29-1023', '29-1024',
       '29-1029', '29-1031', '29-1041', '29-1051', '29-1061', '29-1062',
       '29-1063', '29-1064', '29-1065', '29-1066', '29-1067', '29-1069',
       '29-1071', '29-1081', '29-1122', '29-1123', '29-1124', '29-1125',
       '29-1126', '29-1127', '29-1128', '29-1129', '29-1131', '29-1141',
       '29-1151', '29-1161', '29-1171', '29-1181', '29-1199', '29-2011',
       '29-2012', '29-2021', '29-2031', '29-2032', '29-2033', '29-2034',
       '29-2035', '29-2041', '29-2051', '29-2052', '29-2053', '29-2054',
       '29-2055', '29-2056', '29-2057', '29-2061', '29-2071', '29-2081',
       '29-2091', '29-2092', '29-2099', '29-9011', '29-9012', '29-9091',
       '29-9092', '29-9099', '31-1011', '31-1013', '31-1014', '31-1015',
       '31-2011', '31-2012', '31-2021', '31-2022', '31-9011', '31-9091',
       '31-9092', '31-9093', '31-9094', '31-9095', '31-9096', '31-9097',
       '31-9099', '33-1011', '33-1012', '33-1021', '33-1099', '33-2011',
       '33-2021', '33-2022', '33-3011', '33-3012', '33-3021', '33-3031',
       '33-3041', '33-3051', '33-3052', '33-9011', '33-9021', '33-9031',
       '33-9032', '33-9091', '33-9092', '33-9093', '33-9099', '35-1011',
       '35-1012', '35-2011', '35-2012', '35-2013', '35-2014', '35-2015',
       '35-2019', '35-2021', '35-3011', '35-3021', '35-3022', '35-3031',
       '35-3041', '35-9011', '35-9021', '35-9031', '35-9099', '37-1011',
       '37-1012', '37-2011', '37-2012', '37-2019', '37-2021', '37-3011',
       '37-3012', '37-3013', '37-3019', '39-1011', '39-1012', '39-1021',
       '39-2011', '39-2021', '39-3011', '39-3012', '39-3019', '39-3021',
       '39-3031', '39-3091', '39-3092', '39-3093', '39-3099', '39-4011',
       '39-4021', '39-4031', '39-5011', '39-5012', '39-5091', '39-5092',
       '39-5093', '39-5094', '39-6011', '39-6012', '39-7011', '39-7012',
       '39-9011', '39-9021', '39-9031', '39-9032', '39-9041', '39-9099',
       '41-1011', '41-1012', '41-2011', '41-2012', '41-2021', '41-2022',
       '41-2031', '41-3011', '41-3021', '41-3031', '41-3041', '41-3099',
       '41-4011', '41-4012', '41-9011', '41-9012', '41-9021', '41-9022',
       '41-9031', '41-9041', '41-9091', '41-9099', '43-1011', '43-2011',
       '43-2021', '43-2099', '43-3011', '43-3021', '43-3031', '43-3041',
       '43-3051', '43-3061', '43-3071', '43-3099', '43-4011', '43-4021',
       '43-4031', '43-4041', '43-4051', '43-4061', '43-4071', '43-4081',
       '43-4111', '43-4121', '43-4131', '43-4141', '43-4151', '43-4161',
       '43-4171', '43-4181', '43-4199', '43-5011', '43-5021', '43-5031',
       '43-5032', '43-5041', '43-5051', '43-5052', '43-5053', '43-5061',
       '43-5071', '43-5081', '43-5111', '43-6011', '43-6012', '43-6013',
       '43-6014', '43-9011', '43-9021', '43-9022', '43-9031', '43-9041',
       '43-9051', '43-9061', '43-9071', '43-9081', '43-9111', '43-9199',
       '45-1011', '45-2011', '45-2021', '45-2041', '45-2091', '45-2092',
       '45-2093', '45-2099', '45-3011', '45-3021', '45-4011', '45-4021',
       '45-4022', '45-4023', '45-4029', '47-1011', '47-2011', '47-2021',
       '47-2022', '47-2031', '47-2041', '47-2042', '47-2043', '47-2044',
       '47-2051', '47-2053', '47-2061', '47-2071', '47-2072', '47-2073',
       '47-2081', '47-2082', '47-2111', '47-2121', '47-2131', '47-2132',
       '47-2141', '47-2142', '47-2151', '47-2152', '47-2161', '47-2171',
       '47-2181', '47-2211', '47-2221', '47-2231', '47-3011', '47-3012',
       '47-3013', '47-3014', '47-3015', '47-3016', '47-3019', '47-4011',
       '47-4021', '47-4031', '47-4041', '47-4051', '47-4061', '47-4071',
       '47-4091', '47-4099', '47-5011', '47-5012', '47-5013', '47-5021',
       '47-5031', '47-5041', '47-5042', '47-5049', '47-5051', '47-5061',
       '47-5071', '47-5081', '47-5099', '49-1011', '49-2011', '49-2021',
       '49-2022', '49-2091', '49-2092', '49-2093', '49-2094', '49-2095',
       '49-2096', '49-2097', '49-2098', '49-3011', '49-3021', '49-3022',
       '49-3023', '49-3031', '49-3041', '49-3042', '49-3043', '49-3051',
       '49-3052', '49-3053', '49-3091', '49-3092', '49-3093', '49-9011',
       '49-9012', '49-9021', '49-9031', '49-9041', '49-9043', '49-9044',
       '49-9045', '49-9051', '49-9052', '49-9061', '49-9062', '49-9063',
       '49-9064', '49-9069', '49-9071', '49-9081', '49-9091', '49-9092',
       '49-9093', '49-9094', '49-9095', '49-9096', '49-9097', '49-9098',
       '49-9099', '51-1011', '51-2011', '51-2021', '51-2022', '51-2023',
       '51-2031', '51-2041', '51-2091', '51-2092', '51-2093', '51-2099',
       '51-3011', '51-3021', '51-3022', '51-3023', '51-3091', '51-3092',
       '51-3093', '51-3099', '51-4011', '51-4012', '51-4021', '51-4022',
       '51-4023', '51-4031', '51-4032', '51-4033', '51-4034', '51-4035',
       '51-4041', '51-4051', '51-4052', '51-4061', '51-4062', '51-4071',
       '51-4072', '51-4081', '51-4111', '51-4121', '51-4122', '51-4191',
       '51-4192', '51-4193', '51-4194', '51-4199', '51-5111', '51-5112',
       '51-5113', '51-6011', '51-6021', '51-6031', '51-6041', '51-6042',
       '51-6051', '51-6052', '51-6061', '51-6062', '51-6063', '51-6064',
       '51-6091', '51-6092', '51-6093', '51-6099', '51-7011', '51-7021',
       '51-7031', '51-7032', '51-7041', '51-7042', '51-7099', '51-8011',
       '51-8012', '51-8013', '51-8021', '51-8031', '51-8091', '51-8092',
       '51-8093', '51-8099', '51-9011', '51-9012', '51-9021', '51-9022',
       '51-9023', '51-9031', '51-9032', '51-9041', '51-9051', '51-9061',
       '51-9071', '51-9081', '51-9082', '51-9083', '51-9111', '51-9121',
       '51-9122', '51-9123', '51-9141', '51-9151', '51-9191', '51-9192',
       '51-9193', '51-9194', '51-9195', '51-9196', '51-9197', '51-9198',
       '51-9199', '53-1011', '53-1021', '53-1031', '53-2011', '53-2012',
       '53-2021', '53-2022', '53-2031', '53-3011', '53-3021', '53-3022',
       '53-3031', '53-3032', '53-3033', '53-3041', '53-3099', '53-4011',
       '53-4012', '53-4013', '53-4021', '53-4031', '53-4041', '53-4099',
       '53-5011', '53-5021', '53-5022', '53-5031', '53-6011', '53-6021',
       '53-6031', '53-6041', '53-6051', '53-6061', '53-6099', '53-7011',
       '53-7021', '53-7031', '53-7032', '53-7033', '53-7041', '53-7051',
       '53-7061', '53-7062', '53-7063', '53-7064', '53-7071', '53-7072',
       '53-7073', '53-7081', '53-7111', '53-7121', '53-7199', '55-1011',
       '55-1012', '55-1013', '55-1014', '55-1015', '55-1016', '55-1017',
       '55-1019', '55-2011', '55-2012', '55-2013', '55-3011', '55-3012',
       '55-3013', '55-3014', '55-3015', '55-3016', '55-3017', '55-3018',
       '55-3019'], dtype=object)

How many matches do I find in the ONET-SOC crosswalk?

In [24]:
matches =  []
for code_orig, label_orig in zip(missing_matches.onet_code, missing_matches.title_gtp):
    match = onet_us2010soc.loc[onet_us2010soc.loc[:, 'O*NET-SOC 2010 Code'] == code_orig]
    matches.append(not match.empty)
    print(code_orig, "¦", label_orig, "¦", not match.empty)

11-9199.11 ¦ Brownfield Redevelopment Specialists and Site Managers ¦ True
11-9199.10 ¦ Wind Energy Project Managers ¦ True
11-9199.09 ¦ Wind Energy Operations Managers ¦ True
49-9042.00 ¦ Maintenance and Repair Workers, General ¦ False
47-4099.01 ¦ Solar Photovoltaic Installers ¦ False
47-4099.02 ¦ Solar Thermal Installers and Technicians ¦ True
13-1073.00 ¦ Training and Development Specialists ¦ False
13-1081.01 ¦ Logistics Engineers ¦ True
47-5041.00 ¦ Continuous Mining Machine Operators ¦ True
11-9121.02 ¦ Water Resource Specialists ¦ True
11-9041.01 ¦ Biofuels/Biodiesel Technology and Product Development Managers ¦ True
11-9199.06 ¦ Logistics Managers ¦ False
17-3029.03 ¦ Electromechanical Engineering Technologists ¦ True
49-9099.01 ¦ Geothermal Technicians ¦ True
49-9099.02 ¦ Wind Turbine Service Technicians ¦ False
11-9041.00 ¦ Engineering Managers ¦ True
11-9013.02 ¦ Farm and Ranch Managers ¦ True
51-8011.00 ¦ Nuclear Power Reactor Operators ¦ True
51-8099.01 ¦ Biofuels Processing Technicians ¦ True
11-3051.06 ¦ Hydroelectric Production Managers ¦ True
51-8099.03 ¦ Biomass Plant Technicians ¦ True
11-3051.05 ¦ Methane/Landfill Gas Collection System Operators ¦ True
11-3051.04 ¦ Biomass Production Managers ¦ True
11-3051.03 ¦ Biofuels Production Managers ¦ True
11-3051.02 ¦ Geothermal Production Managers ¦ True
53-1021.01 ¦ Recycling Coordinators ¦ True
11-2011.01 ¦ Green Marketers ¦ True
53-6051.07 ¦ Transportation Vehicle, Equipment and Systems Inspectors, Except Aviation ¦ True
47-1011.03 ¦ Solar Energy Installation Managers ¦ True
13-2099.01 ¦ Financial Quantitative Analysts ¦ True
17-3029.02 ¦ Electrical Engineering Technologists ¦ True
19-2099.01 ¦ Remote Sensing Scientists and Technologists ¦ True
17-3029.05 ¦ Industrial Engineering Technologists ¦ True
17-3027.01 ¦ Automotive Engineering Technicians ¦ True
17-3024.01 ¦ Robotics Technicians ¦ True
17-3024.00 ¦ Electro-Mechanical Technicians ¦ True
17-3029.09 ¦ Manufacturing Production Technicians ¦ True
17-3029.10 ¦ Fuel Cell Technicians ¦ True
17-3029.11 ¦ Nanotechnology Engineering Technologists ¦ True
17-3029.12 ¦ Nanotechnology Engineering Technicians ¦ True
19-1031.01 ¦ Soil and Water Conservationists ¦ True
17-2199.11 ¦ Solar Energy Systems Engineers ¦ True
19-2041.01 ¦ Climate Change Analysts ¦ True
19-2041.02 ¦ Environmental Restoration Planners ¦ True
17-2199.10 ¦ Wind Energy Engineers ¦ True
17-2199.09 ¦ Nanosystems Engineers ¦ True
19-3011.01 ¦ Environmental Economists ¦ True
13-2099.03 ¦ Investment Underwriters ¦ True
17-2199.06 ¦ Microsystems Engineers ¦ True
17-2199.05 ¦ Mechatronics Engineers ¦ True
17-2161.00 ¦ Nuclear Engineers ¦ True
19-4041.02 ¦ Geological Sample Test Technicians ¦ True
19-4051.01 ¦ Nuclear Equipment Operation Technicians ¦ True
17-2141.02 ¦ Automotive Engineers ¦ True
19-4099.02 ¦ Precision Agriculture Technicians ¦ True
17-2141.01 ¦ Fuel Cell Engineers ¦ True
17-2081.01 ¦ Water/Wastewater Engineers ¦ True
17-2051.01 ¦ Transportation Engineers ¦ True
17-2011.00 ¦ Aerospace Engineers ¦ True
15-1099.07 ¦ Geographic Information Systems Technicians ¦ False
15-1099.06 ¦ Geospatial Information Scientists and Technologists ¦ False
41-3099.01 ¦ Energy Brokers ¦ True
17-3029.04 ¦ Electronics Engineering Technologists ¦ True

56 of the 63 matchless occupation can be matched!

In [25]:
np.array(matches).sum()

56

More detailed analysis

#### Option 4: use ONET SOC to ISCO crosswalk from the Institute for Structural Research - IBS

Idea:
- use an existing crosswalk from ONET-SOC to ISCO
-

In [26]:
soc10_isco08 = crosswalks.soc10_isco08_ibs
soc10_isco08

       soc10  isco08
0     111011    1112
1     111011    1113
2     111011    1120
3     111021    1112
4     111021    1114
...      ...     ...
1126  553015     310
1127  553016     310
1128  553017     310
1129  553018     310
1130  553019     310

[1131 rows x 2 columns]

In [27]:
soc10_isco08.soc10.unique()

array([111011, 111021, 111031, 112011, 112021, 112022, 112031, 113011,
       113021, 113031, 113051, 113061, 113071, 113111, 113121, 113131,
       119013, 119021, 119031, 119032, 119033, 119039, 119041, 119051,
       119061, 119071, 119081, 119111, 119121, 119131, 119141, 119151,
       119161, 119199, 131011, 131021, 131022, 131023, 131031, 131032,
       131041, 131051, 131071, 131074, 131075, 131081, 131111, 131121,
       131131, 131141, 131151, 131161, 131199, 132011, 132021, 132031,
       132041, 132051, 132052, 132053, 132061, 132071, 132072, 132081,
       132082, 132099, 151111, 151121, 151122, 151131, 151132, 151133,
       151134, 151141, 151142, 151143, 151151, 151152, 151199, 152011,
       152021, 152031, 152041, 152091, 152099, 171011, 171012, 171021,
       171022, 172011, 172021, 172031, 172041, 172051, 172061, 172071,
       172072, 172081, 172111, 172112, 172121, 172131, 172141, 172151,
       172161, 172171, 172199, 173011, 173012, 173013, 173019, 173021,
       173022, 173023, 173024, 173025, 173026, 173027, 173029, 173031,
       191011, 191012, 191013, 191021, 191022, 191023, 191029, 191031,
       191032, 191041, 191042, 191099, 192011, 192012, 192021, 192031,
       192032, 192041, 192042, 192043, 192099, 193011, 193022, 193031,
       193032, 193039, 193041, 193051, 193091, 193092, 193093, 193094,
       193099, 194011, 194021, 194031, 194041, 194051, 194061, 194091,
       194092, 194093, 194099, 211011, 211012, 211013, 211014, 211015,
       211019, 211021, 211022, 211023, 211029, 211091, 211092, 211093,
       211094, 211099, 212011, 212021, 212099, 231011, 231012, 231021,
       231022, 231023, 232011, 232091, 232093, 232099, 251011, 251021,
       251022, 251031, 251032, 251041, 251042, 251043, 251051, 251052,
       251053, 251054, 251061, 251062, 251063, 251064, 251065, 251066,
       251067, 251069, 251071, 251072, 251081, 251082, 251111, 251112,
       251113, 251121, 251122, 251123, 251124, 251125, 251126, 251191,
       251192, 251193, 251194, 251199, 252011, 252012, 252021, 252022,
       252023, 252031, 252032, 252051, 252052, 252053, 252054, 252059,
       253011, 253021, 253099, 254011, 254012, 254013, 254021, 254031,
       259011, 259021, 259031, 259041, 259099, 271011, 271012, 271013,
       271014, 271019, 271021, 271022, 271023, 271024, 271025, 271026,
       271027, 271029, 272011, 272012, 272021, 272022, 272023, 272031,
       272032, 272041, 272042, 272099, 273011, 273012, 273021, 273022,
       273031, 273041, 273042, 273043, 273091, 273099, 274011, 274012,
       274013, 274014, 274021, 274031, 274032, 274099, 291011, 291021,
       291022, 291023, 291024, 291029, 291031, 291041, 291051, 291061,
       291062, 291063, 291064, 291065, 291066, 291067, 291069, 291071,
       291081, 291122, 291123, 291124, 291125, 291126, 291127, 291128,
       291129, 291131, 291141, 291151, 291161, 291171, 291181, 291199,
       292011, 292012, 292021, 292031, 292032, 292033, 292034, 292035,
       292041, 292051, 292052, 292053, 292054, 292056, 292057, 292061,
       292071, 292081, 292091, 292092, 292099, 299011, 299012, 299091,
       299092, 299099, 311011, 311013, 311014, 311015, 312011, 312012,
       312021, 312022, 319011, 319091, 319092, 319093, 319094, 319095,
       319096, 319097, 319099, 331011, 331012, 331021, 331099, 332011,
       332021, 332022, 333011, 333012, 333021, 333031, 333041, 333051,
       333052, 339011, 339021, 339031, 339032, 339091, 339092, 339093,
       339099, 351011, 351012, 352011, 352012, 352013, 352014, 352015,
       352019, 352021, 353011, 353021, 353022, 353031, 353041, 359011,
       359021, 359031, 359099, 371011, 371012, 372011, 372012, 372019,
       372021, 373011, 373012, 373013, 373019, 391011, 391012, 391021,
       392011, 392021, 393011, 393012, 393019, 393021, 393031, 393091,
       393092, 393093, 393099, 394011, 394021, 394031, 395011, 395012,
       395091, 395092, 395093, 395094, 396011, 396012, 397011, 397012,
       399011, 399021, 399031, 399032, 399041, 399099, 411011, 411012,
       412011, 412012, 412021, 412022, 412031, 413011, 413021, 413031,
       413041, 413099, 414011, 414012, 419011, 419012, 419021, 419022,
       419031, 419041, 419091, 419099, 431011, 432011, 432021, 432099,
       433011, 433021, 433031, 433041, 433051, 433061, 433071, 433099,
       434011, 434021, 434031, 434041, 434051, 434061, 434071, 434081,
       434111, 434121, 434131, 434141, 434151, 434161, 434171, 434181,
       434199, 435011, 435021, 435031, 435032, 435041, 435051, 435052,
       435053, 435061, 435071, 435081, 435111, 436011, 436012, 436013,
       436014, 439011, 439021, 439022, 439031, 439041, 439051, 439061,
       439071, 439081, 439111, 439199, 451011, 452011, 452021, 452041,
       452091, 452092, 452093, 452099, 453011, 453021, 454011, 454021,
       454022, 454023, 454029, 471011, 472011, 472021, 472022, 472031,
       472041, 472042, 472043, 472044, 472051, 472053, 472061, 472071,
       472072, 472073, 472081, 472082, 472111, 472121, 472131, 472132,
       472141, 472142, 472151, 472152, 472161, 472171, 472181, 472211,
       472221, 472231, 473011, 473012, 473013, 473014, 473015, 473016,
       473019, 474011, 474021, 474031, 474041, 474051, 474061, 474071,
       474091, 474099, 475011, 475012, 475013, 475021, 475031, 475041,
       475042, 475049, 475051, 475061, 475071, 475081, 475099, 491011,
       492011, 492021, 492022, 492091, 492092, 492093, 492094, 492095,
       492096, 492097, 492098, 493011, 493021, 493022, 493023, 493031,
       493041, 493042, 493043, 493051, 493052, 493053, 493091, 493092,
       493093, 499011, 499012, 499021, 499031, 499041, 499043, 499044,
       499045, 499051, 499052, 499061, 499062, 499063, 499064, 499069,
       499071, 499081, 499091, 499092, 499093, 499094, 499095, 499096,
       499097, 499098, 499099, 511011, 512011, 512021, 512022, 512023,
       512031, 512041, 512091, 512092, 512093, 512099, 513011, 513021,
       513022, 513023, 513091, 513092, 513093, 513099, 514011, 514012,
       514021, 514022, 514023, 514031, 514032, 514033, 514034, 514035,
       514041, 514051, 514052, 514061, 514062, 514071, 514072, 514081,
       514111, 514121, 514122, 514191, 514192, 514193, 514194, 514199,
       515111, 515112, 515113, 516011, 516021, 516031, 516041, 516042,
       516051, 516052, 516061, 516062, 516063, 516064, 516091, 516092,
       516093, 516099, 517011, 517021, 517031, 517032, 517041, 517042,
       517099, 518011, 518012, 518013, 518021, 518031, 518091, 518092,
       518093, 518099, 519011, 519012, 519021, 519022, 519023, 519031,
       519032, 519041, 519051, 519061, 519071, 519081, 519082, 519083,
       519111, 519121, 519122, 519123, 519141, 519151, 519191, 519192,
       519193, 519194, 519195, 519196, 519197, 519198, 519199, 531011,
       531021, 531031, 532011, 532012, 532021, 532022, 532031, 533011,
       533021, 533022, 533031, 533032, 533033, 533041, 533099, 534011,
       534012, 534013, 534021, 534031, 534041, 534099, 535011, 535021,
       535022, 535031, 536011, 536021, 536031, 536041, 536051, 536061,
       536099, 537011, 537021, 537031, 537032, 537033, 537041, 537051,
       537061, 537062, 537063, 537064, 537071, 537072, 537073, 537081,
       537111, 537121, 537199, 551011, 551012, 551013, 551014, 551015,
       551016, 551017, 551019, 552011, 552012, 552013, 553011, 553012,
       553013, 553014, 553015, 553016, 553017, 553018, 553019])

## Green/brown occupation master file
- triangulation via tasks and skills

In [28]:
smd = esco.combine_skills_metadata(variable_selection=None)
omd = esco.combine_occupation_metadata(skills_metadata=smd)

C:\Users\fzaussinger\Miniconda3\envs\re4gt\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
C:\Users\fzaussinger\Miniconda3\envs\re4gt\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
T:\Documents\Projects\04_jrc_green-skills-regional\03_data-analysis\re4gt\src\data\framework.py:1435: RuntimeWarning: invalid value encountered in true_divide
  occ_share = n_gbn_specific_skills / n_total_specific_skills

In [31]:
omd

,conceptType,conceptUri,iscoGroup,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,regulatedProfessionNote,scopeNote,definition,inScheme,description,code,isco_level_4,isco_level_1,isco_level_2,isco_level_3,isco_label_1,isco_label_2,isco_label_3,isco_label_4,share_green_esco,share_brown_esco,share_neutral_esco,gbn_classification_esco,share_green_esco_ess,share_brown_esco_ess,share_neutral_esco_ess,gbn_classification_esco_ess
0,Occupation,http://data.europa.eu/esco/occupation/00030d09...,2654,technical director,technical and operations director\nhead of tec...,NaN,released,2016-07-05T13:58:41Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Technical directors realise the artistic visio...,2654.1.7,2654,2,26,265,Professionals,"Legal, social and cultural professionals",Creative and performing artists,"Film, stage and related directors and producers",0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral
1,Occupation,http://data.europa.eu/esco/occupation/1a7fb683...,2654,video and motion picture director,television director\nfilm maker\nseries direct...,NaN,released,2017-01-17T13:59:29Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Video and motion picture directors are respons...,2654.1.8,2654,2,26,265,Professionals,"Legal, social and cultural professionals",Creative and performing artists,"Film, stage and related directors and producers",0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral
2,Occupation,http://data.europa.eu/esco/occupation/2f372afe...,2654,performance lighting director,television lighting supervisor\nTV lighting su...,NaN,released,2016-07-05T13:46:52Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Performance lighting directors determine what ...,2654.1.4,2654,2,26,265,Professionals,"Legal, social and cultural professionals",Creative and performing artists,"Film, stage and related directors and producers",0.052632,0.0,0.947368,neutral,0.055556,0.0,0.944444,neutral
3,Occupation,http://data.europa.eu/esco/occupation/30b25ee4...,2654,animation director,animation process director\ncartoon animation ...,NaN,released,2021-03-31T15:31:28.501Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Animation directors supervise and recruit mult...,2654.1.1,2654,2,26,265,Professionals,"Legal, social and cultural professionals",Creative and performing artists,"Film, stage and related directors and producers",0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral
4,Occupation,http://data.europa.eu/esco/occupation/3b6bea7d...,2654,video and motion picture producer,video & motion picture producer\nmovie produce...,NaN,released,2017-01-17T13:58:37Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Video and motion picture producers supervise t...,2654.3.2,2654,2,26,265,Professionals,"Legal, social and cultural professionals",Creative and performing artists,"Film, stage and related directors and producers",0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3003,Occupation,http://data.europa.eu/esco/occupation/b059d331...,9520,hawker,street trader\nmarket stall trader\ncar-boot s...,NaN,released,2021-10-06T08:30:39.429Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Hawkers sell goods and services on established...,9520.1,9520,9,95,952,Elementary occupations,Street and related sales and service workers,Street vendors (excluding food),Street vendors (excluding food),0.000000,0.0,1.000000,neutral,0.000000,0.0,1.000000,neutral
3004,Occupation,http://data.europa.eu/esco/occupation/96a0d8d3...,9411,quick service restaurant crew member,fast food crew member\nquick service crew memb...,NaN,released,2017-01-17T13:33:38Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,"Quick service restaurant crew members prepare,...",9411.2,9411,9,94,941,Elementary occupations,Food preparation assistants,Food preparation assistants,Fast food preparers,0.040000,0.0,0.960000,neutral,0.058824,0.0,0.941176,neutral
3005,Occupation,http://data.europa.eu/esco/occupation/a02a1117...,9411,pizzaiolo,pizza-chef\npizza chef\npizza-cook\npizza cook...,NaN,released,2016-07-05T16:58:43Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Pizzaiolos are responsible for preparing and c...,9411.1,9411,9,94,941,Elementary occupations,Food preparation assistants,Food preparation assistants,Fast food preparers,0.047619,0.0,0.952381,neutral,0.066667,0.0,0.933333,neutral
3006,Occupation,http://data.europa.eu/esco/occupation/e1cf6897...,9412,kitchen assistant,kitchen worker\nkitchen trainee\nkitchen boy\n...,NaN,released,2021-01-20T14:42:44.739Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Kitchen assistants assist in the preparation o...,9412.1,9412,9,94,941,Elementary occupations,Food preparation assistants,Food preparation assistants,Kitchen helpers,0.064516,0.0,0.935484,neutral,0.100000,0.0,0.900000,neutral
3007,Occupation,http://data.europa.eu/esco/occupation/f756fdab...,9412,kitchen porter,pot and pan washer\nkitchen hand\nkitchen stew...,NaN,released,2016-07-05T16:57:14Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/occu...,"Kitchen porters wash and clean kitchen areas, ...",9412.2,9412,9,94,941,Elementary occupations,Food preparation assistants,Food preparation assistants,Kitchen helpers,0.125000,0.0,0.875000,neutral,0.142857,0.0,0.857143,neutral

1 ONET: Vona 2018 (Greenness), SOC 8-digit matched via ONET-ESCO crosswalk [CHECK]
2 ONET: GTP 2011 (Greenness), SOC 8-digit matched via ONET-ESCO crosswalk [CHECK]
3 ONET: Vona 2019 (Greenness), SOC 6-digit matched via IBS SOC-ISCO crosswalk
4 ONET: JRC/Consoli (Greenness), CP-2011 5-digit matched via CP2011-ESCO crosswalk
5 ESCO: ESCO 2022 (Greenness) [CHECK]

In [29]:
cols = ['conceptUri', 'preferredLabel',
       'isco_level_4', 'isco_level_1', 'isco_level_2', 'isco_level_3',
       'isco_label_1', 'isco_label_2', 'isco_label_3', 'isco_label_4',
       'share_green_esco', 'share_brown_esco', 'gbn_classification_esco',
       'share_green_esco_ess', 'share_brown_esco_ess', 'gbn_classification_esco_ess',
       'onet_code', 'title_gtp', 'share_green_gtp', 'share_green_vona2018',
       'is_brown_onet', 'is_green_onet', 'gbn_classification_onet']

In [30]:
omd_sub = omd[cols]

KeyError: "['onet_code', 'title_gtp', 'share_green_gtp', 'share_green_vona2018', 'is_brown_onet', 'is_green_onet', 'gbn_classification_onet'] not in index"

Fill nan values in ONET greenness shares with zeros

In [ ]:
omd_sub.loc[:, "share_green_gtp"] = omd_sub.share_green_gtp.fillna(0)
omd_sub.loc[:, "share_green_vona2018"] = omd_sub.share_green_vona2018.fillna(0)

**Triangulation of green occupations based on intersecting task- and skill data**

Distribution of shares, descriptive statistics

In [ ]:
omd_sub.describe()

In [ ]:
omd_sub.hist(bins=20, log=False, sharex=True)
plt.tight_layout()

Distributions quite skewed, use median

In [ ]:
omd_sub.select_dtypes("float").apply(stats_utils.naniqr, axis=0)

In [ ]:
omd_sub.select_dtypes("float").quantile(0.90)

In [ ]:
omd_sub.loc[omd_sub.loc[:, "share_green_esco"] > 0.2]

In [ ]:
omd_sub.select_dtypes("float")

In [ ]:
omd_sub[(omd_sub.share_green_esco_ess > 0) & ((omd_sub.share_green_gtp > 0) | (omd_sub.share_green_vona2018 > 0))]

In [ ]:
omd_sub[(omd_sub.share_brown_esco > 0) & omd_sub.is_brown_onet]