# Fix bugs in data merging of ESCO and O*NET
Felix Zaussinger | 13.04.2022

## Core Analysis Goal(s)
1. Fix bugs in occupation and skills metadata merging.
2. Gain confidence that the final datasets are valid.
3.

## Key Insight(s)
1.
2.
3.

In [172]:
import os
import sys
import logging
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from src import utils
# import mapping_career_causeways

# OPTIONAL: Load the "autoreload" extension so that code can change
%load_ext autoreload

# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2

# Settings
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

sns.set_context("poster")
sns.set(rc={'figure.figsize': (16, 9.)})
sns.set_style("ticks")

pd.set_option("display.max_rows", 120)
pd.set_option("display.max_columns", 120)

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

# load paths
useful_paths = utils.UsefulPaths(fn_config_path="paths_config.yml")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [173]:
from src import utils, stats_utils, plotting_utils
from src.data.esco import EscoDs

Configuration files

In [174]:
fn_config_path = "paths_config.yml"
fn_config_data = "data_config.yml"
fn_config_model = "model_config.yml"
fn_config_vis = "vis_config.yml"

Code ...

In [175]:
esco = EscoDs(fn_config_path=fn_config_path, fn_config_data=fn_config_data)

Problems with ONET-ESCO crosswalk

In [176]:
gt_esco = esco.read_greenness_task_based()

In [177]:
gt_esco.title_gtp.unique()

array(['Chief Sustainability Officers', 'Green Marketers',
       'Geothermal Production Managers', 'Biofuels Production Managers',
       'Biomass Production Managers',
       'Methane/Landfill Gas Collection System Operators',
       'Hydroelectric Production Managers',
       'Biofuels/Biodiesel Technology and Product Development Managers',
       'Water Resource Specialists', 'Wind Energy Operations Managers',
       'Wind Energy Project Managers',
       'Brownfield Redevelopment Specialists and Site Managers',
       'Energy Auditors', 'Sustainability Specialists',
       'Environmental Engineers', 'Water/Wastewater Engineers',
       'Fuel Cell Engineers', 'Energy Engineers', 'Wind Energy Engineers',
       'Solar Energy Systems Engineers',
       'Environmental Engineering Technicians', 'Fuel Cell Technicians',
       'Soil and Water Conservationists', 'Climate Change Analysts',
       'Environmental Restoration Planners', 'Industrial Ecologists',
       'Environmental Economists',
       'Environmental Science and Protection Technicians, Including Health',
       'Energy Brokers', 'Solar Sales Representatives and Assessors',
       'Solar Energy Installation Managers',
       'Hazardous Materials Removal Workers',
       'Solar Photovoltaic Installers',
       'Solar Thermal Installers and Technicians',
       'Weatherization Installers and Technicians',
       'Geothermal Technicians', 'Wind Turbine Service Technicians',
       'Biofuels Processing Technicians',
       'Methane/Landfill Gas Generation System Technicians',
       'Biomass Plant Technicians', 'Hydroelectric Plant Technicians',
       'Recycling and Reclamation Workers', 'Recycling Coordinators',
       'Refuse and Recyclable Material Collectors', 'Aerospace Engineers',
       'Atmospheric and Space Scientists',
       'Geoscientists, Except Hydrologists and Geographers',
       'Civil Engineers', 'Automotive Specialty Technicians',
       'Transportation Vehicle, Equipment and Systems Inspectors, Except Aviation',
       'Electrical Engineering Technologists',
       'Nuclear Equipment Operation Technicians', 'Plumbers',
       'Nuclear Engineers', 'Urban and Regional Planners',
       'Logistics Engineers', 'Nanosystems Engineers',
       'Nanotechnology Engineering Technologists',
       'Occupational Health and Safety Technicians',
       'Biochemical Engineers', 'Financial Analysts',
       'Electromechanical Engineering Technologists', 'Roofers',
       'Automotive Engineers', 'Precision Agriculture Technicians',
       'Construction and Building Inspectors', 'Supply Chain Managers',
       'Manufacturing Engineering Technologists', 'Construction Managers',
       'Architects, Except Landscape and Naval', 'Logistics Managers',
       'Wholesale and Retail Buyers, Except Farm Products',
       'Nuclear Power Reactor Operators', 'Mechanical Engineers',
       'Automotive Engineering Technicians',
       'Heating and Air Conditioning Mechanics and Installers',
       'Geographic Information Systems Technicians',
       'Landscape Architects', 'Storage and Distribution Managers',
       'Transportation Engineers', 'Industrial Engineering Technicians',
       'Sheet Metal Workers', 'Financial Quantitative Analysts',
       'Electronics Engineers, Except Computer',
       'Public Relations Specialists  ', 'Freight Forwarders',
       'Geophysical Data Technicians', 'Transportation Managers',
       'Electrical Engineering Technicians', 'Power Plant Operators',
       'Compliance Managers', 'Marketing Managers',
       'Microsystems Engineers', 'Photonics Technicians',
       'Manufacturing Production Technicians', 'Logistics Analysts',
       'Photonics Engineers', 'Engineering Managers',
       'Regulatory Affairs Specialists', 'Electrical Engineers',
       'Construction Laborers', 'Geological Sample Test Technicians',
       'Risk Management Specialists',
       'Electronics Engineering Technologists',
       'Industrial Engineering Technologists', 'Manufacturing Engineers',
       'Nanotechnology Engineering Technicians',
       'Mechanical Engineering Technologists',
       'Pipe Fitters and Steamfitters', 'Regulatory Affairs Managers',
       'Farm and Ranch Managers', 'Personal Financial Advisors',
       'Maintenance and Repair Workers, General',
       'Transportation Planners', 'Remote Sensing Technicians',
       'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products',
       'Continuous Mining Machine Operators',
       'Aircraft Structure, Surfaces, Rigging, and Systems Assemblers',
       'Mechatronics Engineers', 'General and Operations Managers',
       'Investment Underwriters', 'Agricultural Technicians',
       'Robotics Technicians', 'Training and Development Specialists',
       'Truck Drivers, Heavy and Tractor-Trailer', 'Validation Engineers',
       'Robotics Engineers', 'Securities and Commodities Traders',
       'Shipping, Receiving, and Traffic Clerks',
       'Geospatial Information Scientists and Technologists',
       'Electro-Mechanical Technicians',
       'Remote Sensing Scientists and Technologists', 'Machinists',
       'Inspectors, Testers, Sorters, Samplers, and Weighers',
       'Service Unit Operators, Oil, Gas, and Mining',
       'Arbitrators, Mediators, and Conciliators',
       'Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders',
       'Reporters and Correspondents'], dtype=object)

63 ONET greening occupations dont have a match to ESCO based on current crosswalk

In [178]:
bsel = gt_esco.loc[:, ["preferred_label"]].isna().values
df_no_match = gt_esco.loc[bsel]
df_no_match

,onet_code,title_gtp,occupation_type,n_new_green_tasks_gtp,n_existing_green_tasks_gtp,n_non_green_tasks_gtp,share_green_gtp,title_vona2018,share_green_vona2018,total_spec_tasks_vona2018,green_spec_tasks_vona2018,id,concept_uri,preferred_label,isco_level_4,onet_occupation
1,11-2011.01,Green Marketers,New Green N&E,16,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11-3051.02,Geothermal Production Managers,New Green N&E,17,0,0,1.000000,Geothermal Production Managers,1.000000,17.0,17.0,NaN,NaN,NaN,NaN,NaN
3,11-3051.03,Biofuels Production Managers,New Green N&E,14,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11-3051.04,Biomass Production Managers,New Green N&E,18,0,0,1.000000,Biomass Power Plant Managers,1.000000,18.0,18.0,NaN,NaN,NaN,NaN,NaN
5,11-3051.05,Methane/Landfill Gas Collection System Operators,New Green N&E,21,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,11-3051.06,Hydroelectric Production Managers,New Green N&E,19,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,11-9041.01,Biofuels/Biodiesel Technology and Product Deve...,New Green N&E,19,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,11-9121.02,Water Resource Specialists,New Green N&E,21,0,0,1.000000,Water Resource Specialists,1.000000,21.0,21.0,NaN,NaN,NaN,NaN,NaN
9,11-9199.09,Wind Energy Operations Managers,New Green N&E,16,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11-9199.10,Wind Energy Project Managers,New Green N&E,15,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11-9199.11,Brownfield Redevelopment Specialists and Site ...,New Green N&E,22,0,0,1.000000,Brownfield Redevelopment Specialists and Site ...,1.000000,22.0,22.0,NaN,NaN,NaN,NaN,NaN
22,17-2081.01,Water/Wastewater Engineers,New Green N&E,27,0,0,1.000000,Water/Wastewater Engineers,1.000000,27.0,27.0,NaN,NaN,NaN,NaN,NaN
23,17-2141.01,Fuel Cell Engineers,Existing Green N&E,3,23,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,17-2199.10,Wind Energy Engineers,New Green N&E,16,0,0,1.000000,Wind Energy Engineers,1.000000,16.0,16.0,NaN,NaN,NaN,NaN,NaN
33,17-2199.11,Solar Energy Systems Engineers,New Green N&E,13,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,17-3029.10,Fuel Cell Technicians,Existing Green N&E,4,12,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,19-1031.01,Soil and Water Conservationists,Green Enhanced Skills,8,25,0,1.000000,Soil and Water Conservationists,1.000000,33.0,33.0,NaN,NaN,NaN,NaN,NaN
40,19-2041.01,Climate Change Analysts,New Green N&E,14,0,0,1.000000,Climate Change Analysts,1.000000,14.0,14.0,NaN,NaN,NaN,NaN,NaN
41,19-2041.02,Environmental Restoration Planners,New Green N&E,22,0,0,1.000000,Environmental Restoration Planners,1.000000,22.0,22.0,NaN,NaN,NaN,NaN,NaN
43,19-3011.01,Environmental Economists,New Green N&E,20,0,0,1.000000,Environmental Economists,1.000000,19.0,19.0,NaN,NaN,NaN,NaN,NaN
48,41-3099.01,Energy Brokers,Existing Green N&E,4,12,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,47-1011.03,Solar Energy Installation Managers,New Green N&E,15,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,47-4099.01,Solar Photovoltaic Installers,New Green N&E,26,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,47-4099.02,Solar Thermal Installers and Technicians,New Green N&E,21,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,49-9099.01,Geothermal Technicians,New Green N&E,26,0,0,1.000000,Geothermal Technicians,1.000000,24.0,24.0,NaN,NaN,NaN,NaN,NaN
57,49-9099.02,Wind Turbine Service Technicians,New Green N&E,13,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,51-8099.01,Biofuels Processing Technicians,New Green N&E,19,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,51-8099.03,Biomass Plant Technicians,New Green N&E,16,0,0,1.000000,Biomass Plant Technicians,1.000000,16.0,16.0,NaN,NaN,NaN,NaN,NaN
65,53-1021.01,Recycling Coordinators,New Green N&E,23,0,0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,17-2011.00,Aerospace Engineers,Green Enhanced Skills,5,4,9,0.500000,Aerospace Engineers,0.333333,18.0,6.0,NaN,NaN,NaN,NaN,NaN
100,53-6051.07,"Transportation Vehicle, Equipment and Systems ...",Green Enhanced Skills,8,1,12,0.428571,"Transportation Vehicle, Equipment and Systems ...",0.409091,22.0,9.0,NaN,NaN,NaN,NaN,NaN
101,17-3029.02,Electrical Engineering Technologists,Existing Green N&E,7,1,11,0.421053,Electrical Engineering Technologists,0.400000,20.0,8.0,NaN,NaN,NaN,NaN,NaN
102,19-4051.01,Nuclear Equipment Operation Technicians,Green Enhanced Skills,7,1,12,0.400000,Nuclear Equipment Operation Technicians,0.411765,17.0,7.0,NaN,NaN,NaN,NaN,NaN
105,17-2161.00,Nuclear Engineers,Green Enhanced Skills,3,4,12,0.368421,Nuclear Engineers,0.350000,20.0,7.0,NaN,NaN,NaN,NaN,NaN
108,13-1081.01,Logistics Engineers,Existing Green N&E,10,1,19,0.366667,Logistics Engineers,0.366667,30.0,11.0,NaN,NaN,NaN,NaN,NaN
109,17-2199.09,Nanosystems Engineers,Existing Green N&E,9,0,16,0.360000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,17-3029.11,Nanotechnology Engineering Technologists,Existing Green N&E,6,0,11,0.352941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,17-3029.03,Electromechanical Engineering Technologists,Existing Green N&E,3,2,10,0.333333,Electromechanical Engineering Technologists,0.294118,17.0,5.0,NaN,NaN,NaN,NaN,NaN
124,17-2141.02,Automotive Engineers,Existing Green N&E,6,2,17,0.320000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,19-4099.02,Precision Agriculture Technicians,Existing Green N&E,4,3,15,0.318182,Precision Agriculture Technicians,0.304348,23.0,7.0,NaN,NaN,NaN,NaN,NaN
142,11-9199.06,Logistics Managers,Existing Green N&E,8,1,21,0.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,51-8011.00,Nuclear Power Reactor Operators,Green Enhanced Skills,6,0,14,0.300000,Nuclear Power Reactor Operators,0.333333,18.0,6.0,NaN,NaN,NaN,NaN,NaN
221,17-3027.01,Automotive Engineering Technicians,Existing Green N&E,4,1,13,0.277778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,15-1099.07,Geographic Information Systems Technicians,Existing Green N&E,5,0,14,0.263158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,17-2051.01,Transportation Engineers,Existing Green N&E,3,3,18,0.250000,Transportation Engineers,0.230769,26.0,6.0,NaN,NaN,NaN,NaN,NaN
238,13-2099.01,Financial Quantitative Analysts,Existing Green N&E,5,0,16,0.238095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,17-2199.06,Microsystems Engineers,Existing Green N&E,5,1,24,0.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,17-3029.09,Manufacturing Production Technicians,Existing Green N&E,4,2,24,0.200000,Manufacturing Production Technicians,0.200000,30.0,6.0,NaN,NaN,NaN,NaN,NaN
304,11-9041.00,Engineering Managers,Green Enhanced Skills,4,0,17,0.190476,Architectural and Engineering Managers,0.190476,21.0,4.0,NaN,NaN,NaN,NaN,NaN
315,19-4041.02,Geological Sample Test Technicians,Green Enhanced Skills,2,1,14,0.176471,Geological Sample Test Technicians,0.187500,16.0,3.0,NaN,NaN,NaN,NaN,NaN
317,17-3029.04,Electronics Engineering Technologists,Existing Green N&E,4,0,19,0.173913,Electronics Engineering Technologists,0.173913,23.0,4.0,NaN,NaN,NaN,NaN,NaN
318,17-3029.05,Industrial Engineering Technologists,Existing Green N&E,4,0,19,0.173913,Industrial Engineering Technologists,0.173913,23.0,4.0,NaN,NaN,NaN,NaN,NaN
322,17-3029.12,Nanotechnology Engineering Technicians,Existing Green N&E,3,0,16,0.157895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,11-9013.02,Farm and Ranch Managers,Green Enhanced Skills,3,1,24,0.142857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,49-9042.00,"Maintenance and Repair Workers, General",Green Enhanced Skills,4,0,25,0.137931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363,47-5041.00,Continuous Mining Machine Operators,Green Enhanced Skills,2,0,13,0.133333,Continuous Mining Machine Operators,0.166667,12.0,2.0,NaN,NaN,NaN,NaN,NaN
367,17-2199.05,Mechatronics Engineers,Existing Green N&E,3,0,20,0.130435,Mechatronics Engineers,0.130435,23.0,3.0,NaN,NaN,NaN,NaN,NaN
375,13-2099.03,Investment Underwriters,Existing Green N&E,2,0,15,0.117647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380,17-3024.01,Robotics Technicians,Existing Green N&E,2,0,17,0.105263,Robotics Technicians,0.086957,23.0,2.0,NaN,NaN,NaN,NaN,NaN
381,13-1073.00,Training and Development Specialists,Green Enhanced Skills,2,0,18,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,15-1099.06,Geospatial Information Scientists and Technolo...,Existing Green N&E,2,0,22,0.083333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,17-3024.00,Electro-Mechanical Technicians,Green Enhanced Skills,1,0,11,0.083333,Electro-Mechanical Technicians,0.083333,12.0,1.0,NaN,NaN,NaN,NaN,NaN
411,19-2099.01,Remote Sensing Scientists and Technologists,Existing Green N&E,2,0,22,0.083333,Remote Sensing Scientists and Technologists,0.083333,24.0,2.0,NaN,NaN,NaN,NaN,NaN

In [179]:
gt_esco.columns

Index(['onet_code', 'title_gtp', 'occupation_type', 'n_new_green_tasks_gtp',
       'n_existing_green_tasks_gtp', 'n_non_green_tasks_gtp',
       'share_green_gtp', 'title_vona2018', 'share_green_vona2018',
       'total_spec_tasks_vona2018', 'green_spec_tasks_vona2018', 'id',
       'concept_uri', 'preferred_label', 'isco_level_4', 'onet_occupation'],
      dtype='object')

Summary: number of ESCO occupations matched to a single greening ONET occupation

In [180]:
grouping_cols = ["onet_code", "title_gtp", "occupation_type", "share_green_gtp"]

match_summary = gt_esco.groupby(grouping_cols)["preferred_label"].count().sort_values(ascending=False)
match_summary.rename("n_matches_esco", inplace=True)

match_summary.to_csv(
    os.path.join(useful_paths.results_dir, "validation", "onet_esco_crosswalk", "onet_to_esco_match_summary.csv"),
    sep=";"
)

match_summary

onet_code   title_gtp                                                                                            occupation_type        share_green_gtp
13-1022.00  Wholesale and Retail Buyers, Except Farm Products                                                    Green Enhanced Skills  0.300000           41
17-2141.00  Mechanical Engineers                                                                                 Green Enhanced Skills  0.285714           36
51-9012.00  Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders  Green Enhanced Skills  0.047619           29
51-9061.00  Inspectors, Testers, Sorters, Samplers, and Weighers                                                 Green Enhanced Skills  0.062500           28
27-3022.00  Reporters and Correspondents                                                                         Green Enhanced Skills  0.035714           18
                                                                                                                                                           ..
17-2011.00  Aerospace Engineers                                                                                  Green Enhanced Skills  0.500000            0
15-1099.07  Geographic Information Systems Technicians                                                           Existing Green N&E     0.263158            0
15-1099.06  Geospatial Information Scientists and Technologists                                                  Existing Green N&E     0.083333            0
41-3099.01  Energy Brokers                                                                                       Existing Green N&E     1.000000            0
17-3029.04  Electronics Engineering Technologists                                                                Existing Green N&E     0.173913            0
Name: n_matches_esco, Length: 138, dtype: int64

In [181]:
df_no_match.title_gtp.unique().shape

(63,)

In [183]:
onet_code = "11-3051.00"
esco.crosswalk_onet_esco_mcc_full.query("onet_code == '{}'".format(onet_code))

,id,concept_uri,preferred_label,isco_level_4,onet_code,onet_occupation
45,45,http://data.europa.eu/esco/occupation/02f26b2f...,footwear quality manager,1321,11-3051.00,industrial production managers
50,50,http://data.europa.eu/esco/occupation/0368c4d4...,metal production manager,1321,11-3051.00,industrial production managers
69,69,http://data.europa.eu/esco/occupation/0552ff45...,foundry manager,1219,11-3051.00,industrial production managers
161,161,http://data.europa.eu/esco/occupation/0d21a30d...,chemical production manager,1321,11-3051.00,industrial production managers
384,384,http://data.europa.eu/esco/occupation/1f8967ce...,leather goods quality manager,1321,11-3051.00,industrial production managers
467,467,http://data.europa.eu/esco/occupation/262d4e45...,leather wet processing department manager,1321,11-3051.00,industrial production managers
599,599,http://data.europa.eu/esco/occupation/316309e4...,leather production manager,1321,11-3051.00,industrial production managers
714,714,http://data.europa.eu/esco/occupation/3afd6af4...,clothing operations manager,1321,11-3051.00,industrial production managers
821,821,http://data.europa.eu/esco/occupation/45517bc3...,metallurgical manager,1321,11-3051.00,industrial production managers
1009,1009,http://data.europa.eu/esco/occupation/546ec458...,water treatment plant manager,1219,11-3051.00,industrial production managers
1199,1199,http://data.europa.eu/esco/occupation/6426ada1...,manufacturing manager,1321,11-3051.00,industrial production managers
1203,1203,http://data.europa.eu/esco/occupation/6482664d...,footwear production manager,1321,11-3051.00,industrial production managers
1211,1211,http://data.europa.eu/esco/occupation/652b847f...,textile quality manager,1321,11-3051.00,industrial production managers
1248,1248,http://data.europa.eu/esco/occupation/680831bb...,manufacturing facility manager,1219,11-3051.00,industrial production managers
1557,1557,http://data.europa.eu/esco/occupation/81cc1583...,chemical plant manager,1219,11-3051.00,industrial production managers
1839,1839,http://data.europa.eu/esco/occupation/9a20c93e...,waste management officer,1321,11-3051.00,industrial production managers
1876,1876,http://data.europa.eu/esco/occupation/9deee896...,sewerage systems manager,1321,11-3051.00,industrial production managers
1929,1929,http://data.europa.eu/esco/occupation/a2bc52c2...,leather finishing operations manager,1321,11-3051.00,industrial production managers
1989,1989,http://data.europa.eu/esco/occupation/a7d6a377...,food production manager,1321,11-3051.00,industrial production managers
2152,2152,http://data.europa.eu/esco/occupation/b633af32...,wood factory manager,1219,11-3051.00,industrial production managers
2350,2350,http://data.europa.eu/esco/occupation/c6bd511a...,operations manager,1321,11-3051.00,industrial production managers
2404,2404,http://data.europa.eu/esco/occupation/cb446db8...,power plant manager,1219,11-3051.00,industrial production managers
2663,2663,http://data.europa.eu/esco/occupation/e5257110...,leather goods production manager,1321,11-3051.00,industrial production managers
2728,2728,http://data.europa.eu/esco/occupation/eb9479c6...,industrial production manager,1321,11-3051.00,industrial production managers
2919,2919,http://data.europa.eu/esco/occupation/fdb16700...,industrial quality manager,1321,11-3051.00,industrial production managers