# Descriptive-Title
Felix Zaussinger | XX.YY.ZZZZ

## Core Analysis Goal(s)
1.
2.
3.

## Key Insight(s)
1.
2.
3.

In [103]:
import os
import sys
import logging
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from src import utils
#import mapping_career_causeways

# OPTIONAL: Load the "autoreload" extension so that code can change
%load_ext autoreload

# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2

# Settings
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

sns.set_context("poster")
sns.set(rc={'figure.figsize': (16, 9.)})
sns.set_style("ticks")

pd.set_option("display.max_rows", 120)
pd.set_option("display.max_columns", 120)

logging.basicConfig(level=logging.INFO, stream=sys.stdout)

# load paths
useful_paths = utils.UsefulPaths(fn_config_path="paths_config.yml")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

Configuration files

In [104]:
fn_config_path = "paths_config.yml"
fn_config_data = "data_config.yml"
fn_config_model = "model_config.yml"
fn_config_vis = "vis_config.yml"

#### Crosswalk IT (CP 2011) - ESCO

Mapping project name,AI4ESCO
Mapping project author,CRISP
Mapping project version,merged
Mapping project version date,2021-04-23
Classification 1 Name,Italian ESCO
Classification 1 Concept type,occupation
Classification 1 Version,1.0.8
Classification 1 Language,it
Classification 1 Landing page,https://ec.europa.eu/esco/portal/occupation
Classification 2 Name,classificazione delle professioni CP2011
Classification 2 Concept type,occupation
Classification 2 Version,2011
Classification 2 Language,it
Classification 2 Landing page,http://professioni.istat.it/cp2011/

In [105]:
cw_it_esco = pd.read_csv(
    os.path.join(useful_paths.data_external, "crosswalks", "IT_mapping_23.04.2021.csv"),
    header=14
)

# Customise column names
cw_it_esco.columns = cw_it_esco.columns.str.split(" ").str.join("_") + "_it"

Customise column names

In [106]:
cw_it_esco

,Classification_1_URI_it,Classification_1_PrefLabel_it,Classification_1_URL_it,Classification_2_ID_it,Classification_2_PrefLabel_it,Classification_2_URL_it,Mapping_relation_it,Editorial_note_it
0,http://data.europa.eu/esco/occupation/404a50e9...,ministro/ministra,http://data.europa.eu/esco/occupation/404a50e9...,1.1.1.1.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN
1,http://data.europa.eu/esco/occupation/5bca96fd...,deputato/deputata,http://data.europa.eu/esco/occupation/5bca96fd...,1.1.1.1.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN
2,http://data.europa.eu/esco/occupation/0ee67d5e...,segretario di Stato/segretaria di Stato,http://data.europa.eu/esco/occupation/0ee67d5e...,1.1.1.1.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN
3,http://data.europa.eu/esco/occupation/73c3f018...,senatore/senatrice,http://data.europa.eu/esco/occupation/73c3f018...,1.1.1.1.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN
4,http://data.europa.eu/esco/occupation/d63789ac...,presidente di regione,http://data.europa.eu/esco/occupation/d63789ac...,1.1.1.2.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN
...,...,...,...,...,...,...,...,...
3235,http://data.europa.eu/esco/occupation/c94dc5b2...,pilota dell’aeronautica militare,http://data.europa.eu/esco/occupation/c94dc5b2...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN
3236,http://data.europa.eu/esco/occupation/fdc8adfb...,sminatore/sminatrice,http://data.europa.eu/esco/occupation/fdc8adfb...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN
3237,http://data.europa.eu/esco/occupation/bd5a2f44...,soldato di fanteria,http://data.europa.eu/esco/occupation/bd5a2f44...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN
3238,http://data.europa.eu/esco/occupation/35e67944...,responsabile informazioni operative,http://data.europa.eu/esco/occupation/35e67944...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN
3239,http://data.europa.eu/esco/occupation/555235ce...,ingegnere militare,http://data.europa.eu/esco/occupation/555235ce...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN

#### Checks

- was used for mapping (2980 unique occupations)
- CP-2011 has 829 unique occupations

- a small number of occupations are not labelled in both classifications

In [107]:
for col in cw_it_esco.columns:
    print(col, ":", cw_it_esco.loc[:, col].unique().shape[0])

Classification_1_URI_it : 2980
Classification_1_PrefLabel_it : 2978
Classification_1_URL_it : 2980
Classification_2_ID_it : 829
Classification_2_PrefLabel_it : 826
Classification_2_URL_it : 829
Mapping_relation_it : 4
Editorial_note_it : 1

#### Crosswalk ESCO - DE (KldB-2010)

In [108]:
cw_de_esco = pd.read_csv(
    os.path.join(useful_paths.data_external, "crosswalks", "mapping_ESCO-Berufenet_draft_20220324.csv"),
    header=14
)

# Customise column names
cw_de_esco.columns = cw_de_esco.columns.str.split(" ").str.join("_") + "_de"
cw_de_esco.columns

Index(['Classification_1_URI_de', 'Classification_1_PrefLabel_de',
       'Classification_1_URL_de', 'Classification_2_ID_de',
       'Classification_2_PrefLabel_de', 'Classification_2_URL_de',
       'Mapping_relation_de'],
      dtype='object')

In [109]:
# check mapping relation types
cw_de_esco.loc[:, "Mapping_relation_de"].unique().tolist()

['no relation',
 'skos:broadMatch',
 'skos:exactMatch',
 'skos:narrowMatch',
 'skos:closeMatch']

In [110]:
# drop instances without match and convert ID to int
cw_de_esco = cw_de_esco.loc[cw_de_esco["Mapping_relation_de"] != "no relation"]
cw_de_esco.loc[:, "Classification_2_ID_de"] = cw_de_esco.loc[:, "Classification_2_ID_de"].astype(int)

#### Checks

- ESCO V.1.0.3 was used for mapping (2942 unique occupations)
- KldB-2010 has 2081 unique occupations

- one occupations in ESCO is not labelled

In [111]:
for col in cw_de_esco.columns:
    print(col, ":", cw_de_esco.loc[:, col].unique().shape[0])

Classification_1_URI_de : 2792
Classification_1_PrefLabel_de : 2791
Classification_1_URL_de : 2792
Classification_2_ID_de : 2079
Classification_2_PrefLabel_de : 2079
Classification_2_URL_de : 2079
Mapping_relation_de : 4

#### Join German mapping on Italian mapping

In [112]:
cw_it_de = pd.merge(
    left=cw_it_esco,
    right=cw_de_esco,
    left_on="Classification_1_URI_it",
    right_on="Classification_1_URI_de",
    how="left",
    validate="m:m"
)
cw_it_de.shape

(4817, 15)

Drop rows where no match in German KldB was found

In [113]:
cw_it_de_reduced = cw_it_de.dropna(subset=["Classification_2_ID_de"])
cw_it_de_reduced.loc[:, "Classification_2_ID_de"] = cw_it_de_reduced.loc[:, "Classification_2_ID_de"].astype(int)
cw_it_de_reduced.shape

C:\Users\fzaussinger\AppData\Local\Temp\ipykernel_14288\2024297717.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cw_it_de_reduced.loc[:, "Classification_2_ID_de"] = cw_it_de_reduced.loc[:, "Classification_2_ID_de"].astype(int)

(4616, 15)

#### Save IT-DE crosswalk (via ESCO)

In [114]:
cw_it_de.to_csv(
    os.path.join(useful_paths.data_external, "crosswalks", "crosswalk_it_cp2011_de_kldb2010_full.csv")
)

cw_it_de_reduced.to_csv(
    os.path.join(useful_paths.data_external, "crosswalks", "crosswalk_it_cp2011_de_kldb2010_reduced.csv")
)

#### Read, inspect and join 5-digit Greenness scores from JRC/Consoli

Note: the crosswalk only includes the following n of occupations:
O*NET-SOC Title, isco08
138, 40

In [124]:
greenness_jrc_raw = pd.read_excel(
    os.path.join(useful_paths.data_raw, "onet", "Green_Occupations_jrc_v1_02052022.xlsx")
)

Only 117 occupations are covered at the 5-digit level. In O*Net, green task data was
available for 138 occupations. Shouldn't that translate into many more 5-digit
occupations than 117?

In [123]:
print("n occupations unique: ", greenness_jrc_raw.isco08_jrc.unique().shape)
print("n occupations unique: ", greenness_jrc_raw.occ_eng_jrc.unique().shape)
greenness_jrc_raw

n occupations unique:  (117,)
n occupations unique:  (117,)

,isco08_jrc,occ_eng_jrc,task_eng_jrc,n_green_tasks_jrc,n_tasks_jrc,greenness_jrc,comment_eth
0,1.2.3.2.0,"Directors and managers of the organisation, hu...",ensuring the application of rules and regulations,0,15,0.066667,NaN
1,1.2.3.2.0,"Directors and managers of the organisation, hu...",provide for staff training,0,15,0.066667,NaN
2,1.2.3.2.0,"Directors and managers of the organisation, hu...",oversee legal matters,0,15,0.066667,NaN
3,1.2.3.2.0,"Directors and managers of the organisation, hu...",monitoring or managing the correct application...,0,15,0.066667,NaN
4,1.2.3.2.0,"Directors and managers of the organisation, hu...",arrange for recruitment and selection of staff,0,15,0.066667,NaN
...,...,...,...,...,...,...,...
1400,8.1.4.5.0,Ecological workers and other waste collectors ...,"collect special waste (syringes, batteries, me...",1,15,0.600000,NaN
1401,8.1.4.5.0,Ecological workers and other waste collectors ...,sorting the material to be recycled,0,15,0.600000,NaN
1402,8.1.4.5.0,Ecological workers and other waste collectors ...,Carrying out administrative tasks (filling in ...,0,15,0.600000,NaN
1403,8.1.4.5.0,Ecological workers and other waste collectors ...,carrying out routine or extraordinary maintena...,0,15,0.600000,NaN
1404,8.1.4.5.0,Ecological workers and other waste collectors ...,emptying and cleaning rubbish bins or waste bi...,1,15,0.600000,NaN

Harmonized occ name of "Machinery operators for dry cleaning, bleaching and dyeing of
 industrial yarns and fabrics" (7.2.6.4.0) in excel file

In [125]:
greenness_jrc_raw.columns

Index(['isco08_jrc', 'occ_eng_jrc', 'task_eng_jrc', 'n_green_tasks_jrc',
       'n_tasks_jrc', 'greenness_jrc', 'comment_eth'],
      dtype='object')

In [126]:
# collapse task-level into occupation-level data
group_cols = ["isco08_jrc", "occ_eng_jrc"]
agg_dict = {"n_green_tasks_jrc": np.sum, "n_tasks_jrc": np.mean, "greenness_jrc": np.mean}
greenness_jrc = greenness_jrc_raw.groupby(group_cols).aggregate(agg_dict).reset_index()

print("n duplicates in isco: ", greenness_jrc[group_cols[0]].duplicated().sum())
print("n duplicates in occname: ", greenness_jrc[group_cols[1]].duplicated().sum())

dups = greenness_jrc[group_cols[0]].duplicated()
greenness_jrc.loc[dups]

n duplicates in isco:  0
n duplicates in occname:  0

Empty DataFrame
Columns: [isco08_jrc, occ_eng_jrc, n_green_tasks_jrc, n_tasks_jrc, greenness_jrc]
Index: []

#### Attach 5-digit greenness shares to CW
1. all 117 5-digit occs can be matched to cw
2.

In [127]:
print(greenness_jrc.iloc[0, 0])
print(cw_it_esco.iloc[0, 3])

1.1.2.4.3
1.1.1.1.0

In [130]:
cw_it_de_reduced

,Classification_1_URI_it,Classification_1_PrefLabel_it,Classification_1_URL_it,Classification_2_ID_it,Classification_2_PrefLabel_it,Classification_2_URL_it,Mapping_relation_it,Editorial_note_it,Classification_1_URI_de,Classification_1_PrefLabel_de,Classification_1_URL_de,Classification_2_ID_de,Classification_2_PrefLabel_de,Classification_2_URL_de,Mapping_relation_de
1,http://data.europa.eu/esco/occupation/5bca96fd...,deputato/deputata,http://data.europa.eu/esco/occupation/5bca96fd...,1.1.1.1.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/5bca96fd...,Abgeordneter/Abgeordnete,http://data.europa.eu/esco/occupation/5bca96fd...,90855,Abgeordnete/r,https://berufenet.arbeitsagentur.de/berufenet/...,skos:exactMatch
5,http://data.europa.eu/esco/occupation/7226c10f...,assessore comunale/assessora comunale,http://data.europa.eu/esco/occupation/7226c10f...,1.1.1.3.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/7226c10f...,Stadtverordneter/Stadtverordnete,http://data.europa.eu/esco/occupation/7226c10f...,90680,Stadtrat/-rätin,https://berufenet.arbeitsagentur.de/berufenet/...,skos:exactMatch
6,http://data.europa.eu/esco/occupation/7226c10f...,assessore comunale/assessora comunale,http://data.europa.eu/esco/occupation/7226c10f...,1.1.1.4.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/7226c10f...,Stadtverordneter/Stadtverordnete,http://data.europa.eu/esco/occupation/7226c10f...,90680,Stadtrat/-rätin,https://berufenet.arbeitsagentur.de/berufenet/...,skos:exactMatch
7,http://data.europa.eu/esco/occupation/6cee3765...,sindaco/sindaca,http://data.europa.eu/esco/occupation/6cee3765...,1.1.1.4.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/6cee3765...,Bürgermeister/Bürgermeisterin,http://data.europa.eu/esco/occupation/6cee3765...,90633,Bürgermeister/in,https://berufenet.arbeitsagentur.de/berufenet/...,skos:exactMatch
8,http://data.europa.eu/esco/occupation/a8d05b64...,console,http://data.europa.eu/esco/occupation/a8d05b64...,1.1.2.1.0,"Ambasciatori, ministri plenipotenziari ed alti...",http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/a8d05b64...,Konsul/Konsulin,http://data.europa.eu/esco/occupation/a8d05b64...,7609,Beamt(er/in) - Auswärtiger Dienst (höh.Dienst),https://berufenet.arbeitsagentur.de/berufenet/...,skos:broadMatch
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4803,http://data.europa.eu/esco/occupation/7696b15a...,ufficiale di artiglieria,http://data.europa.eu/esco/occupation/7696b15a...,9.1.1.1.0,Ufficiali delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/7696b15a...,Artillerieoffizier/Artillerieoffizierin,http://data.europa.eu/esco/occupation/7696b15a...,15341,Offizier - Truppendienst,https://berufenet.arbeitsagentur.de/berufenet/...,skos:broadMatch
4810,http://data.europa.eu/esco/occupation/4a3f40a8...,caporal maggiore,http://data.europa.eu/esco/occupation/4a3f40a8...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/4a3f40a8...,Oberstabsgefreiter,http://data.europa.eu/esco/occupation/4a3f40a8...,15474,Soldat/in auf Zeit - Laufbahngruppe Mannschaften,https://berufenet.arbeitsagentur.de/berufenet/...,skos:broadMatch
4812,http://data.europa.eu/esco/occupation/c94dc5b2...,pilota dell’aeronautica militare,http://data.europa.eu/esco/occupation/c94dc5b2...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/c94dc5b2...,Kampfpilot/Kampfpilotin,http://data.europa.eu/esco/occupation/c94dc5b2...,15341,Offizier - Truppendienst,https://berufenet.arbeitsagentur.de/berufenet/...,skos:broadMatch
4814,http://data.europa.eu/esco/occupation/bd5a2f44...,soldato di fanteria,http://data.europa.eu/esco/occupation/bd5a2f44...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/bd5a2f44...,Grenadier/Grenadierin,http://data.europa.eu/esco/occupation/bd5a2f44...,15474,Soldat/in auf Zeit - Laufbahngruppe Mannschaften,https://berufenet.arbeitsagentur.de/berufenet/...,skos:broadMatch
4815,http://data.europa.eu/esco/occupation/35e67944...,responsabile informazioni operative,http://data.europa.eu/esco/occupation/35e67944...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/35e67944...,Mitarbeiter in einer Aufklärungsstelle/Mitarbe...,http://data.europa.eu/esco/occupation/35e67944...,15369,Beamt(er/in) - Fernmelde- u. Elektronische Auf...,https://berufenet.arbeitsagentur.de/berufenet/...,skos:exactMatch

In [131]:
cw_it_de_reduced_gmerged = pd.merge(
    left=cw_it_de_reduced,
    right=greenness_jrc,
    left_on="Classification_2_ID_it",
    right_on="isco08_jrc",
    how="left",
    validate="m:1"
)

# fill nans in greenness col with zeros
cw_it_de_reduced_gmerged["greenness_jrc"] = \
    cw_it_de_reduced_gmerged["greenness_jrc"].fillna(0)

cw_it_de_reduced_gmerged

,Classification_1_URI_it,Classification_1_PrefLabel_it,Classification_1_URL_it,Classification_2_ID_it,Classification_2_PrefLabel_it,Classification_2_URL_it,Mapping_relation_it,Editorial_note_it,Classification_1_URI_de,Classification_1_PrefLabel_de,Classification_1_URL_de,Classification_2_ID_de,Classification_2_PrefLabel_de,Classification_2_URL_de,Mapping_relation_de,isco08_jrc,occ_eng_jrc,n_green_tasks_jrc,n_tasks_jrc,greenness_jrc
0,http://data.europa.eu/esco/occupation/5bca96fd...,deputato/deputata,http://data.europa.eu/esco/occupation/5bca96fd...,1.1.1.1.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/5bca96fd...,Abgeordneter/Abgeordnete,http://data.europa.eu/esco/occupation/5bca96fd...,90855,Abgeordnete/r,https://berufenet.arbeitsagentur.de/berufenet/...,skos:exactMatch,NaN,NaN,NaN,NaN,0.0
1,http://data.europa.eu/esco/occupation/7226c10f...,assessore comunale/assessora comunale,http://data.europa.eu/esco/occupation/7226c10f...,1.1.1.3.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/7226c10f...,Stadtverordneter/Stadtverordnete,http://data.europa.eu/esco/occupation/7226c10f...,90680,Stadtrat/-rätin,https://berufenet.arbeitsagentur.de/berufenet/...,skos:exactMatch,NaN,NaN,NaN,NaN,0.0
2,http://data.europa.eu/esco/occupation/7226c10f...,assessore comunale/assessora comunale,http://data.europa.eu/esco/occupation/7226c10f...,1.1.1.4.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/7226c10f...,Stadtverordneter/Stadtverordnete,http://data.europa.eu/esco/occupation/7226c10f...,90680,Stadtrat/-rätin,https://berufenet.arbeitsagentur.de/berufenet/...,skos:exactMatch,NaN,NaN,NaN,NaN,0.0
3,http://data.europa.eu/esco/occupation/6cee3765...,sindaco/sindaca,http://data.europa.eu/esco/occupation/6cee3765...,1.1.1.4.0,Membri di organismi di governo e di assemblee ...,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/6cee3765...,Bürgermeister/Bürgermeisterin,http://data.europa.eu/esco/occupation/6cee3765...,90633,Bürgermeister/in,https://berufenet.arbeitsagentur.de/berufenet/...,skos:exactMatch,NaN,NaN,NaN,NaN,0.0
4,http://data.europa.eu/esco/occupation/a8d05b64...,console,http://data.europa.eu/esco/occupation/a8d05b64...,1.1.2.1.0,"Ambasciatori, ministri plenipotenziari ed alti...",http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/a8d05b64...,Konsul/Konsulin,http://data.europa.eu/esco/occupation/a8d05b64...,7609,Beamt(er/in) - Auswärtiger Dienst (höh.Dienst),https://berufenet.arbeitsagentur.de/berufenet/...,skos:broadMatch,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4611,http://data.europa.eu/esco/occupation/7696b15a...,ufficiale di artiglieria,http://data.europa.eu/esco/occupation/7696b15a...,9.1.1.1.0,Ufficiali delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/7696b15a...,Artillerieoffizier/Artillerieoffizierin,http://data.europa.eu/esco/occupation/7696b15a...,15341,Offizier - Truppendienst,https://berufenet.arbeitsagentur.de/berufenet/...,skos:broadMatch,NaN,NaN,NaN,NaN,0.0
4612,http://data.europa.eu/esco/occupation/4a3f40a8...,caporal maggiore,http://data.europa.eu/esco/occupation/4a3f40a8...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/4a3f40a8...,Oberstabsgefreiter,http://data.europa.eu/esco/occupation/4a3f40a8...,15474,Soldat/in auf Zeit - Laufbahngruppe Mannschaften,https://berufenet.arbeitsagentur.de/berufenet/...,skos:broadMatch,NaN,NaN,NaN,NaN,0.0
4613,http://data.europa.eu/esco/occupation/c94dc5b2...,pilota dell’aeronautica militare,http://data.europa.eu/esco/occupation/c94dc5b2...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/c94dc5b2...,Kampfpilot/Kampfpilotin,http://data.europa.eu/esco/occupation/c94dc5b2...,15341,Offizier - Truppendienst,https://berufenet.arbeitsagentur.de/berufenet/...,skos:broadMatch,NaN,NaN,NaN,NaN,0.0
4614,http://data.europa.eu/esco/occupation/bd5a2f44...,soldato di fanteria,http://data.europa.eu/esco/occupation/bd5a2f44...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/bd5a2f44...,Grenadier/Grenadierin,http://data.europa.eu/esco/occupation/bd5a2f44...,15474,Soldat/in auf Zeit - Laufbahngruppe Mannschaften,https://berufenet.arbeitsagentur.de/berufenet/...,skos:broadMatch,NaN,NaN,NaN,NaN,0.0
4615,http://data.europa.eu/esco/occupation/35e67944...,responsabile informazioni operative,http://data.europa.eu/esco/occupation/35e67944...,9.3.1.1.0,Truppa delle forze armate,http://professioni.istat.it/cp2011/scheda.php?...,skos:broadMatch,NaN,http://data.europa.eu/esco/occupation/35e67944...,Mitarbeiter in einer Aufklärungsstelle/Mitarbe...,http://data.europa.eu/esco/occupation/35e67944...,15369,Beamt(er/in) - Fernmelde- u. Elektronische Auf...,https://berufenet.arbeitsagentur.de/berufenet/...,skos:exactMatch,NaN,NaN,NaN,NaN,0.0

all but one 5-digit occ could be mapped to cw

In [134]:
cw_it_de_reduced_gmerged.isco08_jrc.unique().shape

(117,)

Greennest occupations in KldB

In [141]:
cw_it_de_reduced_gmerged[["Classification_1_PrefLabel_de", "greenness_jrc"]].replace\
    (0, np.nan).dropna()

                          Classification_1_PrefLabel_de  greenness_jrc
21    Leiter einer Gesundheitseinrichtung/Leiterin e...       0.090909
22    Leiter einer Gesundheitseinrichtung/Leiterin e...       0.090909
23    Leiter eines medizinischen Labors/Leiterin ein...       0.090909
24    Patientendatenverwalter/Patientendatenverwalterin       0.090909
25    Patientendatenverwalter/Patientendatenverwalterin       0.090909
...                                                 ...            ...
4542                                    Küster/Küsterin       0.076923
4543              Friedhofsarbeiter/Friedhofsarbeiterin       0.076923
4547            Garderobenaufseher/Garderobenaufseherin       0.083333
4548                          Kabinenwart/Kabinenwartin       0.083333
4562                        Waldarbeiter/Waldarbeiterin       0.076923

[884 rows x 2 columns]

#### Save final ds

In [135]:
cw_it_de_reduced_gmerged.to_csv(
    os.path.join(useful_paths.data_external, "crosswalks",
                 "crosswalk_it_cp2011_de_kldb2010_reduced_with_metadata.csv")
)